import asyncio, json
from pathlib import Path
from playwright.async_api import async_playwright
SITE=Path(__file__).resolve().parents[1]; HTML=(SITE/'index.html').read_text(encoding='utf-8'); OUT=SITE/'preview'; OUT.mkdir(exist_ok=True)
WALLET='0x1234567890abcdef1234567890abcdef12345678'; OTHER='0x9999999999999999999999999999999999999999'; WRAPPER='0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401'; SEPOLIA='0x0635513f179D50A207757E05759CbD106d7dFcE8'
POLY="""(()=>{const s=new Map();const ls={getItem:k=>s.has(String(k))?s.get(String(k)):null,setItem:(k,v)=>s.set(String(k),String(v)),removeItem:k=>s.delete(String(k)),clear:()=>s.clear(),key:i=>Array.from(s.keys())[i]??null,get length(){return s.size}};Object.defineProperty(window,'localStorage',{value:ls,configurable:true});})();"""
def wa(a):return '0x'+'0'*24+a[2:].lower()
def wu(n):return hex(n)[2:].rjust(64,'0')
def mock(mode='direct'):
 d=WALLET if mode=='direct' else (WRAPPER if mode in ('wrapped','expired') else (SEPOLIA if mode=='sepolia' else OTHER)); w=WALLET if mode in ('wrapped','expired','sepolia') else OTHER; exp=1 if mode=='expired' else 4102444800
 return f"""(()=>{{const l={{}},wallet='{WALLET}',ownerWord='{wa(d)}',wrappedWord='{wa(w)}',getData='0x'+wrappedWord.slice(2)+'{wu(0)}'+'{wu(exp)}';window.ethereum={{request:async({{method,params}})=>{{if(method==='eth_requestAccounts'||method==='eth_accounts')return[wallet];if(method==='eth_chainId')return'0x1';if(method==='wallet_switchEthereumChain')return null;if(method==='eth_blockNumber')return'0x1312d00';if(method==='eth_signTypedData_v4')return'0x'+'cd'.repeat(65);if(method==='personal_sign')return'0x'+'ab'.repeat(65);if(method==='eth_call'){{const data=(params?.[0]?.data||'').toLowerCase();if(data.startsWith('0x02571be3'))return ownerWord;if(data.startsWith('0x6352211e'))return wrappedWord;if(data.startsWith('0x0178fe3f'))return getData;return'0x'+'0'.repeat(64)}}throw new Error('Unsupported '+method)}},on:(e,cb)=>{{(l[e]||(l[e]=[])).push(cb)}},emit:(e,...a)=>{{(l[e]||[]).forEach(cb=>cb(...a))}}}}}})();"""
async def ctx(browser,mode='direct',vp=None):
 c=await browser.new_context(viewport=vp or {'width':1600,'height':1000},device_scale_factor=1,accept_downloads=True);await c.add_init_script(POLY);await c.add_init_script(mock(mode));return c
async def load(p):await p.set_content(HTML,wait_until='load')
async def gate(p,label):
 await p.fill('#agiClubLabelInput',label)
 for x in ['#agiClubOwnerConfirm','#agiClubLicenseConfirm','#agiClubBoundaryConfirm','#agiClubLanguageConfirm','#agiClubNoSecretsConfirm']:await p.check(x)
async def unlock(p,label):await gate(p,label);await p.click('#agiClubVerifyBtn');await p.wait_for_function("!document.body.classList.contains('agc-locked')")
def add(r,n,ok,d=''):r.append({'name':n,'passed':bool(ok),'detail':str(d)})
async def run():
 r=[]
 async with async_playwright() as pw:
  b=await pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
  c=await b.new_context(viewport={'width':1600,'height':1000});await c.add_init_script(POLY);p=await c.new_page();err=[];ext=[];p.on('pageerror',lambda e:err.append(str(e)));p.on('console',lambda m:err.append(m.text) if m.type=='error' else None);p.on('request',lambda q:ext.append(q.url) if q.url.startswith(('http://','https://')) else None);await load(p);add(r,'locked',await p.locator('body').evaluate("e=>e.classList.contains('agc-locked')"));add(r,'gate visible',await p.locator('#agiClubAccessGate').is_visible());add(r,'French-first legal confirmations',await p.locator('#agiClubLanguageConfirm').count()==1);add(r,'locked errors zero',not err,err);add(r,'locked external requests zero',not ext,ext);await p.screenshot(path=str(OUT/'01_sn5_final_locked.png'),full_page=False);await c.close()
  c=await ctx(b,'direct');p=await c.new_page();err=[];ext=[];p.on('pageerror',lambda e:err.append(str(e)));p.on('console',lambda m:err.append(m.text) if m.type=='error' else None);p.on('request',lambda q:ext.append(q.url) if q.url.startswith(('http://','https://')) else None);await load(p);await unlock(p,'founder');add(r,'direct owner unlock',True);add(r,'EIP-712 recorded','eip712' in (await p.locator('#ownerVaultSignatureMode').inner_text()).lower());await p.evaluate("document.querySelector('#ownerAccessDialog')?.close()");await p.evaluate("document.querySelector('#demoBtn').click();document.querySelector('#runMission').click()");await p.wait_for_timeout(5200);add(r,'12 architectures',await p.locator('#heroScenarios').inner_text()=='12');add(r,'21 bounded jobs',(await p.locator('#jobs').inner_text()).count('Budget index')==21);await p.evaluate("document.querySelector('button[data-route=opportunity]').click()");add(r,'Apex portfolio',await p.locator('#sn5ProposalPortfolio article').count()==3);add(r,'Value-of-Proof',await p.locator('#sn5Vop .sn5-vop-row').count()>0);await p.screenshot(path=str(OUT/'02_sn5_final_opportunity.png'),full_page=False);await p.evaluate("document.querySelector('button[data-route=masterclass]').click()");txt=await p.locator('#view-masterclass').inner_text();add(r,'204-page SN5 MasterClass visible','204-page' in txt and 'SN5 Constitutional' in txt);await p.evaluate("document.querySelector('button[data-route=legal]').click()");add(r,'French legal default','Cadre opérationnel' in await p.locator('#view-legal').inner_text());await p.evaluate("document.querySelector('[data-legal-lang=en]').click()");add(r,'English legal selection','Operating boundary' in await p.locator('#view-legal').inner_text());routes=[]
  for btn in await p.locator('nav button[data-route]').all():
   route=await btn.get_attribute('data-route')
   if route in routes:continue
   routes.append(route);await p.evaluate('(x)=>document.querySelector(`nav button[data-route=${x}]`).click()',route);await p.wait_for_timeout(25);add(r,f'route {route}',await p.locator(f'#view-{route}').evaluate("e=>e.classList.contains('active')"))
  add(r,'16 routes',len(routes)==16,routes);add(r,'direct errors zero',not err,err);add(r,'direct external requests zero',not ext,ext);await c.close()
  c=await ctx(b,'wrapped',{'width':1365,'height':900});p=await c.new_page();await load(p);await unlock(p,'wrapped');add(r,'official Mainnet wrapped owner unlock',True);await c.close()
  c=await ctx(b,'sepolia',{'width':1280,'height':850});p=await c.new_page();await load(p);await gate(p,'sepolia');await p.click('#agiClubVerifyBtn');await p.wait_for_timeout(500);add(r,'Sepolia wrapper rejected on Mainnet',await p.locator('body').evaluate("e=>e.classList.contains('agc-locked')"));add(r,'Sepolia rejection explained','official ethereum mainnet name wrapper' in (await p.locator('#agiClubGateStatus').inner_text()).lower());await c.close()
  for mode,label,needle,name in [('wrong','wrong','not the connected wallet','wrong owner'),('expired','expired','expired','expired name')]:
   c=await ctx(b,mode,{'width':1280,'height':850});p=await c.new_page();await load(p);await gate(p,label);await p.click('#agiClubVerifyBtn');await p.wait_for_timeout(500);add(r,name+' denied',await p.locator('body').evaluate("e=>e.classList.contains('agc-locked')"));add(r,name+' reason',needle in (await p.locator('#agiClubGateStatus').inner_text()).lower());await c.close()
  c=await ctx(b,'direct',{'width':390,'height':844});p=await c.new_page();me=[];p.on('pageerror',lambda e:me.append(str(e)));await load(p);add(r,'mobile locked overflow',(await p.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth'))<=1);await unlock(p,'mobile');await p.evaluate("document.querySelector('#ownerAccessDialog')?.close();document.querySelector('#demoBtn').click();document.querySelector('#runMission').click()");await p.wait_for_timeout(5200);await p.evaluate("document.querySelector('button[data-route=opportunity]').click()");add(r,'mobile unlocked overflow',(await p.evaluate('document.documentElement.scrollWidth-document.documentElement.clientWidth'))<=1);add(r,'mobile errors zero',not me,me);await p.screenshot(path=str(OUT/'03_sn5_final_mobile.png'),full_page=False);await c.close();await b.close()
 out={'passed':all(x['passed'] for x in r),'assertions':len(r),'results':r};(SITE/'documentation'/'QA_REPORT.json').write_text(json.dumps(out,indent=2),encoding='utf-8');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
asyncio.run(run())
