(() => {
'use strict';
const D=window.VSI3_DATA,R=D.records,CFG=window.VSI3_CONFIG;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const short=(v,n=10)=>{const s=String(v||'');return s.length>n*2+1?`${s.slice(0,n)}…${s.slice(-n)}`:s;};
const fmt=n=>new Intl.NumberFormat('en-CA',{maximumFractionDigits:3}).format(Number(n)||0);
const canonical=v=>v===undefined?'null':v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(canonical).join(',')}]`:`{${Object.keys(v).filter(k=>v[k]!==undefined).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;
const textBytes=t=>new TextEncoder().encode(t);
const hexOf=buffer=>[...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('');
function sha256Sync(value){let ascii=unescape(encodeURIComponent(typeof value==='string'?value:canonical(value))),words=[],bitLen=ascii.length*8;const rr=(n,x)=>(x>>>n)|(x<<(32-n)),p=Math.pow,maxWord=p(2,32),lengthProperty='length';let result='',hash=[],k=[],isComposite={};let primeCounter=0,candidate=2;while(primeCounter<64){if(!isComposite[candidate]){for(let i=0;i<313;i+=candidate)isComposite[i]=candidate;hash[primeCounter]=(p(candidate,.5)*maxWord)|0;k[primeCounter++]=(p(candidate,1/3)*maxWord)|0;}candidate++;}ascii+='\x80';while(ascii[lengthProperty]%64-56)ascii+='\x00';for(let i=0;i<ascii[lengthProperty];i++){const j=ascii.charCodeAt(i);if(j>>8)return '';words[i>>2]|=j<<((3-i)%4)*8;}words[words[lengthProperty]]=((bitLen/maxWord)|0);words[words[lengthProperty]]=bitLen;for(let j=0;j<words[lengthProperty];){const w=words.slice(j,j+=16),oldHash=hash.slice(0);hash=hash.slice(0,8);for(let i=0;i<64;i++){const w15=w[i-15],w2=w[i-2],a=hash[0],e=hash[4],temp1=hash[7]+(rr(6,e)^rr(11,e)^rr(25,e))+((e&hash[5])^((~e)&hash[6]))+k[i]+(w[i]=(i<16)?w[i]:((w[i-16]+(rr(7,w15)^rr(18,w15)^(w15>>>3))+w[i-7]+(rr(17,w2)^rr(19,w2)^(w2>>>10)))|0));const temp2=(rr(2,a)^rr(13,a)^rr(22,a))+((a&hash[1])^(a&hash[2])^(hash[1]&hash[2]));hash=[(temp1+temp2)|0,a,hash[1],hash[2],(hash[3]+temp1)|0,e,hash[5],hash[6]];}for(let i=0;i<8;i++)hash[i]=(hash[i]+oldHash[i])|0;}for(let i=0;i<8;i++)for(let j=3;j+1;j--){const b=(hash[i]>>(j*8))&255;result+=(b<16?'0':'')+b.toString(16);}return result;}
const sha=async value=>crypto?.subtle?hexOf(await crypto.subtle.digest('SHA-256',textBytes(typeof value==='string'?value:canonical(value)))):sha256Sync(value);
const download=(name,text,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000);};
const downloadJSON=(name,obj)=>download(name,JSON.stringify(obj,null,2)+'\n');
const storage={get:(k,d='')=>{try{return localStorage.getItem(k)??d}catch{return d}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch{}}};
let savedRoles={};try{savedRoles=JSON.parse(storage.get('vsi3_role_signatures','{}'))||{}}catch{}
const state={section:'overview',authorityPhase:'initial',roleSignatures:savedRoles,proofRun:null,requalificationStep:0};
const sections=['overview','mainnet','constitution','execution','proof','admission','authority','requalification','chronicle','developer'];
function chip(text,tone='neutral'){return `<span class="chip ${tone}">${esc(text)}</span>`;}
function hashLine(label,value){return `<div class="hash-line"><span>${esc(label)}</span><code title="${esc(value)}">${esc(short(value,12))}</code><button data-copy="${esc(value)}" aria-label="Copy ${esc(label)}">Copy</button></div>`;}
function metric(label,value,detail=''){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</div>`;}
function callout(title,body,tone='navy'){return `<div class="callout ${tone}"><strong>${esc(title)}</strong><span>${body}</span></div>`;}
function setSection(id,push=true){if(!sections.includes(id))id='overview';state.section=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${id}`));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));$('#pageTitle').textContent=$(`[data-nav="${id}"]`)?.dataset.title||'Verified Succession Institution';if(push)history.replaceState(null,'',`#${id}`);document.querySelector('#main')?.scrollTo?.({top:0,behavior:'smooth'});}
function bindCommon(){
  $$('[data-nav]').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.nav)));
  document.addEventListener('click',e=>{const c=e.target.closest('[data-copy]');if(c){navigator.clipboard?.writeText(c.dataset.copy);c.textContent='Copied';setTimeout(()=>c.textContent='Copy',1000);}const d=e.target.closest('[data-download-record]');if(d){const key=d.dataset.downloadRecord;downloadJSON(`${key}.json`,R[key]);}});
  $('#menuButton')?.addEventListener('click',()=>$('#sidebar')?.classList.toggle('open'));
  $('#closeMenuButton')?.addEventListener('click',()=>$('#sidebar')?.classList.remove('open'));
  $('#lockButton')?.addEventListener('click',()=>window.VSI3Access?.lock('Access was manually locked.'));
}
function renderOverview(){const m=R.missionConstitution,p=R.freshProofInitial,a=R.admissionRecordInitial,e=R.authorityEnvelopeInitial,q=R.requalificationRecord,vr=R.cycleVerificationReport;
  $('#view-overview').innerHTML=`
  <section class="hero-panel">
    <div class="hero-copy"><span class="eyebrow">Successor Ω × AGI Jobs · v3.0.0</span><h1>The first executable proof-bearing succession cycle.</h1><p>Actual AGI Jobs on Ethereum Mainnet are connected to a separately reproducible reference cycle in which one exact Candidate Successor is frozen, evaluated by an independent proof process, separately admitted, constrained by an enforceable Authority Envelope, impaired, rolled back and requalified as a new release.</p><div class="hero-actions"><button class="button gold" data-nav-jump="mainnet">Inspect actual jobs</button><button class="button outline" data-nav-jump="proof">Verify fresh proof</button></div></div>
    <div class="omega-orbit" aria-hidden="true"><span>Ω</span><i></i><b></b></div>
  </section>
  ${callout('Governing doctrine','AGI Jobs manufacture candidacy. Fresh proof may establish Specialist ASI. Only accountable admission creates Successor Ω. Chronicle prepares the successor to the successor.','navy')}
  <div class="metric-grid">${metric('Executable runtime',vr.pass?'PASS':'FAIL',`${Object.keys(vr.checks).length} integrity checks`)}${metric('Formation / fresh / transfer',`${m.proofBudget.formationEpisodes} / ${m.proofBudget.freshCases} / ${m.proofBudget.transferCases}`,'separated evidence partitions')}${metric('Fresh-proof margin',fmt(p.pairedComparison.lower_confidence_bound),'95% lower confidence bound')}${metric('Authority',e.level==='A1_RECOMMEND_ONLY'?'A1 · RECOMMEND':e.level,'0 external actions · 0 spend')}${metric('Rollback',q.rollbackExecuted?'EXECUTED':'NOT EXECUTED',m.fallback)}${metric('Requalification',q.verdict==='REQUALIFICATION_TEST_PASS'?'PASS':q.verdict,'new proof · new admission · new authority')}</div>
  <section class="panel"><div class="panel-head"><div><span class="eyebrow">One complete cycle</span><h2>Capability is never allowed to collapse into authority.</h2></div>${chip('REFERENCE CYCLE VERIFIED','pass')}</div><div class="cycle-rail">
    ${[['01','Mission Constitution','Frozen'],['02','Actual AGI Jobs','Bounded'],['03','Candidate Release','Frozen'],['04','Fresh Proof','Signed'],['05','Admission','Separate'],['06','Authority','Revocable'],['07','Impairment','Detected'],['08','Rollback','Executed'],['09','Requalification','Passed']].map((x,i)=>`<button data-nav-jump="${['constitution','mainnet','execution','proof','admission','authority','requalification','requalification','requalification'][i]}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></button>`).join('')}
  </div></section>
  <div class="two-col"><section class="panel"><div class="panel-head"><h2>Exact institutional identity</h2></div>${hashLine('Mission Constitution',m.constitutionSha256)}${hashLine('Candidate release',R.candidateManifestInitial.releaseId)}${hashLine('Candidate manifest',R.candidateManifestInitial.manifestSha256)}${hashLine('Protected cases',p.protectedCaseCommitment)}${hashLine('Chronicle head',R.chronicleLedger.headHash)}</section>
  <section class="panel"><div class="panel-head"><h2>Claim boundary</h2></div><p>${esc(m.claimBoundary)}</p><p>This is a real executable, signed and tested <strong>reference cycle over synthetic mission data</strong>. It does not claim that a customer system has earned production Specialist ASI, and it controls no physical grid.</p>${chip('AUTHORITY CREATED BY ACCESS: NONE','neutral')}</section></div>`;
  $$('[data-nav-jump]').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.navJump)));
}
function renderMainnet(){
  $('#view-mainnet').innerHTML=`<section class="page-intro"><span class="eyebrow">Actual AGI Jobs · Ethereum Mainnet</span><h1>On-chain work and settlement, not a simulated marketplace.</h1><p>The application reconstructs the Prime job ledger directly from contract logs and exposes transaction workbenches only after explicit simulation and confirmation.</p></section>
  <div class="contract-strip"><div><span>Official AGIALPHA</span><a data-contract="token" target="_blank" rel="noopener"></a></div><div><span>Manager Prime</span><a data-contract="agiJobManagerPrime" target="_blank" rel="noopener"></a></div><div><span>Discovery Prime</span><a data-contract="agiJobDiscoveryPrime" target="_blank" rel="noopener"></a></div><div><span>Genesis Manager</span><a data-contract="agiJobManagerGenesis" target="_blank" rel="noopener"></a></div></div>
  <section class="panel"><div class="panel-head"><div><h2>Live Prime ledger</h2><p>Wallet-provider JSON-RPC · direct event reconstruction</p></div><div class="panel-actions"><span id="mainnetStatus" class="inline-status neutral">Waiting for access</span><button id="refreshMainnetButton" class="button outline">Refresh Mainnet</button></div></div><div id="mainnetSummary" class="summary-row"><div><span>Prime jobs</span><strong>—</strong></div><div><span>Decoded jobs</span><strong>—</strong></div><div><span>Events scanned</span><strong>—</strong></div><div><span>Contract code</span><strong>—</strong></div></div><div id="mainnetJobs"><div class="empty-state"><strong>Connect through the access gate.</strong><span>Live chain reconstruction begins after the qualifying wallet is connected on Ethereum Mainnet.</span></div></div></section>
  <section class="panel transaction-panel"><div class="panel-head"><div><span class="eyebrow">Optional real transaction workbench</span><h2>Create and advance actual AGI Jobs</h2></div><label class="switch"><input type="checkbox" id="enableTransactions"><span></span>Enable Mainnet writes</label></div>${callout('Separate from access verification','Access never requests a token approval, transfer, payment, staking, locking or custody. This workbench is a distinct, optional protocol interaction. Every write is simulated, described and confirmed before the wallet is opened.','amber')}
    <div class="workbench-grid"><div class="form-card"><h3>Post a job</h3><label>Job specification URI<input id="jobSpecUri" placeholder="ipfs://… or https://…"></label><div class="form-row"><label>Payout in AGIALPHA<input id="jobPayout" inputmode="decimal" value="100"></label><label>Duration in seconds<input id="jobDuration" inputmode="numeric" value="86400"></label></div><label>Public details<textarea id="jobDetails" rows="3" placeholder="Bounded purpose and acceptance context"></textarea></label><div class="button-row"><button id="approveExactButton" class="button outline">Approve exact payout</button><button id="createJobButton" class="button gold">Create Mainnet job</button></div></div>
    <div class="form-card"><h3>Advance a job</h3><label>Job ID<input id="actionJobId" inputmode="numeric" value="0"></label><label>Action<select id="jobAction"><option value="requestJobCompletion">Request completion</option><option value="finalizeJob">Finalize</option><option value="disputeJob">Dispute</option><option value="expireJob">Expire</option><option value="cancelJob">Cancel</option></select></label><label id="completionUriField">Completion URI<input id="completionUri" placeholder="ipfs://…"></label><button id="submitJobActionButton" class="button gold">Simulate and submit</button><p class="micro">Agent application and validator voting require authorization identities and proofs. Use the canonical AGI Jobs console for those advanced paths.</p></div></div><div id="transactionResult" class="transaction-result">No transaction prepared.</div></section>`;
}
function renderConstitution(){const m=R.missionConstitution,g=R.typedJobGraph;const familyTone={constitution:'navy',evidence:'blue',formation:'gold',challenge:'red',verification:'violet',admission:'green',renewal:'teal'};
  $('#view-constitution').innerHTML=`<section class="page-intro"><span class="eyebrow">Mission Constitution + typed Job Graph</span><h1>Every job belongs to one exact mission and creates no authority.</h1><p>A flat task list cannot manufacture an institution. The reference graph binds work to explicit principals, evidence obligations, prohibited actions, budgets, rollback and typed dependencies.</p></section>
  <div class="two-col"><section class="panel"><div class="panel-head"><h2>${esc(m.name)}</h2>${chip('FROZEN','pass')}</div><dl class="definition-list"><dt>Objective</dt><dd>${esc(m.objective)}</dd><dt>Incumbent</dt><dd>${esc(m.incumbent)}</dd><dt>Best credible alternative</dt><dd>${esc(m.bestCredibleAlternative)}</dd><dt>Authority ceiling</dt><dd>${esc(m.authorityCeiling)}</dd><dt>Fallback</dt><dd>${esc(m.fallback)}</dd></dl>${hashLine('Constitution SHA-256',m.constitutionSha256)}</section>
  <section class="panel"><div class="panel-head"><h2>Non-compensable gates</h2>${chip(`${m.hardGates.length} GATES`,'neutral')}</div><ol class="gate-list">${m.hardGates.map(x=>`<li><span>✓</span>${esc(x)}</li>`).join('')}</ol><h3>Prohibited effects</h3><div class="tag-list">${m.prohibitedEffects.map(x=>`<span>${esc(x)}</span>`).join('')}</div></section></div>
  <section class="panel graph-panel"><div class="panel-head"><div><h2>Executable manufacturing graph</h2><p>Evidence → challenge → control → invalidation → rollback</p></div>${chip(g.compiler.pass?'COMPILER PASS':'COMPILER REFUSAL',g.compiler.pass?'pass':'fail')}</div><div class="job-graph">${g.jobs.map((j,i)=>`<article class="job-node ${familyTone[j.family]||''}"><div><span>${j.jobId}</span>${chip(j.family,'neutral')}</div><h3>${esc(j.title)}</h3><p>${esc(j.objective)}</p><footer><small>${j.state}</small><b>AUTHORITY: ${j.authorityCreated}</b></footer>${i<g.jobs.length-1?`<i class="edge ${esc(g.edges[i]?.type||'evidence')}">${esc(g.edges[i]?.type||'evidence')} →</i>`:''}</article>`).join('')}</div></section>
  <section class="panel"><div class="panel-head"><h2>Compiler assurance</h2><button class="button outline" data-download-record="typedJobGraph">Download Job Graph</button></div><div class="metric-grid compact">${Object.entries(g.compiler).filter(([k])=>k!=='pass').map(([k,v])=>metric(k.replace(/[A-Z]/g,m=>' '+m).replace(/^./,c=>c.toUpperCase()),v?'PASS':'FAIL')).join('')}</div>${hashLine('Graph SHA-256',g.graphSha256)}</section>`;
}
function renderExecution(){const m0=R.candidateManifestInitial,m1=R.candidateManifestRequalification;
  $('#view-execution').innerHTML=`<section class="page-intro"><span class="eyebrow">Protected execution</span><h1>Formation may learn. Fresh proof may not.</h1><p>The packaged Python runtime executed two exact cycles. The browser rehearsal below repeats the one-way interface: the proof worker retains hidden truth, the candidate receives observations only, and scoring returns no gradient or learning signal.</p></section>
  <div class="release-compare"><section class="panel"><span class="eyebrow">Initial release</span><h2>${esc(m0.algorithm.name)}</h2>${hashLine('Release ID',m0.releaseId)}${hashLine('Policy state',m0.policyStateSha256)}${hashLine('Verifier bundle',m0.verifierBundleSha256)}<p>${chip('LEARNING AFTER FREEZE: NO','pass')}</p></section><div class="succession-arrow">Ω<br><small>material change</small><span>→</span></div><section class="panel"><span class="eyebrow">Requalified release</span><h2>${esc(m1.algorithm.name)}</h2>${hashLine('Release ID',m1.releaseId)}${hashLine('Policy state',m1.policyStateSha256)}${hashLine('Verifier bundle',m1.verifierBundleSha256)}<p>${chip('NEW EXACT RELEASE','pass')}</p></section></div>
  <section class="panel"><div class="panel-head"><div><h2>One-way proof rehearsal</h2><p>Isolated browser workers · 48 hidden synthetic cases</p></div><button id="runProofRehearsal" class="button gold">Run sealed rehearsal</button></div><div id="proofRehearsalOutput" class="console"><span>Ready. No case truth has been revealed to the candidate.</span></div></section>
  <div class="three-col"><section class="panel"><h3>Candidate process</h3><p>Receives only role-authorized observations. Returns bounded action objects. Holds no scorer, protected seed, admission or release credentials.</p></section><section class="panel"><h3>Proof process</h3><p>Generates and commits hidden cases, scores reserve safety and paired value, and emits a fail-closed verdict without training calls.</p></section><section class="panel"><h3>Production boundary</h3><p>The browser worker is inspectable rehearsal. The complete suite includes a separately deployable proof-custody package for protected infrastructure.</p></section></div>`;
  $('#runProofRehearsal')?.addEventListener('click',runProofRehearsal);
}
function workerUrl(kind){if(window.VSI3_INLINE_WORKERS?.[kind])return URL.createObjectURL(new Blob([window.VSI3_INLINE_WORKERS[kind]],{type:'text/javascript'}));return `assets/workers/${kind}-worker.js`;}
function workerRequest(worker,message,expected){return new Promise((resolve,reject)=>{const id=crypto.randomUUID?.()||('id-'+Date.now()+'-'+Math.random().toString(16).slice(2));const timer=setTimeout(()=>reject(new Error('Worker timeout')),15000);const fn=e=>{if(e.data?.id===id&&e.data?.type===expected){clearTimeout(timer);worker.removeEventListener('message',fn);resolve(e.data);}};worker.addEventListener('message',fn);worker.postMessage({...message,id});});}
async function runProofRehearsal(){const out=$('#proofRehearsalOutput'),button=$('#runProofRehearsal');button.disabled=true;out.innerHTML='<span>01 · Proof worker is sealing hidden cases…</span>';let proofWorker,candidateWorker;try{
  proofWorker=new Worker(workerUrl('proof'));candidateWorker=new Worker(workerUrl('candidate'));
  const prepared=await workerRequest(proofWorker,{type:'prepare',seed:20260817,count:48},'prepared');out.innerHTML+=`<span>02 · Commitment <code>${short(prepared.commitment,16)}</code> · ${prepared.caseCount} cases</span><span>03 · Sending observations—not truth—to frozen candidate…</span>`;
  const acted=await workerRequest(candidateWorker,{type:'act',observations:prepared.observations},'actions');out.innerHTML+=`<span>04 · ${acted.actions.length} bounded actions returned · no scorer access</span><span>05 · Independent worker scoring hidden truth…</span>`;
  const scored=await workerRequest(proofWorker,{type:'score',actions:acted.actions},'scored');state.proofRun=scored;out.innerHTML+=`<strong class="${scored.verdict.endsWith('PASS')?'pass-text':'fail-text'}">${scored.verdict}</strong><span>Mean paired gain: ${fmt(scored.meanPairedGain)} · critical failures: ${scored.criticalFailures} · unauthorized actions: ${scored.unauthorizedActions}</span><span>Learning calls during proof: ${scored.learningCallsDuringProof}</span><small>${esc(scored.claimBoundary)}</small>`;
  }catch(e){out.innerHTML+=`<strong class="fail-text">${esc(e.message||e)}</strong>`;}finally{proofWorker?.terminate();candidateWorker?.terminate();button.disabled=false;}}
function pemBytes(pem){const b64=pem.replace(/-----[^-]+-----/g,'').replace(/\s/g,'');return Uint8Array.from(atob(b64),c=>c.charCodeAt(0));}
async function verifyRecord(record){const sig=record.signature;if(!sig)return {pass:false,error:'No signature'};const role=Object.values(R.publicKeys.roles).find(x=>x.keyId===sig.keyId);if(!role)return {pass:false,error:'Public key not found'};const unsigned=structuredClone(record);delete unsigned.signature;const digest=await sha(unsigned);if(!crypto?.subtle){const row=R.signatureVerificationReport?.results?.find(x=>x.keyId===sig.keyId&&x.payloadSha256===digest);return {pass:Boolean(row?.pass)&&digest===sig.signedPayloadSha256,keyId:sig.keyId,payloadSha256:digest,fallback:true,error:row?'WebCrypto unavailable; exact release verified by packaged Node.js report.':'No packaged verification match.'};}try{const key=await crypto.subtle.importKey('spki',pemBytes(role.publicKeyPem),{name:'Ed25519'},false,['verify']);const pass=await crypto.subtle.verify({name:'Ed25519'},key,Uint8Array.from(atob(sig.valueBase64),c=>c.charCodeAt(0)),textBytes(canonical(unsigned)));return {pass,keyId:sig.keyId,payloadSha256:digest,fallback:false};}catch(e){const row=R.signatureVerificationReport?.results?.find(x=>x.keyId===sig.keyId&&x.payloadSha256===digest);return {pass:Boolean(row?.pass)&&digest===sig.signedPayloadSha256,keyId:sig.keyId,payloadSha256:digest,fallback:true,error:`Browser Ed25519 unavailable: ${e.message}`};}}
function renderProof(){const p0=R.freshProofInitial,p1=R.freshProofRequalification;
  $('#view-proof').innerHTML=`<section class="page-intro"><span class="eyebrow">Independent Fresh Proof</span><h1>One frozen challenger. Protected work. Signed verdict.</h1><p>Formation metrics guide search; they cannot certify the winner. The proof plane uses separately committed cases, zero proof-time learning, matched comparison, hard gates and a distinct Ed25519 verifier identity.</p></section>
  ${callout('Fresh-proof firewall',`${esc(p0.proofPlane)} · ${p0.caseCount} protected fresh cases · ${p0.transferCaseCount} transfer cases · ${p0.learningCallsDuringProof} learning calls. A proof verdict creates <strong>no authority</strong>.`,'navy')}
  <div class="metric-grid">${metric('Mean paired gain',fmt(p0.pairedComparison.mean_paired_gain))}${metric('95% lower bound',fmt(p0.pairedComparison.lower_confidence_bound))}${metric('95% upper bound',fmt(p0.pairedComparison.upper_confidence_bound))}${metric('Proof-adjusted Alpha',fmt(p0.proofAdjustedAlpha))}${metric('Critical failures',String(p0.hardGates.critical_misses??0))}${metric('Verdict',p0.verdict==='SYNTHETIC_REFERENCE_PROMOTION_ELIGIBLE'?'PROMOTION ELIGIBLE':p0.verdict)}</div>
  <div class="two-col"><section class="panel"><div class="panel-head"><h2>Initial protected proof</h2><button id="verifyProofInitial" class="button outline">Verify signature</button></div>${hashLine('Candidate',p0.candidateReleaseId)}${hashLine('Protected commitment',p0.protectedCaseCommitment)}${hashLine('Transfer commitment',p0.transferCaseCommitment)}${hashLine('Signed payload',p0.signature.signedPayloadSha256)}<div id="proofInitialVerification" class="verification-result">Not yet checked in this browser.</div></section>
  <section class="panel"><div class="panel-head"><h2>Requalification proof</h2><button id="verifyProofRenewal" class="button outline">Verify signature</button></div>${hashLine('Candidate',p1.candidateReleaseId)}${hashLine('Protected commitment',p1.protectedCaseCommitment)}${hashLine('Transfer commitment',p1.transferCaseCommitment)}${hashLine('Signed payload',p1.signature.signedPayloadSha256)}<div id="proofRenewalVerification" class="verification-result">Not yet checked in this browser.</div></section></div>
  <section class="panel"><div class="panel-head"><h2>Hard-gate result</h2>${chip(p0.hardGates.pass?'ALL PASS':'FAIL',p0.hardGates.pass?'pass':'fail')}</div><pre class="json-view">${esc(JSON.stringify(p0.hardGates,null,2))}</pre></section>`;
  $('#verifyProofInitial')?.addEventListener('click',()=>showVerification(p0,'#proofInitialVerification'));
  $('#verifyProofRenewal')?.addEventListener('click',()=>showVerification(p1,'#proofRenewalVerification'));
}
async function showVerification(record,selector){const el=$(selector);el.textContent='Verifying Ed25519 signature…';const v=await verifyRecord(record);el.innerHTML=v.pass?`${chip(v.fallback?'PACKAGED VERIFICATION PASS':'SIGNATURE VALID','pass')} <code>${esc(short(v.keyId,14))}</code>${v.fallback?` <small>${esc(v.error||'')}</small>`:''}`:`${chip('SIGNATURE INVALID','fail')} ${esc(v.error||'')}`;}
function renderAdmission(){const a=R.admissionRecordInitial,p=R.freshProofInitial;
  $('#view-admission').innerHTML=`<section class="page-intro"><span class="eyebrow">Accountable admission</span><h1>Proof eligibility is not institutional permission.</h1><p>A distinct principal reviews the exact proof, rights, burden, residual uncertainty, fallback and authority ceiling. The candidate and verifier cannot issue the admission transition.</p></section>
  <div class="two-col"><section class="panel"><div class="panel-head"><h2>Official reference admission</h2>${chip(a.decision,'pass')}</div><dl class="definition-list"><dt>Admitted state</dt><dd>${esc(a.admittedState)}</dd><dt>Candidate</dt><dd><code>${esc(short(a.candidateReleaseId,18))}</code></dd><dt>Authority ceiling</dt><dd>${esc(a.authorityCeiling)}</dd><dt>Rollback</dt><dd>${esc(a.rollbackTarget)}</dd><dt>Independent of producer</dt><dd>${a.admitterIndependentOfProducer?'YES':'NO'}</dd><dt>Independent of verifier</dt><dd>${a.admitterIndependentOfVerifier?'YES':'NO'}</dd></dl><div class="tag-list">${a.conditions.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${hashLine('Proof record',a.proofSha256)}${hashLine('Admission signature',a.signature.signedPayloadSha256)}<button id="verifyAdmission" class="button outline">Verify official signature</button><div id="admissionVerification" class="verification-result">Not yet checked.</div></section>
  <section class="panel"><div class="panel-head"><h2>Multi-wallet separation rehearsal</h2>${chip('OPTIONAL','neutral')}</div><p>Three different Ethereum accounts may sign role-bound acknowledgements. These signatures demonstrate attributable separation; they do not replace the official Ed25519 records or create authority.</p><div class="role-signers">${['verifier','admitter','governor'].map(role=>`<div><span>${role}</span><strong id="role-${role}">${state.roleSignatures[role]?esc(short(state.roleSignatures[role].wallet)):'Not signed'}</strong><button data-sign-role="${role}" class="button outline">Sign as ${role}</button></div>`).join('')}</div><div id="roleSigningStatus" class="verification-result">Each role must use a distinct wallet.</div></section></div>
  ${callout('Admission claim boundary',a.claimBoundary,'amber')}`;
  $('#verifyAdmission')?.addEventListener('click',()=>showVerification(a,'#admissionVerification'));
  $$('[data-sign-role]').forEach(b=>b.addEventListener('click',()=>signRole(b.dataset.signRole,p.candidateReleaseId)));
}
async function signRole(role,release){const out=$('#roleSigningStatus');try{if(!window.ethereum)throw new Error('Wallet not found.');const accounts=await window.ethereum.request({method:'eth_requestAccounts'}),wallet=accounts?.[0]?.toLowerCase();if(!wallet)throw new Error('No account returned.');const other=Object.entries(state.roleSignatures).find(([r,v])=>r!==role&&v.wallet===wallet);if(other)throw new Error(`This wallet already signed as ${other[0]}. Separation requires another account.`);const at=new Date().toISOString(),message=[`Successor Omega v3 role acknowledgement`,`Role: ${role}`,`Release: ${release}`,`Wallet: ${wallet}`,`Time: ${at}`,`Authority created: NONE`].join('\n');const hex='0x'+[...new TextEncoder().encode(message)].map(x=>x.toString(16).padStart(2,'0')).join('');const signature=await window.ethereum.request({method:'personal_sign',params:[hex,wallet]});state.roleSignatures[role]={wallet,at,message,signature};storage.set('vsi3_role_signatures',JSON.stringify(state.roleSignatures));$(`#role-${role}`).textContent=short(wallet);out.innerHTML=chip(`${role.toUpperCase()} SIGNED`,'pass')+' Switch the wallet before signing another role.';}catch(e){out.innerHTML=chip('NOT SIGNED','fail')+' '+esc(e.message||e);}}
function currentEnvelope(){return state.authorityPhase==='contracted'?R.authorityEnvelopeContracted:state.authorityPhase==='requalified'?R.authorityEnvelopeRequalification:R.authorityEnvelopeInitial;}
function evaluateAuthority(envelope,action){const statePermits=envelope.state==='ACTIVE'||(envelope.state==='IMPAIRED'&&envelope.level==='A0_READ_ONLY');const allowed=statePermits&&envelope.allowedActions.includes(action);return {decision:allowed?'ALLOW':'DENY',reason:allowed?'Exact release, current evidence and Authority Envelope permit this action.':!statePermits?'Envelope is inactive or impaired beyond this action.':'Action is outside the current Authority Envelope.'};}
function renderAuthority(){const e=currentEnvelope(),tests=R.authorityGatewayTests;
  $('#view-authority').innerHTML=`<section class="page-intro"><span class="eyebrow">Enforceable Authority Envelope</span><h1>Consequential constraints live outside the candidate.</h1><p>The packaged gateway verifies the signed envelope, exact release and evidence state before allowing a named action. Prompting a model to behave is not an authority system.</p></section>
  <div class="authority-banner ${e.level==='A0_READ_ONLY'?'contracted':''}"><div><span>${esc(e.phase)} · ${esc(e.state)}</span><h2>${esc(e.level)}</h2><p>Release <code>${esc(short(e.releaseId,18))}</code></p></div><div>${metric('External action limit',String(e.externalActionLimit))}${metric('Spend limit',String(e.spendLimit))}${metric('Human approval',e.humanApprovalRequired?'REQUIRED':'NO')}</div></div>
  <div class="two-col"><section class="panel"><h2>Allowed actions</h2><div class="action-list allowed">${e.allowedActions.map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div><h2>Prohibited actions</h2><div class="action-list denied">${e.prohibitedActions.map(x=>`<span>× ${esc(x)}</span>`).join('')}</div></section>
  <section class="panel"><div class="panel-head"><h2>Gateway evaluator</h2>${chip('FAIL-CLOSED','pass')}</div><label>Requested action<select id="authorityAction">${[...new Set([...e.allowedActions,...e.prohibitedActions])].map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><button id="evaluateAuthorityButton" class="button gold">Evaluate action</button><div id="authorityDecision" class="authority-decision">No request evaluated.</div><div class="phase-buttons"><button data-authority-phase="initial" class="button outline">Initial</button><button data-authority-phase="contracted" class="button outline">Impaired</button><button data-authority-phase="requalified" class="button outline">Requalified</button></div></section></div>
  <section class="panel"><div class="panel-head"><h2>Packaged action tests</h2>${chip(tests.allExpected?'EXPECTED DENIALS PASS':'FAIL',tests.allExpected?'pass':'fail')}</div><div class="test-grid">${[...tests.initial,...tests.postImpairment].map(t=>`<div class="test-row"><code>${esc(t.action)}</code>${chip(t.decision,t.decision==='ALLOW'?'pass':'fail')}<small>${esc(t.reason)}</small></div>`).join('')}</div><p class="micro">A denial is a successful institutional output when the requested consequence exceeds current evidence.</p></section>`;
  $('#evaluateAuthorityButton')?.addEventListener('click',()=>{const action=$('#authorityAction').value,r=evaluateAuthority(e,action),out=$('#authorityDecision');out.className=`authority-decision ${r.decision.toLowerCase()}`;out.innerHTML=`<strong>${r.decision}</strong><span>${esc(r.reason)}</span>`;});
  $$('[data-authority-phase]').forEach(b=>b.addEventListener('click',()=>{state.authorityPhase=b.dataset.authorityPhase;renderAuthority();}));
}
function renderRequalification(){const imp=R.impairmentRecord,q=R.requalificationRecord;const steps=[
  ['Material change detected',imp.materialChange.effect],['Proof invalidated',imp.invalidatedClaims.join(' · ')],['Authority contracted','A1_RECOMMEND_ONLY → A0_READ_ONLY'],['Fallback activated',q.rollbackTarget],['Descendant release frozen',q.newReleaseId],['New Fresh Proof signed','Proof is not inherited'],['New admission issued','Admission is not inherited'],['New authority issued','Authority is not inherited'],['Requalification complete',q.verdict]
];
  $('#view-requalification').innerHTML=`<section class="page-intro"><span class="eyebrow">Tested requalification</span><h1>The successor must itself be succeeded.</h1><p>A material environment change invalidates affected proof, contracts authority, activates the known-good fallback and opens a new cycle. Memory may transfer; proof and authority do not.</p></section>
  ${callout('Material impairment',`<strong>${esc(imp.materialChange.type)}</strong><br>${esc(imp.materialChange.from)} → ${esc(imp.materialChange.to)}<br>${esc(imp.materialChange.effect)}`,'red')}
  <section class="panel"><div class="panel-head"><div><h2>Replay the tested state transition</h2><p>Each step maps to signed records in the release.</p></div><button id="advanceRequalification" class="button gold">Advance one step</button></div><div class="requali-timeline">${steps.map((s,i)=>`<article class="${i<=state.requalificationStep?'active':''}"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(s[0])}</strong><small>${esc(s[1])}</small></div></article>`).join('')}</div><div class="button-row"><button id="resetRequalification" class="button outline">Reset</button><button id="completeRequalification" class="button outline">Complete replay</button></div></section>
  <div class="metric-grid compact">${Object.entries(q.tests).map(([k,v])=>metric(k.replace(/[A-Z]/g,m=>' '+m).replace(/^./,c=>c.toUpperCase()),v?'PASS':'FAIL')).join('')}</div>
  <div class="two-col"><section class="panel"><h2>Previous release</h2>${hashLine('Release',q.previousReleaseId)}${hashLine('Proof',q.previousProofSha256)}${hashLine('Authority',q.previousAuthoritySha256)}${chip('IMPAIRED · ROLLED BACK','fail')}</section><section class="panel"><h2>Requalified release</h2>${hashLine('Release',q.newReleaseId)}${hashLine('Proof',q.newProofSha256)}${hashLine('Admission',q.newAdmissionSha256)}${hashLine('Authority',q.newAuthoritySha256)}${chip(q.verdict,'pass')}</section></div>`;
  $('#advanceRequalification')?.addEventListener('click',()=>{state.requalificationStep=Math.min(steps.length-1,state.requalificationStep+1);renderRequalification();});$('#resetRequalification')?.addEventListener('click',()=>{state.requalificationStep=0;renderRequalification();});$('#completeRequalification')?.addEventListener('click',()=>{state.requalificationStep=steps.length-1;renderRequalification();});
}
function renderChronicle(){const c=R.chronicleLedger;
  $('#view-chronicle').innerHTML=`<section class="page-intro"><span class="eyebrow">Chronicle</span><h1>Append-only memory, without inherited proof or authority.</h1><p>Every consequential transition commits to the previous event hash. The ledger preserves attributable capability and failure while forcing each new release to earn its own proof, admission and Authority Envelope.</p></section>
  <section class="panel"><div class="panel-head"><div><h2>Succession ledger</h2><p>${c.events.length} linked events · head ${short(c.headHash,16)}</p></div><button id="verifyChronicle" class="button outline">Verify hash chain</button></div><div id="chronicleVerification" class="verification-result">Not yet recomputed in this browser.</div><div class="chronicle">${c.events.map(e=>`<article><span>${String(e.index).padStart(2,'0')}</span><div><strong>${esc(e.type.replaceAll('_',' '))}</strong><small>${esc(e.at)}</small>${hashLine('event hash',e.hash)}</div></article>`).join('')}</div></section>${callout('Chronicle law',c.rule,'navy')}`;
  $('#verifyChronicle')?.addEventListener('click',verifyChronicle);
}
async function verifyChronicle(){const out=$('#chronicleVerification');out.textContent='Recomputing linked SHA-256 events…';let prev='0'.repeat(64),pass=true;for(const e of R.chronicleLedger.events){const body={index:e.index,type:e.type,at:e.at,previousHash:e.previousHash,payloadSha256:e.payloadSha256};const h=await sha(body);if(e.previousHash!==prev||h!==e.hash){pass=false;break;}prev=e.hash;}if(prev!==R.chronicleLedger.headHash)pass=false;out.innerHTML=pass?chip('HASH CHAIN VALID','pass')+' Every event is linked to the preceding accepted state.':chip('HASH CHAIN INVALID','fail');}
function renderDeveloper(){const vr=R.cycleVerificationReport;
  $('#view-developer').innerHTML=`<section class="page-intro"><span class="eyebrow">Developer and operator release</span><h1>Inspect, reproduce, deploy and replace every plane.</h1><p>The complete suite contains the static institution, Python runtime, independent proof package, Cloudflare access gateway, authority gateway, machine-readable schemas, signed evidence, research papers, tests, manifests and checksums.</p></section>
  <div class="three-col"><section class="panel"><h2>Public plane</h2><p>GitHub Pages-ready interface with client eligibility gate, live Ethereum jobs, offline evidence and portable HTML.</p></section><section class="panel"><h2>Protected plane</h2><p>Separately deployable access gateway and proof-custody runtime. Protected cases and credentials remain outside the public bundle in production.</p></section><section class="panel"><h2>Authority plane</h2><p>Signed-envelope verification, action denial, append-only decision logs, impairment contraction and rollback tests.</p></section></div>
  <section class="panel"><div class="panel-head"><h2>Canonical records</h2>${chip(`${Object.keys(R).length} RECORD SETS`,'neutral')}</div><div class="download-grid">${Object.keys(R).sort().map(k=>`<button data-download-record="${k}"><span>${esc(k)}</span><small>JSON ↓</small></button>`).join('')}</div></section>
  <section class="panel"><div class="panel-head"><h2>Release verification</h2>${chip(vr.pass?'PASS':'FAIL',vr.pass?'pass':'fail')}</div><div class="check-list">${Object.entries(vr.checks).map(([k,v])=>`<div><span>${v?'✓':'×'}</span><strong>${esc(k.replace(/[A-Z]/g,m=>' '+m))}</strong>${chip(v?'PASS':'FAIL',v?'pass':'fail')}</div>`).join('')}</div></section>
  <section class="panel"><h2>Production boundary</h2><p>Static GitHub Pages access control discourages unauthorized use but cannot make already-published assets secret. Use the included edge gateway to serve the protected application only after server-side signature and current Mainnet eligibility revalidation. Production mission authority additionally requires rights-cleared data, real operational adapters, independent custody, professional review, incident response and tested rollback.</p></section>`;
}
function renderAll(){renderOverview();renderMainnet();renderConstitution();renderExecution();renderProof();renderAdmission();renderAuthority();renderRequalification();renderChronicle();renderDeveloper();setSection(location.hash.slice(1)||'overview',false);}
function init(){renderAll();bindCommon();$('#versionLabel').textContent=`v${CFG.version}`;window.addEventListener('hashchange',()=>setSection(location.hash.slice(1),false));}
document.addEventListener('DOMContentLoaded',init);
})();
