const pptxgen=require('pptxgenjs');
const {imageSizingContain,imageSizingCrop,warnIfSlideHasOverlaps,warnIfSlideElementsOutOfBounds}=require('/home/oai/skills/slides/pptxgenjs_helpers');
const path=require('path');
const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='GoalOS / MONTREAL.AI';pptx.company='GoalOS';pptx.subject='GoalOS Partner MASTERCLASS Masterpiece Edition';pptx.title='GoalOS Partner MASTERCLASS — Masterpiece Institutional Edition';pptx.lang='en-CA';pptx.theme={headFontFace:'Georgia',bodyFontFace:'Arial',lang:'en-CA'};
const C={night:'050914',navy:'07182D',navy2:'0D2948',ink:'F1F6FC',muted:'A8B8C9',gold:'E9BD62',gold2:'FFE09A',cyan:'65D6E9',blue:'64A9FF',green:'70DFA6',red:'FF7186',purple:'B79AFF',line:'29415B',paper:'F7F3EA',darkInk:'10243C'};
const A='/mnt/data/GoalOS_Partner_MASTERCLASS_MASTERPIECE_v3/assets';
const img=n=>path.join(A,n);
function bg(slide,light=false){slide.background={color:light?C.paper:C.night};if(!light){slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:7.5,fill:{color:C.navy,transparency:55},line:{transparency:100}});slide.addShape(pptx.ShapeType.arc,{x:9.5,y:-2.7,w:6.5,h:6.5,rotate:20,adjustPoint:.2,fill:{color:C.gold,transparency:100},line:{color:C.gold,transparency:78,width:1}})} }
function footer(slide,n,light=false){slide.addText('GOALOS PARTNER MASTERCLASS · MASTERPIECE EDITION',{x:.48,y:7.12,w:5.2,h:.16,fontFace:'Arial',fontSize:7,bold:true,color:light?'8C7B5A':'71879D',charSpacing:.7,margin:0});slide.addText(String(n).padStart(2,'0'),{x:12.2,y:7.08,w:.6,h:.2,fontSize:8,bold:true,color:light?'8C7B5A':'71879D',align:'right',margin:0});}
function kicker(slide,text,light=false){slide.addText(text.toUpperCase(),{x:.6,y:.38,w:7.5,h:.25,fontFace:'Arial',fontSize:9,bold:true,color:light?'A87620':C.gold,charSpacing:1.25,margin:0});}
function title(slide,t,sub,n,light=false){kicker(slide,sub||'GoalOS Partner MASTERCLASS',light);slide.addText(t,{x:.58,y:.78,w:12.1,h:1.04,fontFace:'Georgia',fontSize:31,bold:true,color:light?C.darkInk:C.ink,breakLine:false,margin:0,fit:'shrink'});footer(slide,n,light)}
function addNotes(slide,lines){if(slide.addNotes)slide.addNotes(Array.isArray(lines)?lines:[lines]);}
function box(slide,x,y,w,h,opts={}){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:.08,fill:{color:opts.fill||C.navy2,transparency:opts.transparency??18},line:{color:opts.line||C.line,transparency:opts.lineTransparency??20,width:opts.width||1},radius:opts.radius||.08});}
function pill(slide,text,x,y,w,color=C.gold){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h:.28,rectRadius:.12,fill:{color,transparency:82},line:{color,transparency:45,width:.8}});slide.addText(text,{x:x+.06,y:y+.055,w:w-.12,h:.12,fontSize:7.5,bold:true,color,align:'center',margin:0,charSpacing:.5,fit:'shrink'});}
function bodyText(slide,text,x,y,w,h,opts={}){slide.addText(text,{x,y,w,h,fontFace:opts.serif?'Georgia':'Arial',fontSize:opts.size||16,bold:opts.bold||false,color:opts.color||C.muted,margin:opts.margin??0,breakLine:false,fit:'shrink',valign:opts.valign||'top',bullet:opts.bullet,lineSpacingMultiple:opts.lineSpacingMultiple||1.0});}
function metric(slide,x,y,w,label,value,detail,color=C.gold){box(slide,x,y,w,1.15,{fill:C.navy2,transparency:10,line:color,lineTransparency:45});bodyText(slide,label.toUpperCase(),x+.15,y+.13,w-.3,.16,{size:7.5,bold:true,color});bodyText(slide,value,x+.15,y+.37,w-.3,.38,{size:23,bold:true,serif:true,color:C.ink});bodyText(slide,detail,x+.15,y+.8,w-.3,.24,{size:8,color:C.muted});}
function image(slide,file,x,y,w,h,crop=false){const p=img(file);slide.addImage({path:p,...(crop?imageSizingCrop(p,x,y,w,h):imageSizingContain(p,x,y,w,h))});}
function check(slide,label){try{warnIfSlideHasOverlaps(slide,pptx);warnIfSlideElementsOutOfBounds(slide,pptx);}catch(e){console.error('QA',label,e.message)}}
let N=0;function newSlide(light=false){const s=pptx.addSlide();N++;bg(s,light);return s}
// 1
{const s=newSlide();pill(s,'GRAND × APEX × SOVEREIGN × PRODUCTION',.65,.58,4.15,C.gold);s.addText('The institution for',{x:.6,y:1.25,w:7.9,h:.65,fontFace:'Georgia',fontSize:43,bold:true,color:C.ink,margin:0});s.addText('proof-carrying\nintelligence.',{x:.6,y:1.85,w:7.9,h:1.55,fontFace:'Georgia',fontSize:55,bold:true,color:C.gold2,margin:0,breakLine:false,fit:'shrink'});bodyText(s,'GoalOS Partner MASTERCLASS — Masterpiece Institutional Edition',.63,3.7,7.5,.42,{size:18,bold:true,color:C.cyan});bodyText(s,'Executive theatre · Mission laboratory · Evidence Docket · AI / AGI Node Council · Governed RSI · Partner Deal Architect',.63,4.22,7.3,.76,{size:15,color:C.muted});image(s,'apex_atrium.png',8.15,.7,4.62,5.7,true);box(s,.65,5.6,7.2,.82,{fill:C.navy2,transparency:8,line:C.gold,lineTransparency:30});bodyText(s,'A model may answer. An agent may act. An institution must prove.',.87,5.86,6.75,.24,{size:16,serif:true,bold:true,color:C.ink});bodyText(s,'GOS-PM-MASTERPIECE-2026.07-v3.0 · July 2026',.65,6.75,5,.2,{size:8,color:'71879D'});footer(s,N);addNotes(s,'Open with the category: AI output is abundant; institutional authority is scarce. This system is the operating layer between autonomous work and justified institutional authority.');check(s,'1')}
//2
{const s=newSlide();title(s,'AI creates output. GoalOS creates proof.','01 · The category',N);bodyText(s,'The strategic scarcity has shifted.',.6,1.85,5.6,.35,{size:18,serif:true,color:C.gold2});const rows=[['Report-only AI','GoalOS'],['Output is the endpoint','A Governed Decision State is the endpoint'],['Evidence is reconstructed later','Claims, evidence, risk and rollback travel together'],['Contradictions compress into prose','Contradictions and Proof Debt remain explicit'],['Memory accumulates by default','Chronicle decides what may influence future work'],['“Improvement” means better output','Mission 2 must demonstrate equal-constraint transfer']];rows.forEach((r,i)=>{const y=2.45+i*.58;box(s,.65,y,12.05,.46,{fill:i===0?C.navy2:'0A1B30',transparency:i===0?0:8,line:C.line,lineTransparency:35});bodyText(s,r[0],.83,y+.12,5.35,.18,{size:i===0?10:11,bold:i===0,color:i===0?C.gold:C.muted});bodyText(s,r[1],6.45,y+.12,5.95,.18,{size:i===0?10:11,bold:i===0,color:i===0?C.cyan:C.ink});});addNotes(s,'Do not begin with tokens or planetary scale. Begin with the enterprise proof gap.');check(s,'2')}
//3
{const s=newSlide();title(s,'The partner receives a Governed Decision State.','02 · The flagship deliverable',N);bodyText(s,'Not merely a report: an inspectable, challengeable, operational state.',.62,1.75,8.3,.35,{size:17,serif:true,color:C.gold2});const objects=[['Mission Contract','objective, scope, risk, proof level, validators, rollback'],['Claims matrix','supported, conditional, disputed, blocked or unresolved'],['Evidence Docket','provenance, ProofBundles, contradiction, cost, risk, replay'],['Verifier report','identity, independence, verdict, challenge and limitation'],['Action Graph','owners, dependencies, approvals, proof and stop conditions'],['Chronicle decision','admit, scope, repair, reject, quarantine or retire'],['Capability passport','method, evidence, tests, freshness, rollback and lineage']];objects.forEach((o,i)=>{const col=i%2,row=Math.floor(i/2),x=.7+col*6.05,y=2.25+row*.98;box(s,x,y,5.72,.78,{fill:'0B213C',transparency:5,line:i===6?C.green:C.line,lineTransparency:30});bodyText(s,o[0],x+.18,y+.14,1.65,.22,{size:11,bold:true,color:i===6?C.green:C.gold});bodyText(s,o[1],x+1.92,y+.14,3.55,.36,{size:9.5,color:C.muted});});addNotes(s,'This slide is the bridge from architecture to product. The deliverable is a decision state that travels with its proof and limitations.');check(s,'3')}
//4
{const s=newSlide();title(s,'Four front doors. One institution.','03 · Masterpiece architecture',N);const cards=[['APEX Boardroom','90 sec · 12 min · 45 min','Executive category, urgency and partner ask','apex_atrium.png',C.gold],['Grand Institution','90 min · 3 hours · 1 day','Complete labs, curriculum, diligence and deal design','grand_atrium.png',C.blue],['Sovereign Evidence','REAL-001 · Mission 2 · replay','Scoped first-party evidence and governed RSI','sovereign_home.png',C.green],['Production Showcase','Live mission · Docket · pilot','Concise commercial demonstration and receipt','showcase_overview.png',C.purple]];cards.forEach((c,i)=>{const x=.55+i*3.18;box(s,x,1.8,2.95,4.75,{fill:C.navy2,transparency:5,line:c[4],lineTransparency:38});image(s,c[3],x+.12,1.94,2.71,1.58,true);bodyText(s,`0${i+1}`,x+.17,3.68,.5,.34,{size:22,serif:true,bold:true,color:c[4]});bodyText(s,c[0],x+.17,4.12,2.55,.38,{size:16,serif:true,bold:true,color:C.ink});pill(s,c[1],x+.17,4.62,2.35,c[4]);bodyText(s,c[2],x+.17,5.16,2.55,.72,{size:10,color:C.muted});});addNotes(s,'The synthesis does not flatten the source editions. It gives each edition the role it performs best.');check(s,'4')}
//5
{const s=newSlide();title(s,'Six velocities—from ninety seconds to one day.','04 · Dynamic delivery',N);const modes=[['90 seconds','Category + curiosity','APEX Proof Theatre'],['12 minutes','One candidate Proof Mission','Production Showcase'],['45 minutes','Board understanding + sponsor','APEX + REAL-001'],['90 minutes','Draft Mission Contract','Grand + Sovereign'],['3 hours','Executable partner design','Fieldbook + labs'],['One day','90-day institution blueprint','Full Masterpiece system']];modes.forEach((m,i)=>{const col=i%3,row=Math.floor(i/3),x=.65+col*4.15,y=1.85+row*2.25;box(s,x,y,3.85,1.84,{fill:'0B213C',transparency:4,line:i<2?C.gold:i<4?C.blue:C.green,lineTransparency:38});bodyText(s,m[0],x+.18,y+.18,3.45,.3,{size:19,serif:true,bold:true,color:C.ink});bodyText(s,m[1],x+.18,y+.68,3.45,.28,{size:12,bold:true,color:i<2?C.gold2:i<4?C.cyan:C.green});bodyText(s,m[2],x+.18,y+1.15,3.45,.26,{size:10,color:C.muted});});addNotes(s,'Ask how much time the room has and what decision they must reach. Route accordingly.');check(s,'5')}
//6
{const s=newSlide();title(s,'The canonical proof-to-capability loop.','05 · Operating chain',N);image(s,'proof_loop.png',.65,1.55,12.0,4.55,false);box(s,.8,6.28,11.7,.47,{fill:'0C2139',transparency:0,line:C.gold,lineTransparency:35});bodyText(s,'Objective → Mission Contract → Proof Debt → AGI Jobs → ProofBundles → Evidence Docket → Validation → Chronicle → Validated Skill → Harder Mission',1.0,6.43,11.25,.16,{size:10.2,bold:true,color:C.gold2,align:'center'});addNotes(s,'Authority only appears after the next gate passes. Keep the loop visible throughout the session.');check(s,'6')}
//7
{const s=newSlide();title(s,'Authority narrows through the stack.','06 · No silent bypass',N);image(s,'authority_stack.png',.9,1.45,7.2,5.35,false);const laws=[['Intent','No ambiguous authority'],['Work','No unsupported claim hidden as prose'],['Evidence','No completion without artifacts'],['Validation','No nominal independence'],['Memory','No Chronicle entry, no future influence'],['Economy','No bond receipt, no authority transition'],['Reality','No empirical claim without external evidence']];laws.forEach((l,i)=>{const y=1.5+i*.68;box(s,8.35,y,4.25,.52,{fill:'0B213C',transparency:4,line:i>4?C.gold:C.line,lineTransparency:35});bodyText(s,l[0],8.52,y+.12,1.05,.18,{size:10,bold:true,color:i>4?C.gold:C.cyan});bodyText(s,l[1],9.55,y+.12,2.85,.18,{size:9.5,color:C.muted});});addNotes(s,'This is the constitutional structure. Lower layers cannot silently override higher gates.');check(s,'7')}
//8
{const s=newSlide();title(s,'Freeze the decision before autonomous work begins.','07 · Mission Contract',N);image(s,'ui_mission.png',6.65,1.55,6.05,4.95,true);const fields=[['Decision','What exact choice must the institution make?'],['Success / failure','What evidence would justify proceed, hold, reject or repair?'],['Scope / boundary','What may the mission touch—and what remains prohibited?'],['Proof level','Internal, external-review, controlled handoff or Chronicle-ready?'],['Review authority','Who can approve, challenge, block or require repair?'],['Rollback','What state is restored if assumptions fail?']];fields.forEach((f,i)=>{const y=1.7+i*.78;bodyText(s,`${String(i+1).padStart(2,'0')}  ${f[0]}`,.72,y,2.0,.24,{size:11,bold:true,color:C.gold});bodyText(s,f[1],2.65,y,3.55,.36,{size:10.2,color:C.muted});});addNotes(s,'A Mission Contract is a decision constitution. It prevents vague authority from appearing after the work is done.');check(s,'8')}
//9
{const s=newSlide();title(s,'Uncertainty becomes Proof Debt—not confidence.','08 · Proof Factory',N);const debt=[['PD-01','Security attestation','blocked until independent evidence'],['PD-02','Data-flow map','conditional; private appendix required'],['PD-03','Commercial references','review; primary references missing'],['PD-04','Rollback rehearsal','blocked; executable evidence absent']];debt.forEach((d,i)=>{const y=1.8+i*.83;box(s,.65,y,5.5,.64,{fill:'0B213C',transparency:5,line:i===0||i===3?C.red:C.gold,lineTransparency:35});bodyText(s,d[0],.85,y+.16,.65,.18,{size:9,bold:true,color:i===0||i===3?C.red:C.gold});bodyText(s,d[1],1.55,y+.14,1.7,.2,{size:11,bold:true,color:C.ink});bodyText(s,d[2],3.2,y+.14,2.65,.3,{size:9,color:C.muted});});s.addShape(pptx.ShapeType.chevron,{x:6.4,y:2.85,w:.7,h:.8,fill:{color:C.gold,transparency:15},line:{transparency:100}});box(s,7.35,1.6,5.35,4.5,{fill:'091B30',transparency:0,line:C.blue,lineTransparency:35});bodyText(s,'MISSION-SPECIFIC AGI JOB',7.65,1.92,4.75,.2,{size:9,bold:true,color:C.cyan,charSpacing:.8});const job=['source claim','why-needed rationale','worker / tool boundary','independent validator','deliverables','acceptance tests','blocked claims','ProofBundle return path','failure branch','rollback condition'];job.forEach((j,i)=>{bodyText(s,`• ${j}`,7.72,2.35+i*.32,4.5,.2,{size:10,color:i>6?C.gold2:C.muted});});addNotes(s,'The job factory begins empty. Jobs appear only after the mission exposes actual Proof Debt.');check(s,'9')}
//10
{const s=newSlide();title(s,'The Evidence Docket is the institutional proof room.','09 · Evidence operations',N);const parts=[['Claims matrix','Every consequential claim has a state'],['Source provenance','Primary, secondary, derived and private sources separated'],['ProofBundles','Artifacts, tests, manifests, hashes and replay'],['Contradictions','Conflicts remain visible and decision-relevant'],['Cost + risk ledgers','The proof burden and downside remain explicit'],['Verifier report','Identity, independence, verdict and limitations'],['Claim boundary','Exactly what the Docket does—and does not—support'],['Action Graph','Owners, approvals, dependencies, stops and rollback']];parts.forEach((p,i)=>{const col=i%4,row=Math.floor(i/4),x=.55+col*3.17,y=1.8+row*2.15;box(s,x,y,2.9,1.72,{fill:'0B213C',transparency:5,line:i===0?C.gold:i===5?C.green:C.line,lineTransparency:35});bodyText(s,`0${i+1}`,x+.15,y+.15,.4,.28,{size:18,serif:true,bold:true,color:i===5?C.green:C.gold});bodyText(s,p[0],x+.15,y+.53,2.6,.26,{size:13,bold:true,color:C.ink});bodyText(s,p[1],x+.15,y+.93,2.55,.5,{size:9.5,color:C.muted});});addNotes(s,'A proof page is not a marketing page. The reviewer must be able to reconstruct what happened and what remains blocked.');check(s,'10')}
//11
{const s=newSlide();title(s,'Three evidence lanes. Three authority levels.','10 · Evidence taxonomy',N);const lanes=[['FIRST-PARTY REAL','GOALOS-REAL-001','Scoped repository-specific transfer case with matching first-party replay.','+5.71 reported score lift','Independent replays + maintainer review remain open',C.green],['DETERMINISTIC REFERENCE','COMP-001 / Proof Run','Object model, local implementation, Make gates, Docket and Merkle mechanics.','PASS reference gates','Not external empirical superiority',C.blue],['ILLUSTRATIVE PARTNER','Strategic Partnership Diligence','Shows the intended claims matrix, closing conditions and Governed Decision State.','10 illustrative claim states','Not a real partner result',C.purple]];lanes.forEach((l,i)=>{const x=.6+i*4.25;box(s,x,1.8,3.95,4.65,{fill:'0A2038',transparency:2,line:l[5],lineTransparency:30});pill(s,l[0],x+.18,2.05,2.55,l[5]);bodyText(s,l[1],x+.18,2.55,3.55,.48,{size:20,serif:true,bold:true,color:C.ink});bodyText(s,l[2],x+.18,3.18,3.55,.78,{size:10.5,color:C.muted});bodyText(s,l[3],x+.18,4.22,3.55,.36,{size:15,bold:true,color:l[5]});box(s,x+.18,4.82,3.55,.95,{fill:'0C192B',transparency:5,line:C.red,lineTransparency:45});bodyText(s,l[4],x+.35,5.05,3.2,.5,{size:9.5,color:C.muted});});addNotes(s,'Credibility increases when the presentation does not blur real, reference and illustrative evidence.');check(s,'11')}
//12
{const s=newSlide();title(s,'REAL-001: a scoped Mission 1 → Mission 2 case.','11 · First-party evidence',N);image(s,'sovereign_transfer.png',7.1,1.55,5.65,4.85,true);metric(s,.65,1.75,2.9,'Reported lift','+5.71','skill arm vs fresh/raw',C.green);metric(s,3.75,1.75,2.9,'Observation steps','−1','in the scoped transfer task',C.cyan);metric(s,.65,3.2,2.9,'Replay receipt','MATCH','first-party deterministic receipt',C.gold);metric(s,3.75,3.2,2.9,'Unsafe arm','BLOCKED','ungated transfer did not earn authority',C.red);box(s,.65,4.8,6.0,1.13,{fill:'171724',transparency:4,line:C.red,lineTransparency:35});bodyText(s,'OPEN PROOF DEBT',.86,5.0,1.6,.2,{size:9,bold:true,color:C.red});bodyText(s,'Two independent operator replays + human maintainer review of the proposed migration action.',.86,5.3,5.45,.42,{size:11,color:C.muted});bodyText(s,'Claim: repository-specific transfer mechanism—not arbitrary-domain compounding, production authority or general RSI.',.68,6.3,11.8,.36,{size:10.5,serif:true,color:C.gold2,align:'center'});addNotes(s,'Present REAL-001 precisely. The value is not only the lift; it is the explicit remaining burden and blocked ungated arm.');check(s,'12')}
//13
{const s=newSlide();title(s,'Replay is necessary. Independence is separate.','12 · Proof maturity',N);const steps=[['1','AUTHOR RUN','Candidate result and original ProofBundle'],['2','FIRST-PARTY REPLAY','Exact artifacts reproduce under the same operator'],['3','INDEPENDENT REPLAY','Separate operator reproduces from the public kit'],['4','HUMAN / DOMAIN REVIEW','A qualified reviewer accepts, rejects or requests repair'],['5','DELAYED OUTCOME','The result survives time, transfer and real operational consequences']];steps.forEach((st,i)=>{const x=.55+i*2.54;box(s,x,2.15,2.25,3.25,{fill:'0B213C',transparency:4,line:i<2?C.gold:i===2?C.cyan:i===3?C.green:C.purple,lineTransparency:35});bodyText(s,st[0],x+.16,2.35,.45,.42,{size:25,serif:true,bold:true,color:i<2?C.gold:i===2?C.cyan:i===3?C.green:C.purple});bodyText(s,st[1],x+.16,3.05,1.95,.45,{size:11,bold:true,color:C.ink});bodyText(s,st[2],x+.16,3.73,1.95,.9,{size:9.5,color:C.muted});if(i<4)s.addShape(pptx.ShapeType.chevron,{x:x+2.25,y:3.25,w:.3,h:.55,fill:{color:C.gold,transparency:30},line:{transparency:100}})});box(s,1.4,5.75,10.55,.58,{fill:C.navy2,transparency:0,line:C.red,lineTransparency:45});bodyText(s,'A matching first-party replay upgrades reproducibility—not reviewer independence.',1.7,5.95,9.95,.18,{size:13,serif:true,bold:true,color:C.gold2,align:'center'});addNotes(s,'Use this slide to show why GoalOS does not inflate evidence maturity.');check(s,'13')}
//14
{const s=newSlide();title(s,'Validation must be independent—not merely numerous.','13 · AGI Node Council',N);image(s,'ui_council.png',6.7,1.5,6.0,5.25,true);const dims=[['Operator','Who controls the reviewer?'],['Wallet','Is economic control shared?'],['Model family','Are reviewers epistemically diverse?'],['Cloud / hardware','Is infrastructure correlated?'],['Jurisdiction','Are incentives and constraints independent?'],['Capability','Does the council cover the actual proof class?']];dims.forEach((d,i)=>{const y=1.72+i*.72;bodyText(s,d[0],.72,y,1.35,.2,{size:11,bold:true,color:i<3?C.gold:C.cyan});bodyText(s,d[1],2.18,y,3.9,.25,{size:10,color:C.muted});});box(s,.7,6.03,5.55,.55,{fill:'0B2038',transparency:0,line:C.green,lineTransparency:40});bodyText(s,'Commit → reveal → challenge → resolve → record',.95,6.22,5.05,.17,{size:12,bold:true,color:C.green,align:'center'});addNotes(s,'A raw count of reviewers is not independence. Show the dimensions that matter.');check(s,'14')}
//15
{const s=newSlide();title(s,'Chronicle is the memory firewall.','14 · Governed memory',N);const decisions=[['ADMIT','within exact proven scope',C.green],['ADMIT WITH SCOPE','only for named conditions',C.cyan],['REPAIR','additional proof required',C.gold],['REJECT','evidence insufficient',C.red],['QUARANTINE','risk or contradiction unresolved',C.purple],['SUPERSEDE / REVOKE / RETIRE','authority can shrink or disappear',C.muted]];decisions.forEach((d,i)=>{const col=i%3,row=Math.floor(i/3),x=.65+col*4.15,y=1.85+row*2.0;box(s,x,y,3.85,1.55,{fill:'0B213C',transparency:5,line:d[2],lineTransparency:35});bodyText(s,d[0],x+.18,y+.22,3.45,.25,{size:13,bold:true,color:d[2]});bodyText(s,d[1],x+.18,y+.73,3.45,.35,{size:11,serif:true,color:C.ink});});box(s,1.2,6.02,10.9,.55,{fill:'111B2B',transparency:0,line:C.gold,lineTransparency:42});bodyText(s,'No Chronicle entry, no future-mission influence.',1.45,6.2,10.4,.18,{size:14,serif:true,bold:true,color:C.gold2,align:'center'});addNotes(s,'The biggest memory risk is persuasive but unsupported output becoming a prior. Chronicle prevents that.');check(s,'15')}
//16
{const s=newSlide();title(s,'The durable asset is a validated capability—not a prompt.','15 · Validated Skill Graph',N);image(s,'skill_graph.png',.65,1.45,7.0,5.45,false);const fields=['stable identity + immutable version','scope + allowed and excluded uses','method + evidence + tests','validator history + replay path','freshness + delayed outcomes','risk posture + rollback target','revocation + supersession','mission lineage + measured reuse'];fields.forEach((f,i)=>{const y=1.65+i*.58;box(s,8.0,y,4.65,.42,{fill:'0B213C',transparency:5,line:i>5?C.red:C.line,lineTransparency:40});bodyText(s,`0${i+1}`,8.16,y+.1,.35,.16,{size:8,bold:true,color:i>5?C.red:C.gold});bodyText(s,f,8.6,y+.1,3.75,.16,{size:10,color:C.muted});});addNotes(s,'The moat is the accumulated evidence, scope, replay, validator history, delayed outcomes, policy and lineage—not raw prompt text.');check(s,'16')}
//17
{const s=newSlide();title(s,'Protect intelligence. Publish minimum proof.','16 · Public-private boundary',N);image(s,'aep_boundary.png',.95,1.45,7.4,5.3,false);box(s,8.65,1.75,3.9,1.75,{fill:'0B213C',transparency:4,line:C.cyan,lineTransparency:35});bodyText(s,'PUBLIC PROOF',8.9,2.0,3.4,.24,{size:13,bold:true,color:C.cyan});bodyText(s,'hashes · Merkle roots · attestations · selection certificates · receipts · revocations · public-safe Docket',8.9,2.5,3.35,.72,{size:10,color:C.muted});box(s,8.65,3.85,3.9,1.75,{fill:'16152B',transparency:3,line:C.purple,lineTransparency:35});bodyText(s,'PRIVATE INTELLIGENCE',8.9,4.1,3.4,.24,{size:13,bold:true,color:C.purple});bodyText(s,'prompts · long traces · customer data · private tools · evaluation workpapers · proprietary methods · privileged rationale',8.9,4.6,3.35,.72,{size:10,color:C.muted});addNotes(s,'Do not put private intelligence on-chain. Put the minimum proof of intelligence on-chain.');check(s,'17')}
//18
{const s=newSlide();title(s,'$AGIALPHA is the bonded-authority rail.','17 · Economic accountability',N);bodyText(s,'GoalOS creates proof. $AGIALPHA makes accepted proof economically consequential.',.65,1.7,11.8,.38,{size:18,serif:true,color:C.gold2,align:'center'});const rows=[['Work begins','Mission capacity + Worker Proof Bond'],['Work becomes paid','Accepted ProofBundle + Validator Accuracy Bonds'],['Claim becomes trusted','Claim Authority Bond + Chronicle + challenge finality'],['Claim is challenged','Challenger Bond + evidence-bearing resolution'],['Skill becomes reusable','Capability Reuse Bond + delayed outcome + scope/freshness'],['Node validates','Operational reserve + reputation + independence'],['GoalOS upgrades','Proposal + evaluator + canary + rollback reserves']];rows.forEach((r,i)=>{const y=2.35+i*.55;box(s,.9,y,11.5,.42,{fill:i%2?'0A1C31':'0C223B',transparency:0,line:C.line,lineTransparency:65});bodyText(s,r[0],1.13,y+.1,3.15,.17,{size:10.5,bold:true,color:C.cyan});bodyText(s,r[1],4.45,y+.1,7.65,.17,{size:10.5,color:C.muted});});bodyText(s,'No passive-yield, dividend, revenue-share or guaranteed-value thesis is required for the partner proposition.',1.05,6.45,11.2,.3,{size:11,serif:true,color:C.gold2,align:'center'});addNotes(s,'Lead with economic accountability, not token speculation. Ordinary customers may buy fiat-denominated proof services while professional participants provide bonded security.');check(s,'18')}
//19
{const s=newSlide();title(s,'Recursive improvement must be earned.','18 · Governed RSI',N);image(s,'rsi_kernel.png',.65,1.45,7.3,5.25,false);const laws=[['Exploration allowed','Interestingness can guide search.'],['Outcome authority mechanical','Risk, evidence, baselines, replay and validators decide.'],['Promotion requires evidence','No simulated confidence inflation.'],['Compounding requires persistence','Advantage must survive shocks and fresh tasks.'],['Autonomy requires authority','Scope, canary, monitor and rollback remain mandatory.']];laws.forEach((l,i)=>{const y=1.68+i*.88;box(s,8.25,y,4.25,.68,{fill:'0B213C',transparency:4,line:i===1?C.gold:i===3?C.green:C.line,lineTransparency:35});bodyText(s,l[0],8.45,y+.13,3.9,.2,{size:11,bold:true,color:i===1?C.gold:i===3?C.green:C.cyan});bodyText(s,l[1],8.45,y+.39,3.85,.18,{size:8.5,color:C.muted});});addNotes(s,'The system may be open-ended in what it attempts, but strictly gated in what it may promote.');check(s,'19')}
//20
{const s=newSlide();title(s,'Confidence cannot inflate without evidence contact.','19 · Evidence Contact Index',N);const levels=[['E0','SIMULATED','LLM-only reasoning or scenario generation','No promotion beyond idea/probe'],['E1','PROBED','schema, static analysis or cheap microbench','Probe status only'],['E2','EXECUTED','sandbox, benchmark, tool or environment run','Required beyond probe'],['E3','REPLAYED','independent reproduction from pins and manifests','Settlement-grade claims'],['E4','STRESS-TESTED','shocks, adversarial probes, seeds and nearby baselines','High-novelty candidates'],['E5','EXTERNALLY VALIDATED','external expert, real outcome, market or delayed evidence','Strong empirical claims']];levels.forEach((l,i)=>{const y=1.6+i*.82;const col=i<2?C.muted:i<4?C.gold:i===4?C.cyan:C.green;bodyText(s,l[0],.75,y,.55,.28,{size:18,serif:true,bold:true,color:col});box(s,1.48,y-.02,2.15,.47,{fill:'0B213C',transparency:3,line:col,lineTransparency:35});bodyText(s,l[1],1.65,y+.11,1.82,.15,{size:9.5,bold:true,color:col,align:'center'});bodyText(s,l[2],3.9,y,4.0,.32,{size:10,color:C.muted});bodyText(s,l[3],8.25,y,3.9,.32,{size:10,bold:i===5,color:i===5?C.green:C.ink});});addNotes(s,'The Evidence Contact Index prevents internal reasoning from being mistaken for executed, replayed or externally validated evidence.');check(s,'20')}
//21
{const s=newSlide();title(s,'High novelty raises—not lowers—the proof burden.','20 · Move-37 handling',N);image(s,'move37.png',.7,1.4,7.25,5.3,false);const gates=[['Recognize','record novelty distance, advantage, risk, ECI, lineage'],['Reproduce','rerun candidate and null / incumbent / neighbor baselines'],['Stress-test','policy shocks, adversarial probes, alternate seeds, side effects'],['Persistence gate','retain positive cost- and risk-adjusted advantage'],['Dossier','package evidence, validators, governance and replay instructions']];gates.forEach((g,i)=>{const y=1.65+i*.89;bodyText(s,`${i+1}`,8.25,y,.38,.3,{size:18,serif:true,bold:true,color:i===4?C.green:C.gold});bodyText(s,g[0],8.75,y,1.35,.2,{size:11,bold:true,color:C.ink});bodyText(s,g[1],10.05,y,2.45,.42,{size:9.2,color:C.muted});});bodyText(s,'A breakthrough is an audited state transition—not a compelling story.',8.28,6.15,4.25,.45,{size:12,serif:true,bold:true,color:C.gold2,align:'center'});addNotes(s,'Move-37 is where most systems overclaim. GoalOS responds with more skepticism, reproduction and stress.');check(s,'21')}
//22
{const s=newSlide();title(s,'Mission 2 is the decisive compounding test.','21 · Transfer and persistence',N);const flow=[['MISSION 1','perform work'],['CHRONICLE','admit with scope'],['VALIDATED SKILL','package evidence'],['MISSION 2','fresh adjacent task'],['DELTA','compare to baselines'],['DECISION','promote, repair or retire']];flow.forEach((f,i)=>{const x=.48+i*2.12;box(s,x,2.35,1.82,1.35,{fill:'0B213C',transparency:4,line:i===3?C.green:i===5?C.gold:C.line,lineTransparency:35});bodyText(s,f[0],x+.14,2.58,1.54,.22,{size:10,bold:true,color:i===3?C.green:i===5?C.gold:C.cyan,align:'center'});bodyText(s,f[1],x+.14,3.06,1.54,.22,{size:9,color:C.muted,align:'center'});if(i<5)s.addShape(pptx.ShapeType.chevron,{x:x+1.82,y:2.78,w:.3,h:.45,fill:{color:C.gold,transparency:25},line:{transparency:100}})});box(s,1.0,4.55,11.25,1.15,{fill:'0B2038',transparency:0,line:C.green,lineTransparency:35});bodyText(s,'Compounding claim = positive, replayable, risk-bounded, persistent Advantage Delta on fresh work under equal constraints.',1.3,4.9,10.65,.34,{size:16,serif:true,bold:true,color:C.ink,align:'center'});bodyText(s,'No Mission 2, no compounding claim.',2.7,6.15,7.9,.3,{size:15,bold:true,color:C.red,align:'center'});addNotes(s,'This is the slide that makes the Masterclass more than a product demonstration. It operationalizes recursive self-improvement.');check(s,'22')}
//23
{const s=newSlide();title(s,'The commercial sequence compounds with the proof.','22 · Partner expansion',N);const steps=[['1','Proof Mission Sprint','One bounded objective → Governed Decision State','Services wedge + primary evidence'],['2','Enterprise Proof OS','Recurring contracts, Dockets, Chronicle and audit','Annual platform + assurance'],['3','Private VSG','Customer-specific governed capability memory','Implementation + reusable asset'],['4','Managed Node Council','Independent validation without customer infrastructure','ARR + metered review'],['5','Cross-Institution Network','Portable jobs, validators, challenges and skill passports','Network effects + proof throughput']];steps.forEach((st,i)=>{const x=.48+i*2.55;box(s,x,1.7,2.3,4.65,{fill:'0B213C',transparency:4,line:[C.blue,C.gold,C.green,C.purple,C.red][i],lineTransparency:35});bodyText(s,st[0],x+.16,1.94,.38,.34,{size:22,serif:true,bold:true,color:[C.blue,C.gold,C.green,C.purple,C.red][i]});bodyText(s,st[1],x+.16,2.48,1.98,.72,{size:14,serif:true,bold:true,color:C.ink});bodyText(s,st[2],x+.16,3.52,1.98,1.05,{size:9.5,color:C.muted});box(s,x+.14,5.03,2.02,.83,{fill:'08192C',transparency:0,line:C.line,lineTransparency:55});bodyText(s,st[3],x+.29,5.25,1.72,.36,{size:8.8,bold:true,color:C.gold2,align:'center'});});addNotes(s,'Sell proof first. Let repeated demand create the Proof OS. Let validated capability become the durable asset.');check(s,'23')}
//24
{const s=newSlide();title(s,'Where partners can use GoalOS now.','23 · Immediate applications',N);const uses=[['Strategic partnership diligence','technical fit · commercial logic · closing conditions'],['Enterprise AI procurement','common claims matrix · security · cost · replay'],['AI product launch readiness','claims · evals · policy · rollback · release authority'],['M&A / technology diligence','technical · data · IP · security · operations'],['Defensive cybersecurity','repo-owned scope · evidence · human review · safe remediation'],['R&D portfolio governance','proof-bearing hypotheses · capability reuse · retirement']];uses.forEach((u,i)=>{const col=i%3,row=Math.floor(i/3),x=.65+col*4.12,y=1.75+row*2.25;box(s,x,y,3.82,1.82,{fill:'0B213C',transparency:4,line:i===0?C.gold:i===4?C.red:C.line,lineTransparency:35});bodyText(s,`0${i+1}`,x+.16,y+.2,.45,.3,{size:18,serif:true,bold:true,color:i===0?C.gold:i===4?C.red:C.cyan});bodyText(s,u[0],x+.75,y+.17,2.8,.55,{size:14,serif:true,bold:true,color:C.ink});bodyText(s,u[1],x+.16,y+1.03,3.45,.42,{size:9.5,color:C.muted});});addNotes(s,'Choose the first mission where proof quality and decision traceability already matter.');check(s,'24')}
//25
{const s=newSlide();title(s,'A 15-business-day Proof Mission Sprint.','24 · Recommended first engagement',N);const phases=[['DAYS 1–2','Freeze the mission','decision · scope · proof level · validators · blocked claims · rollback'],['DAYS 3–8','Produce proof','custom AGI Jobs · sources · ProofBundles · contradictions · cost · risk'],['DAYS 9–12','Validate and replay','independent review · repair loop · challenge · public/private packaging'],['DAYS 13–15','Decide and package','Governed Decision State · Action Graph · Chronicle · Mission 2 protocol']];phases.forEach((p,i)=>{const x=.65+i*3.1;box(s,x,1.95,2.82,3.55,{fill:'0B213C',transparency:4,line:[C.blue,C.gold,C.purple,C.green][i],lineTransparency:35});pill(s,p[0],x+.17,2.18,1.5,[C.blue,C.gold,C.purple,C.green][i]);bodyText(s,p[1],x+.17,2.82,2.48,.58,{size:17,serif:true,bold:true,color:C.ink});bodyText(s,p[2],x+.17,3.72,2.45,1.15,{size:10,color:C.muted});});box(s,1.35,5.95,10.6,.52,{fill:C.navy2,transparency:0,line:C.gold,lineTransparency:35});bodyText(s,'One sponsor · one decision · one independent reviewer · one evidence package · one rollback · one fresh Mission 2',1.62,6.13,10.05,.17,{size:11,bold:true,color:C.gold2,align:'center'});addNotes(s,'The first engagement is deliberately bounded. It earns the right to discuss the larger institution.');check(s,'25')}
//26
{const s=newSlide();title(s,'GoalOS optimizes decision value—not report length.','25 · Value equation',N);bodyText(s,'Mission Value =',.72,1.9,2.2,.38,{size:22,serif:true,bold:true,color:C.gold2});box(s,2.8,1.62,8.75,1.15,{fill:'0B213C',transparency:2,line:C.cyan,lineTransparency:35});bodyText(s,'Decision Impact × Proof Integrity × Actionability × Reuse',3.15,1.96,8.05,.3,{size:20,serif:true,bold:true,color:C.ink,align:'center'});bodyText(s,'÷',11.75,1.86,.4,.42,{size:28,serif:true,bold:true,color:C.gold});box(s,2.8,3.08,8.75,1.15,{fill:'11172A',transparency:2,line:C.red,lineTransparency:35});bodyText(s,'Cost + Risk + Latency + Proof Debt',3.15,3.42,8.05,.3,{size:20,serif:true,bold:true,color:C.ink,align:'center'});const vals=[['Decision readiness','Can the reviewer act without reading every raw trace?'],['Proof Debt reduction','Are unsupported assumptions visible and shrinking?'],['Reuse value','Does admitted capability improve fresh related work?'],['Safety / rollback','Are unsafe claims blocked and releases reversible?']];vals.forEach((v,i)=>{const x=.75+i*3.1;box(s,x,5.0,2.82,1.0,{fill:'0B213C',transparency:4,line:C.line,lineTransparency:45});bodyText(s,v[0],x+.15,5.18,2.5,.2,{size:10.5,bold:true,color:i===2?C.green:C.cyan});bodyText(s,v[1],x+.15,5.52,2.48,.28,{size:8.5,color:C.muted});});addNotes(s,'The highest-value output is the shortest defensible path from uncertainty to justified action.');check(s,'26')}
//27
{const s=newSlide();title(s,'Serious participation without commercial overreach.','26 · Enterprise participation framework',N);const lanes=[['Authority','The representative confirms professional capacity and authority to bind the organization.'],['Exclusive responsibility','The Participant remains responsible for its objective, data, people, systems, taxes, approvals and downstream use.'],['Risk + non-recourse','The Participant independently evaluates technical, AI, network and digital-asset risks.'],['Hold harmless + non-joinder','Hold harmless for Participant-caused matters; keep user-to-user matters between relevant Participants.'],['Evidence receipt','Version, hashes, organization, representative, language election and acknowledgements travel with the mission.'],['Montréal process','Permitted professional disputes follow notice, preservation, conference and the accepted Montréal process.']];lanes.forEach((l,i)=>{const col=i%2,row=Math.floor(i/2),x=.65+col*6.1,y=1.65+row*1.55;box(s,x,y,5.78,1.25,{fill:'0B213C',transparency:4,line:i===3?C.green:C.line,lineTransparency:35});bodyText(s,l[0],x+.18,y+.17,1.75,.22,{size:11,bold:true,color:i===3?C.green:C.gold});bodyText(s,l[1],x+1.92,y+.16,3.55,.65,{size:9.5,color:C.muted});});bodyText(s,'Partner-facing language is proportionate; the exact accepted v2.1 instrument remains available in French and English.',1.0,6.42,11.3,.25,{size:10.5,serif:true,color:C.gold2,align:'center'});addNotes(s,'Do not lead with legal language. Use it as a serious participation record once the partner chooses to operate the system.');check(s,'27')}
//28
{const s=newSlide();title(s,'Claim discipline is a feature—not a concession.','27 · Evidence maturity',N);const status=[['Specified','Doctrine, object model, Mission OS, AEP-001, Chronicle, VSG'],['Implemented','Interactive partner institutions and browser-local operating surfaces'],['Reference-ready','AGI Node runtime, contracts, deployment packs and schemas'],['First-party scoped','REAL-001 transfer case and matching first-party replay receipt'],['Pending','Independent replay, reviewed live deployment and delayed outcomes'],['Unproven','General RSI, arbitrary-domain compounding, production certification, achieved AGI / ASI']];status.forEach((st,i)=>{const y=1.6+i*.82;bodyText(s,st[0],.78,y,1.6,.25,{size:11,bold:true,color:i<3?C.green:i===3?C.gold:i===4?C.cyan:C.red});bodyText(s,st[1],2.5,y,9.7,.35,{size:11,color:C.muted});s.addShape(pptx.ShapeType.line,{x:.78,y:y+.47,w:11.4,h:0,line:{color:C.line,transparency:35,width:.8}})});addNotes(s,'Senior partners will notice whether the evidence status is precise. Precision improves credibility and diligence velocity.');check(s,'28')}
//29
{const s=newSlide();title(s,'A diligence path that makes partnership easier.','28 · Review architecture',N);const gates=[['01','Category fit','Is the proof gap material to the partner?'],['02','Mission fit','Is there one consequential, reversible decision?'],['03','Evidence access','Can primary evidence and private appendices be made available?'],['04','Reviewer independence','Can a qualified independent reviewer be named?'],['05','Operational boundary','Are data, tool, action, wallet and authority limits explicit?'],['06','Commercial path','Does repeated demand justify Proof OS, VSG or managed validation?'],['07','Mission 2','What fresh task would falsify the compounding hypothesis?'],['08','Decision gate','Proceed, repair, hold or reject—with a complete record.']];gates.forEach((g,i)=>{const col=i%4,row=Math.floor(i/4),x=.55+col*3.17,y=1.65+row*2.25;box(s,x,y,2.9,1.78,{fill:'0B213C',transparency:4,line:i===7?C.green:C.line,lineTransparency:35});bodyText(s,g[0],x+.15,y+.15,.45,.28,{size:17,serif:true,bold:true,color:i===7?C.green:C.gold});bodyText(s,g[1],x+.15,y+.58,2.55,.25,{size:12,bold:true,color:C.ink});bodyText(s,g[2],x+.15,y+.96,2.55,.52,{size:9,color:C.muted});});addNotes(s,'Diligence is part of the product. The system should make it easier to identify what remains to be proven.');check(s,'29')}
//30
{const s=newSlide();title(s,'The Masterclass is itself a proof-producing institution.','29 · Operating map',N);image(s,'ui_command.png',.6,1.5,5.95,4.95,true);image(s,'ui_deal.png',6.8,1.5,5.95,4.95,true);pill(s,'SESSION COMPOSER',1.0,6.18,2.0,C.cyan);pill(s,'PARTNER DEAL ARCHITECT',9.05,6.18,2.55,C.gold);bodyText(s,'Route the right room.',3.15,6.25,2.6,.15,{size:10,bold:true,color:C.muted});bodyText(s,'Convert evidence into one mission.',7.0,6.25,2.0,.15,{size:10,bold:true,color:C.muted,align:'right'});addNotes(s,'The launcher is not just a download center. It adapts the session and produces a run of show, RSI dossier and partner memorandum.');check(s,'30')}
//31
{const s=newSlide();title(s,'Give GoalOS one consequential but reversible objective.','30 · The partner ask',N);bodyText(s,'Let the evidence determine what authority the result earns.',.65,1.68,11.9,.46,{size:24,serif:true,bold:true,color:C.gold2,align:'center'});const asks=[['ONE OBJECTIVE','Something the partner already needs to decide.'],['ONE SPONSOR','Authority to define success and review the result.'],['ONE REVIEWER','Independent, qualified and evidence-accessible.'],['ONE WINDOW','Reversible, measurable and claim-bounded.'],['ONE MISSION 2','A fresh test of whether admitted capability compounds.']];asks.forEach((a,i)=>{const x=.45+i*2.57;box(s,x,2.7,2.3,2.3,{fill:'0B213C',transparency:4,line:i===4?C.green:C.line,lineTransparency:35});bodyText(s,`0${i+1}`,x+.16,2.92,.45,.32,{size:20,serif:true,bold:true,color:i===4?C.green:C.gold});bodyText(s,a[0],x+.16,3.48,1.98,.3,{size:11,bold:true,color:C.ink});bodyText(s,a[1],x+.16,4.08,1.98,.55,{size:9.2,color:C.muted});});box(s,1.1,5.7,11.05,.58,{fill:'0C2139',transparency:0,line:C.gold,lineTransparency:30});bodyText(s,'Do not ask the room to believe the long-range thesis. Ask it to select the first mission that can produce the evidence.',1.4,5.9,10.45,.2,{size:13,serif:true,bold:true,color:C.ink,align:'center'});addNotes(s,'Close on a real mission, not a vague partnership.');check(s,'31')}
//32
{const s=newSlide();pill(s,'FINAL OPERATING LAW',.65,.65,1.8,C.gold);s.addText('AI creates output.\nGoalOS creates proof.',{x:.65,y:1.38,w:8.1,h:1.45,fontFace:'Georgia',fontSize:46,bold:true,color:C.ink,margin:0,fit:'shrink'});const laws=['AGI Nodes make validation global.','Chronicle decides what earns memory.','The Validated Skill Graph preserves capability.','Merkle roots preserve admitted state.','$AGIALPHA makes authority accountable.','Constitutional proof governs improvement.','Independent evidence determines reality.'];laws.forEach((l,i)=>bodyText(s,l,.75,3.25+i*.39,7.25,.2,{size:13,color:i===6?C.green:C.muted,bold:i===6}));image(s,'grand_atrium.png',8.2,.8,4.55,5.9,true);box(s,8.45,6.08,4.05,.52,{fill:C.navy2,transparency:0,line:C.gold,lineTransparency:35});bodyText(s,'No proof, no evolution. No rollback, no release.',8.67,6.25,3.62,.18,{size:10.5,bold:true,color:C.gold2,align:'center'});footer(s,N);addNotes(s,'End by returning to the category and immediately ask: What is the first objective we should freeze into a Mission Contract?');check(s,'32')}

pptx.writeFile({fileName:'/mnt/data/GoalOS_Partner_MASTERCLASS_MASTERPIECE_v3/presentation/GoalOS_Partner_MASTERCLASS_MASTERPIECE_Executive_Deck.pptx'});
