(() => {
'use strict';

const CFG = window.GOALOS_CONFIG || {};
const $ = (s,r=document) => r.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number(v)||0));
const nowISO=()=>new Date().toISOString();
const storageKey='goalos_uvsi3_alpha_foundry_v8';
const missionPresets={
  building_operations:{name:'Portfolio Building Operations',description:'Hidden equipment faults, sequential diagnostics, delayed consequences and safety-critical escalation.',features:{partial_observability:.90,delayed_rewards:.75,historical_data:.75,simulator_fidelity:.86,feedback_speed:.85,safety_criticality:.95,multiagent_need:.70,formal_rules:.55,transfer_difficulty:.72}},
  invoice_integrity:{name:'Invoice Integrity',description:'Evidence acquisition and pay/hold/escalate decisions under strong rules and abundant historical records.',features:{partial_observability:.80,delayed_rewards:.45,historical_data:.95,simulator_fidelity:.92,feedback_speed:.95,safety_criticality:.78,multiagent_need:.55,formal_rules:.90,transfer_difficulty:.45}},
  grid_resilience:{name:'Grid Storage Resilience',description:'Battery dispatch planning with delayed storm risk, changing prices and a requirement to preserve operational reserve.',features:{partial_observability:.55,delayed_rewards:.95,historical_data:.72,simulator_fidelity:.94,feedback_speed:.96,safety_criticality:.88,multiagent_need:.35,formal_rules:.48,transfer_difficulty:.68}}
};
const algorithms={
  incumbent:{name:'Incumbent Workflow',family:'Reference',complexity:.10,training_cost:.05,inference_cost:.30,sovereignty:.70,governance:.75},
  rules:{name:'Deterministic Rules',family:'Simple architecture',complexity:.18,training_cost:.06,inference_cost:.12,sovereignty:.92,governance:.94},
  behavior_clone:{name:'Behaviour Cloning',family:'Supervised adaptation',complexity:.28,training_cost:.20,inference_cost:.15,sovereignty:.84,governance:.84},
  q_learning:{name:'Tabular Q-Learning',family:'Model-free RL',complexity:.42,training_cost:.42,inference_cost:.20,sovereignty:.80,governance:.80},
  dyna_q:{name:'Dyna-Q',family:'Model-based RL',complexity:.55,training_cost:.58,inference_cost:.24,sovereignty:.80,governance:.81},
  muzero_lite:{name:'MuZero-Lite',family:'Latent world model + MCTS',complexity:.82,training_cost:.92,inference_cost:.55,sovereignty:.77,governance:.78},
  shielded_muzero:{name:'Shielded MuZero-Lite',family:'World model + MCTS + constraint shield',complexity:.92,training_cost:1.00,inference_cost:.62,sovereignty:.88,governance:.94}
};

function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(storageKey)||'{}')}}catch{return defaults()}}
function defaults(){return {version:'8.8.0-UVSI3',missionId:CFG.foundry?.defaultMission||'building_operations',mode:CFG.foundry?.defaultMode||'quick',endpoint:CFG.foundry?.endpoint||'',route:null,result:null,status:'idle',lastRunAt:null,history:[]}}
let state=load();
function save(){localStorage.setItem(storageKey,JSON.stringify(state));render()}
function toast(message){const t=$('#toast');if(!t)return; t.textContent=message;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3200)}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
function seeded(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function modeCounts(){return state.mode==='deep'?{formation:1200,fresh:500,transfer:250}:state.mode==='standard'?{formation:400,fresh:220,transfer:100}:{formation:120,fresh:80,transfer:40}}
function route(){
  const m=missionPresets[state.missionId],f=m.features;
  const scores={
    incumbent:.15,
    rules:.35+.55*f.formal_rules,
    behavior_clone:.25+.60*f.historical_data,
    q_learning:.20+.25*f.feedback_speed+.20*(1-f.safety_criticality),
    dyna_q:.22+.25*f.simulator_fidelity+.20*f.delayed_rewards,
    muzero_lite:.10+.34*f.delayed_rewards+.34*f.simulator_fidelity+.20*f.partial_observability,
    shielded_muzero:.10+.30*f.delayed_rewards+.30*f.simulator_fidelity+.26*f.safety_criticality
  };
  const core=['incumbent','rules','behavior_clone',...Object.keys(scores).filter(x=>!['incumbent','rules','behavior_clone'].includes(x)).sort((a,b)=>scores[b]-scores[a]).slice(0,4)];
  const reasons=[];
  if(f.formal_rules>=.75)reasons.push('Strong formal rules make the transparent baseline unusually competitive.');
  if(f.historical_data>=.75)reasons.push('Rights-cleared historical experience supports supervised and offline-learning candidates.');
  if(f.delayed_rewards>=.65&&f.simulator_fidelity>=.70)reasons.push('Delayed consequences and credible simulation justify a MuZero-style world-model experiment.');
  if(f.safety_criticality>=.75)reasons.push('Hard external action shields and zero-violation gates are mandatory.');
  if(f.multiagent_need>=.65)reasons.push('Separated Producer, Critic, Verifier, Governor and Principal roles justify a multi-agent adapter.');
  state.route={schema:'GoalOS.AlgorithmRoute.v1',mission_id:state.missionId,features:f,selected_core_algorithms:[...new Set(core)],scores,reasons,optional_adapters:['RLlib PPO / SAC / IQL / CQL / DreamerV3','MCTX MuZero / Gumbel MuZero','PettingZoo + MAPPO','MO-Gymnasium vector rewards'],at:nowISO()};
  save();toast('Algorithm portfolio compiled');
}
function offlineTournament(){
  if(!state.route)route();
  state.status='running';render();
  setTimeout(()=>{
    const m=missionPresets[state.missionId],rng=seeded(hash(`${state.missionId}:${state.mode}:8`)),counts=modeCounts();
    const missionProfiles={
      invoice_integrity:{incumbent:[.42,.31,52,0,-20.9,-23.4],rules:[.97,1,0,0,0,-.43],behavior_clone:[.96,1,0,0,-.18,-.72],q_learning:[.80,.76,1,1,-3.2,-4.1],dyna_q:[.94,.84,0,0,-.84,-2.3],muzero_lite:[.91,.72,1,2,-3.5,-4.7],shielded_muzero:[.93,.78,0,0,-.9,-2.1]},
      building_operations:{incumbent:[.30,.33,18,0,-13.1,-15.3],rules:[.76,.57,0,0,0,-.92],behavior_clone:[.88,.62,0,0,.62,.15],q_learning:[.75,.45,8,6,-5.8,-7.7],dyna_q:[.77,.50,5,1,-4.2,-5.8],muzero_lite:[.72,.38,10,3,-6.9,-9.2],shielded_muzero:[.81,.48,0,0,.12,-.58]},
      grid_resilience:{incumbent:[.52,1,58,0,-29,-30.3],rules:[1,1,0,0,0,-.32],behavior_clone:[1,1,0,0,3.4,2.72],q_learning:[.78,1,28,12,-30,-32],dyna_q:[.82,1,18,8,-20,-22],muzero_lite:[.92,1,6,4,-8,-10],shielded_muzero:[1,1,0,0,2.1,1.15]}
    }[state.missionId];
    const candidates=state.route.selected_core_algorithms.map(id=>{
      const p=missionProfiles[id]||[.5,.5,1,1,-5,-6];const jitter=()=> (rng()-.5)*.03;
      const fresh={correct_rate:clamp((p[0]+jitter())*100)/100,evidence_coverage:clamp((p[1]+jitter())*100)/100,constraint_totals:{critical_miss:p[2],unauthorized_action:p[3]},episodes:counts.fresh,complete_cost:algorithms[id].inference_cost,human_burden:id==='incumbent'?.8:.25};
      const lcb=p[4]+jitter();const alpha=p[5]+jitter();const pass=p[2]===0&&p[3]===0&&fresh.correct_rate>=.68&&fresh.evidence_coverage>=.42&&lcb>0&&alpha>0;
      return {algorithm:{algorithm_id:id,...algorithms[id]},fresh,transfer:{correct_rate:Math.max(0,fresh.correct_rate-.04),episodes:counts.transfer},formation:{episodes:counts.formation},proof:{paired_comparison:{lower_confidence_bound:lcb,mean_paired_gain:lcb+.2},alpha:{proof_adjusted_alpha:alpha,gym_basis_risk_reserve:.2+algorithms[id].complexity*.1},hard_gate_result:{pass},pass},architecture:{policy:id},claim_boundary:'Browser portfolio simulation. Use the protected backend for executable training and fresh-case receipts.'};
    });
    const eligible=candidates.filter(c=>c.proof.pass);const references=['incumbent','rules'];let champion=eligible.sort((a,b)=>b.proof.alpha.proof_adjusted_alpha-a.proof.alpha.proof_adjusted_alpha)[0];
    if(!champion)champion=candidates.filter(c=>references.includes(c.algorithm.algorithm_id)).sort((a,b)=>b.fresh.correct_rate-a.fresh.correct_rate)[0];
    const simple=references.includes(champion.algorithm.algorithm_id);
    state.result={schema:'GoalOS.SovereignAlphaFoundry.BrowserSimulation.v1',run_id:`browser_${state.missionId}_${Date.now()}`,created_at:nowISO(),mission:{mission_id:state.missionId,name:m.name,...counts},router:state.route,candidates,references,best_reference_id:'rules',champion_id:champion.algorithm.algorithm_id,verdict:eligible.length?'SPECIALIST_ASI_GATE_SIMULATION_PASS':'RETAIN_OR_REPAIR_REFERENCE',governing_reason:simple?'No advanced candidate justified its complete burden; the transparent reference remains champion.':`${champion.algorithm.name} produced the strongest positive browser-simulated proof-adjusted Alpha.`,authority_recommendation:{maximum_recommended_level:eligible.length?'A1_RECOMMEND':'A0_OBSERVE',created:false,requires_accountable_admission:true},claim_boundary:'This browser tournament is a deterministic portfolio simulator, not executable reinforcement learning or independent fresh proof.'};
    state.status='complete';state.lastRunAt=nowISO();state.history.unshift({run_id:state.result.run_id,mission_id:state.missionId,champion_id:state.result.champion_id,verdict:state.result.verdict,at:state.lastRunAt,mode:'browser'});save();toast('Browser Alpha tournament completed');
  },350);
}
async function backendTournament(){
  const endpoint=(state.endpoint||CFG.foundry?.localEndpoint||'').replace(/\/$/,'');if(!endpoint){toast('Set a protected Foundry endpoint first');return}
  if(!state.route)route();state.status='running';render();
  try{
    const counts=modeCounts();const accessReceipt=(()=>{try{return JSON.parse(sessionStorage.getItem('goalos_uvsi3_access_v8_8_0')||localStorage.getItem('goalos_uvsi3_access_v8_8_0')||'null')}catch{return null}})();const response=await fetch(`${endpoint}/api/tournament`,{method:'POST',headers:{'Content-Type':'application/json','X-GoalOS-App':'goalos-uvsi3-v8-8'},body:JSON.stringify({mission_id:state.missionId,algorithms:state.route.selected_core_algorithms,formation_episodes:counts.formation,fresh_cases:counts.fresh,transfer_cases:counts.transfer,seed:20260811,accessReceipt})});
    if(!response.ok)throw new Error(await response.text());state.result=await response.json();state.status='complete';state.lastRunAt=nowISO();state.history.unshift({run_id:state.result.run_id,mission_id:state.missionId,champion_id:state.result.champion_id,verdict:state.result.verdict,at:state.lastRunAt,mode:'backend'});save();toast('Executable Alpha tournament completed');
  }catch(error){state.status='error';save();toast(`Foundry request failed: ${error.message}`)}
}
async function testEndpoint(){const endpoint=(state.endpoint||CFG.foundry?.localEndpoint||'').replace(/\/$/,'');if(!endpoint)return toast('Enter the backend URL');try{const r=await fetch(`${endpoint}/api/health`);if(!r.ok)throw new Error(await r.text());const d=await r.json();toast(`${d.service} ready · v${d.version}`)}catch(e){toast(`Backend unavailable: ${e.message}`)}}
function champion(){return state.result?.candidates?.find(c=>c.algorithm.algorithm_id===state.result.champion_id)}
function adoptChampion(){const c=champion();if(!c)return toast('Run a tournament first');const result=state.result;window.GoalOSDemo?.patchState?.(draft=>{
  const id=`alpha_${c.algorithm.algorithm_id}_${Date.now().toString(36)}`;const q=clamp(c.fresh.correct_rate*100),ev=clamp(c.fresh.evidence_coverage*100),rel=clamp((c.fresh.correct_rate||0)*100),gov=clamp((c.algorithm.governance||.75)*100),sov=clamp((c.algorithm.sovereignty||.75)*100);
  const candidate={id,name:`Alpha Foundry · ${c.algorithm.name}`,kind:c.proof.pass?'specialist':'executable',generation:(draft.recursive.generation||0)+1,parentId:draft.selectedCandidateId,selected:true,createdAt:nowISO(),notes:`Imported from ${result.run_id}. ${result.governing_reason}`,params:{perception:q,reasoning:q,domain:q,tools:clamp(60+c.algorithm.complexity*30),evidence:ev,verifier:gov,memory:75,governance:gov,portability:sov,speed:clamp(85-c.algorithm.inference_cost*25),costEfficiency:clamp(90-c.algorithm.training_cost*35),humanEfficiency:75,resilience:rel,calibration:rel,exploration:clamp(50+c.algorithm.complexity*35)},burden:{formation:clamp(c.algorithm.training_cost*70),operation:clamp(c.algorithm.inference_cost*55),migration:25,proof:45,dependency:clamp((1-c.algorithm.sovereignty)*70),irreversibility:20}};
  draft.candidates.push(candidate);draft.selectedCandidateId=id;draft.gradient.candidateId=id;draft.chronicle.unshift({id:`alpha_${Date.now()}`,type:'ALPHA_FOUNDRY_CANDIDATE_IMPORTED',title:candidate.name,detail:result.governing_reason,data:{run_id:result.run_id,proof:c.proof},at:nowISO(),generation:draft.meta.institutionGeneration});return draft
});toast('Champion imported as a candidate; it inherited neither proof nor authority.');window.GoalOSDemo?.navTo?.('manifold')}
function fmt(v,d=2){return Number(v??0).toFixed(d)}
function featureRows(){const f=missionPresets[state.missionId].features;return Object.entries(f).map(([k,v])=>`<div class="af-feature"><span>${esc(k.replaceAll('_',' '))}</span><div><i style="width:${clamp(v*100)}%"></i></div><b>${Math.round(v*100)}</b></div>`).join('')}
function algorithmCards(){if(!state.route)return '<div class="empty-state"><h3>Compile the portfolio</h3><p>The Router will retain simple baselines and add advanced candidates only when the mission structure justifies them.</p></div>';return state.route.selected_core_algorithms.map((id,i)=>{const a=algorithms[id],score=state.route.scores[id]||0;return `<article class="af-algorithm ${id.includes('muzero')?'world-model':''}"><div class="af-rank">${String(i+1).padStart(2,'0')}</div><div><h3>${esc(a.name)}</h3><p>${esc(a.family)}</p><small>Suitability ${Math.round(score*100)} · Complexity ${Math.round(a.complexity*100)} · Sovereignty ${Math.round(a.sovereignty*100)}</small></div></article>`}).join('')}
function resultTable(){if(!state.result)return '<div class="empty-state"><h3>No tournament result yet</h3><p>Run the browser simulator for an immediate demonstration or the protected backend for executable candidate training.</p></div>';return `<div class="table-scroll"><table class="af-table"><thead><tr><th>Candidate</th><th>Fresh quality</th><th>Evidence</th><th>Critical</th><th>Unauthorized</th><th>LCB gain</th><th>Proof-adjusted α</th><th>Gate</th></tr></thead><tbody>${state.result.candidates.map(c=>{const win=c.algorithm.algorithm_id===state.result.champion_id;return `<tr class="${win?'af-winner':''}"><td><b>${esc(c.algorithm.name)}</b><small>${esc(c.algorithm.family)}</small></td><td>${Math.round((c.fresh.correct_rate||0)*100)}%</td><td>${Math.round((c.fresh.evidence_coverage||0)*100)}%</td><td>${c.fresh.constraint_totals?.critical_miss||0}</td><td>${c.fresh.constraint_totals?.unauthorized_action||0}</td><td>${fmt(c.proof.paired_comparison?.lower_confidence_bound)}</td><td>${fmt(c.proof.alpha?.proof_adjusted_alpha)}</td><td><span class="mini-badge ${c.proof.pass?'pass':'fail'}">${c.proof.pass?'PASS':'NO'}</span></td></tr>`}).join('')}</tbody></table></div>`}
function renderRouter(){const root=$('#section-algorithm-router');if(!root)return;const m=missionPresets[state.missionId],counts=modeCounts();root.innerHTML=`
<div class="page-head"><div><div class="eyebrow">UVSI3 · Mission-to-Algorithm Constitution</div><h1>Algorithm Router</h1><p>Determine which experiment portfolio can credibly test MuZero, another learning method—or a simpler architecture—without assuming that complexity creates Alpha.</p></div><div class="page-actions"><button class="button" data-af-action="route">Compile portfolio</button><button class="button secondary" data-af-nav="alpha-foundry">Open Alpha Foundry</button></div></div>
<div class="af-thesis"><strong>THE ROUTER PROPOSES. THE FOUNDRY TRAINS. FRESH PROOF DECIDES.</strong><span>Every portfolio retains an incumbent and transparent simple baseline.</span></div>
<div class="grid-2"><section class="card"><h2>Mission structure</h2><div class="form-grid"><label>Mission<select id="afMission">${Object.entries(missionPresets).map(([id,x])=>`<option value="${id}" ${id===state.missionId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Experiment depth<select id="afMode"><option value="quick" ${state.mode==='quick'?'selected':''}>Quick · ${counts.formation}/${counts.fresh}/${counts.transfer}</option><option value="standard" ${state.mode==='standard'?'selected':''}>Standard</option><option value="deep" ${state.mode==='deep'?'selected':''}>Deep</option></select></label></div><p>${esc(m.description)}</p>${featureRows()}</section><section class="card navy"><h2>Router judgment</h2>${state.route?`<div class="big-number">${state.route.selected_core_algorithms.length}</div><p>Core candidates selected, including transparent references.</p><ul>${state.route.reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="callout gold"><strong>MuZero is a candidate—not a default winner.</strong><span>The complete burden and Gym-to-reality reserve remain in the denominator.</span></div>`:'<p>Compile the algorithm portfolio to generate the governed experiment plan.</p>'}</section></div>
<section class="card"><div class="card-head"><div><h2>Candidate portfolio</h2><p>Algorithms are organized by institutional purpose, not fashion.</p></div></div><div class="af-algorithm-grid">${algorithmCards()}</div></section>
<section class="grid-3"><article class="card"><h2>Training stack</h2><p>Warm start → history → interactive practice → constrained learning → architecture evolution → transfer replay.</p></article><article class="card"><h2>Hard firewall</h2><p>The candidate cannot inspect protected cases, change thresholds, certify itself or inherit authority.</p></article><article class="card"><h2>Selection objective</h2><p>Maximize conservative lower-bound Mission Alpha among candidates passing every non-compensable gate.</p></article></section>`}
function renderFoundry(){const root=$('#section-alpha-foundry');if(!root)return;const c=champion(),endpoint=state.endpoint||CFG.foundry?.localEndpoint||'';root.innerHTML=`
<div class="page-head"><div><div class="eyebrow">Sovereign Successor Training Foundry Ω</div><h1>Alpha Foundry Ω</h1><p>Train diverse candidates, freeze exact releases, compare matched fresh cases and select the strongest residual mission advantage—or retain the simpler architecture.</p></div><div class="page-actions"><button class="button" data-af-action="browser-run">Run browser tournament</button><button class="button navy" data-af-action="backend-run">Run executable backend</button></div></div>
<div class="hero af-hero"><div class="eyebrow">The governing thesis</div><h1>The best algorithm is the one that survives the complete denominator.</h1><p>MuZero wins only when its planning advantage exceeds its formation cost, inference burden, proof debt, tail risk and Gym-to-reality basis risk. Otherwise, another method—or the simplest credible architecture—wins.</p><div class="hero-doctrine">Highest simulated score ≠ strongest proven Alpha.</div></div>
<div class="grid-3"><section class="card"><h2>1 · Formation</h2><p>Expert demonstrations, historical replay, Q-learning, Dyna-Q and MuZero-inspired world-model search improve candidates on visible cases.</p></section><section class="card"><h2>2 · Exact freeze</h2><p>Models, tools, data, workflow, verifier, resources and permissions are frozen before certification.</p></section><section class="card"><h2>3 · Fresh proof</h2><p>One challenger competes against the incumbent and best simple alternative on matched protected cases.</p></section></div>
<section class="card"><div class="card-head"><div><h2>Protected training endpoint</h2><p>GitHub Pages remains the public control plane. Executable training belongs in a separate compute plane.</p></div><span class="mini-badge ${state.status==='running'?'warn':state.status==='complete'?'pass':''}">${esc(state.status.toUpperCase())}</span></div><div class="form-grid"><label>Foundry endpoint<input id="afEndpoint" value="${esc(endpoint)}" placeholder="https://your-protected-foundry.example"></label><label>Mission<select id="afMissionFoundry">${Object.entries(missionPresets).map(([id,x])=>`<option value="${id}" ${id===state.missionId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label></div><div class="button-row"><button class="button secondary" data-af-action="save-endpoint">Save endpoint</button><button class="button secondary" data-af-action="test-endpoint">Test endpoint</button><button class="button" data-af-action="backend-run">Train and compare</button></div><div class="callout"><strong>Public-static boundary</strong><span>The browser simulation is educational. The local/protected backend executes the dependency-free training tournament and creates episode receipts.</span></div></section>
<section class="card"><div class="card-head"><div><h2>Alpha tournament</h2><p>Matched fresh-work scorecard after complexity, cost, hard gates and basis-risk reserve.</p></div>${state.result?`<span class="mini-badge ${state.result.verdict.includes('PASS')?'pass':'warn'}">${esc(state.result.verdict)}</span>`:''}</div>${resultTable()}</section>
${state.result?`<section class="af-champion"><div class="af-seal">α</div><div><div class="eyebrow">Foundry disposition</div><h2>${esc(c?.algorithm?.name||state.result.champion_id)}</h2><p>${esc(state.result.governing_reason)}</p><div class="af-verdict-grid"><span><b>${fmt(c?.proof?.alpha?.proof_adjusted_alpha)}</b>Proof-adjusted α</span><span><b>${fmt(c?.proof?.paired_comparison?.lower_confidence_bound)}</b>Fresh-work LCB</span><span><b>${Math.round((c?.fresh?.correct_rate||0)*100)}%</b>Fresh quality</span><span><b>${state.result.authority_recommendation?.maximum_recommended_level||'A0'}</b>Maximum review posture</span></div><div class="button-row"><button class="button" data-af-action="adopt">Import as candidate</button><button class="button secondary" data-af-action="download-result">Download record</button></div><small>Importing creates candidacy only. It transfers neither proof nor authority into the main succession state.</small></div></section>`:''}
<section class="card"><h2>Why this is sovereign</h2><div class="grid-4"><div class="metric-card"><b>Mission</b><span>Frozen objective and gates</span></div><div class="metric-card"><b>Environment</b><span>Institution-owned cases and receipts</span></div><div class="metric-card"><b>Portability</b><span>Models compete inside the same Gym</span></div><div class="metric-card"><b>Authority</b><span>Always separate from training</span></div></div></section>`}
function render(){renderRouter();renderFoundry()}
function handleClick(e){const nav=e.target.closest('[data-af-nav]');if(nav){window.GoalOSDemo?.navTo?.(nav.dataset.afNav);return}const a=e.target.closest('[data-af-action]');if(!a)return;const id=a.dataset.afAction;if(id==='route')route();if(id==='browser-run')offlineTournament();if(id==='backend-run')backendTournament();if(id==='test-endpoint')testEndpoint();if(id==='save-endpoint'){state.endpoint=$('#afEndpoint')?.value.trim().replace(/\/$/,'')||'';save();toast('Foundry endpoint saved')}if(id==='download-result'&&state.result)download(`GoalOS_Alpha_Foundry_${state.result.run_id}.json`,state.result);if(id==='adopt')adoptChampion()}
function handleChange(e){if(e.target.id==='afMission'||e.target.id==='afMissionFoundry'){state.missionId=e.target.value;state.route=null;state.result=null;save()}if(e.target.id==='afMode'){state.mode=e.target.value;state.result=null;save()}}
document.addEventListener('click',handleClick);document.addEventListener('change',handleChange);document.addEventListener('goalos:state',()=>setTimeout(render,0));document.addEventListener('DOMContentLoaded',render);
window.GoalOSAlphaFoundry={getState:()=>JSON.parse(JSON.stringify(state)),route,runBrowser:offlineTournament,runBackend:backendTournament,render};
})();
