(()=>{'use strict';
const CFG={chainId:'0x1',registry:'0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',wrapper:'0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401',token:'0xA61a3B3a130a9c20768EEBF97E21515A6046a1fA',threshold:1000000000000000000000000n,keys:['goalosSingularityNavigatorDualAccessReceiptV331','goalosSingularityNavigatorDirectOwnerReceiptV3','goalos.sn5.bi2.agialpha.access.receipt'],recheckMs:300000};
const $=s=>document.querySelector(s);let receipt=null,timer=null,lastVerified=0;const MASK64=(1n<<64n)-1n,ROT=[0,1,62,28,27,36,44,6,55,20,3,10,43,25,39,41,45,15,21,8,18,2,61,56,14],RC=[0x1n,0x8082n,0x800000000000808an,0x8000000080008000n,0x808bn,0x80000001n,0x8000000080008081n,0x8000000000008009n,0x8an,0x88n,0x80008009n,0x8000000an,0x8000808bn,0x800000000000008bn,0x8000000000008089n,0x8000000000008003n,0x8000000000008002n,0x8000000000000080n,0x800an,0x800000008000000an,0x8000000080008081n,0x8000000000008080n,0x80000001n,0x8000000080008008n];
function rotl(x,n){n=BigInt(n);return n===0n?x&MASK64:((x<<n)|(x>>(64n-n)))&MASK64}function kF(s){for(let r=0;r<24;r++){const C=Array(5),D=Array(5),B=Array(25);for(let x=0;x<5;x++)C[x]=s[x]^s[x+5]^s[x+10]^s[x+15]^s[x+20];for(let x=0;x<5;x++)D[x]=C[(x+4)%5]^rotl(C[(x+1)%5],1);for(let x=0;x<5;x++)for(let y=0;y<5;y++)s[x+5*y]=(s[x+5*y]^D[x])&MASK64;for(let x=0;x<5;x++)for(let y=0;y<5;y++)B[y+5*((2*x+3*y)%5)]=rotl(s[x+5*y],ROT[x+5*y]);for(let x=0;x<5;x++)for(let y=0;y<5;y++)s[x+5*y]=(B[x+5*y]^((~B[(x+1)%5+5*y])&B[(x+2)%5+5*y]))&MASK64;s[0]=(s[0]^RC[r])&MASK64}}function k256(input){const bytes=typeof input==='string'?new TextEncoder().encode(input):input,rate=136,n=Math.ceil((bytes.length+1)/rate)*rate,p=new Uint8Array(n);p.set(bytes);p[bytes.length]^=1;p[n-1]^=128;const s=Array(25).fill(0n);for(let o=0;o<p.length;o+=rate){for(let i=0;i<rate;i++)s[Math.floor(i/8)]^=BigInt(p[o+i])<<BigInt(8*(i%8));kF(s)}const out=new Uint8Array(32);for(let i=0;i<32;i++)out[i]=Number((s[Math.floor(i/8)]>>BigInt(8*(i%8)))&255n);return out}function hx(b){return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}function cat(a,b){const o=new Uint8Array(a.length+b.length);o.set(a);o.set(b,a.length);return o}function namehash(name){let node=new Uint8Array(32);for(const label of name.toLowerCase().split('.').reverse())node=k256(cat(node,k256(label)));return'0x'+hx(node)}
function same(a,b){return String(a||'').toLowerCase()===String(b||'').toLowerCase()}function addr(data,word=0){const h=String(data||'').replace(/^0x/,'');if(h.length<(word+1)*64)throw Error('Malformed address response');return'0x'+h.slice(word*64+24,word*64+64)}function uint(data,word=0){const h=String(data||'').replace(/^0x/,'');return BigInt('0x'+(h.slice(word*64,(word+1)*64)||'0'))}function normalize(a){if(!/^0x[0-9a-fA-F]{40}$/.test(String(a||'')))throw Error('Invalid Ethereum account');return String(a).toLowerCase()}function fmt(raw){const w=raw/1000000000000000000n,f=(raw%1000000000000000000n).toString().padStart(18,'0').slice(0,4).replace(/0+$/,'');return w.toLocaleString('en-US')+(f?'.'+f:'')}
function active(r){return !!(r&&r.address&&r.expiresAt&&Date.parse(r.expiresAt)>Date.now()&&['AGI_CLUB_DIRECT_OWNER','AGIALPHA_BALANCE_QUALIFIED'].includes(r.accessClass))}function cached(){for(const key of CFG.keys){try{const r=JSON.parse(sessionStorage.getItem(key)||'null');if(r&&!r.accessClass&&r.name)r.accessClass='AGI_CLUB_DIRECT_OWNER';if(r?.expiresAtISO&&!r.expiresAt)r.expiresAt=r.expiresAtISO;if(active(r))return r}catch{}}return null}
async function request(method,params=[]){if(!window.ethereum)throw Error('Open the unified access gate in a wallet-enabled browser.');return window.ethereum.request({method,params})}async function call(to,data){return request('eth_call',[{to,data},'latest'])}
async function verifyOwner(r,address){const node=namehash(r.name),registryOwner=addr(await call(CFG.registry,'0x02571be3'+node.slice(2)));if(same(registryOwner,address))return true;if(!same(registryOwner,CFG.wrapper))return false;const wrapped=addr(await call(CFG.wrapper,'0x6352211e'+node.slice(2)));if(!same(wrapped,address))return false;const data=await call(CFG.wrapper,'0x0178fe3f'+node.slice(2));const dataOwner=addr(data,0),expiry=Number(uint(data,2));return same(dataOwner,address)&&(!expiry||expiry>Math.floor(Date.now()/1000))}
async function verifyToken(address){const data='0x70a08231'+normalize(address).slice(2).padStart(64,'0'),raw=BigInt(await call(CFG.token,data)||'0x0');return{ok:raw>=CFG.threshold,raw}}
function statusText(r){if(!r)return'Access locked';return r.accessClass==='AGI_CLUB_DIRECT_OWNER'?`AGI Club · ${r.name}`:`AGIALPHA · ${r.observedBalanceFormatted||'qualified'}`}
function setLocked(message){receipt=null;document.body.classList.add('access-locked');$('#unifiedAccessGuard')?.removeAttribute('hidden');const s=$('#gymAccessGuardStatus');if(s)s.textContent=message||'Current qualifying access is required.';const chip=$('#gymAccessChip');if(chip){chip.textContent='Access locked';chip.classList.add('danger')}clearInterval(timer);document.dispatchEvent(new CustomEvent('goalos:gym-access',{detail:{verified:false,reason:message}}))}
function setUnlocked(r,source='session'){receipt=r;lastVerified=Date.now();document.body.classList.remove('access-locked');$('#unifiedAccessGuard')?.setAttribute('hidden','');const chip=$('#gymAccessChip');if(chip){chip.textContent=statusText(r);chip.classList.remove('danger');chip.title=`Current qualifying route · ${source}`};document.dispatchEvent(new CustomEvent('goalos:gym-access',{detail:{verified:true,receipt:r,source}}));clearInterval(timer);timer=setInterval(()=>revalidate('periodic'),CFG.recheckMs)}
async function revalidate(reason='manual'){if(window.parent!==window){window.parent.postMessage({type:'GOALOS_GYM_ACCESS_REQUEST',reason},location.origin==='null'?'*':location.origin);return true}const r=receipt||cached();if(!active(r)){setLocked('The verified access session is missing or expired.');return false}try{const chain=String(await request('eth_chainId')).toLowerCase();if(chain!==CFG.chainId)throw Error('Ethereum Mainnet is required.');const accounts=await request('eth_accounts'),address=normalize(accounts?.[0]);if(!same(address,r.address))throw Error('The connected wallet changed.');let ok=false;if(r.accessClass==='AGI_CLUB_DIRECT_OWNER')ok=await verifyOwner(r,address);else{const e=await verifyToken(address);ok=e.ok;if(ok){r.observedBalance=e.raw.toString();r.observedBalanceFormatted=fmt(e.raw)}}if(!ok)throw Error('The connected wallet no longer satisfies the selected access route.');r.lastVerifiedAt=new Date().toISOString();setUnlocked(r,'on-chain revalidation');return true}catch(e){setLocked(String(e.message||e));return false}}
function parentResponse(data){if(data?.type!=='GOALOS_GYM_ACCESS_RESPONSE')return;if(data.verified&&active(data.receipt))setUnlocked(data.receipt,'parent institution');else setLocked(data.reason||'The parent institution is locked.')}
function init(){window.addEventListener('message',e=>parentResponse(e.data));const lang=(localStorage.getItem('goalosLanguage')||document.documentElement.lang||'en').toLowerCase().startsWith('fr')?'fr':'en';document.documentElement.dataset.accessLang=lang;$$('[data-access-lang]').forEach(b=>b.addEventListener('click',()=>{document.documentElement.dataset.accessLang=b.dataset.accessLang;localStorage.setItem('goalosLanguage',b.dataset.accessLang)}));const r=cached();if(window.parent!==window){window.parent.postMessage({type:'GOALOS_GYM_ACCESS_REQUEST',reason:'initial'},location.origin==='null'?'*':location.origin);setTimeout(()=>{if(!receipt&&r)setUnlocked(r,'shared session')},900)}else if(r){receipt=r;revalidate('initial')}else setLocked('Choose either qualifying route in the unified GoalOS entrance.');window.addEventListener('focus',()=>{if(receipt&&Date.now()-lastVerified>60000)revalidate('focus')});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&receipt&&Date.now()-lastVerified>60000)revalidate('visibility')});window.GOALOS_GYM_ACCESS={get verified(){return active(receipt)},get receipt(){return receipt},revalidate,setLocked,setUnlocked}}
const $$=s=>[...document.querySelectorAll(s)];if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();