(() => {
'use strict';
const CFG=window.SUCCESSOR_OMEGA_CONFIG,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ACCESS_KEY='successor_omega_access_v1',ACTIVITY_KEY='successor_omega_activity_v1';
let manifest=null,keyBytes=null,session=null,downloading=false,periodic=null,inactivity=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normal=v=>/^0x[0-9a-fA-F]{40}$/.test(String(v||''))?String(v).toLowerCase():null;
const short=v=>v?`${v.slice(0,6)}…${v.slice(-4)}`:'—';
const hexUtf8=t=>'0x'+[...new TextEncoder().encode(t)].map(v=>v.toString(16).padStart(2,'0')).join('');
const b64=v=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
const hex=v=>[...new Uint8Array(v)].map(x=>x.toString(16).padStart(2,'0')).join('');
const configured=()=>/^https:\/\//.test(CFG.access.brokerUrl)&&!CFG.access.brokerUrl.includes('REPLACE-WITH');
const broker=()=>CFG.access.brokerUrl.replace(/\/+$/,'');
const bytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(n>104857600?0:1)} MB`;
function toast(m){const e=$('#toast');e.textContent=m;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),3600)}
function modal(t,h){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=h;$('#modal').classList.remove('hidden')}
function status(m,t='neutral'){const e=$('#accessStatus');e.className=`access-status ${t}`;e.innerHTML=`<span class="access-status-dot"></span><span>${esc(m)}</span>`}
function busy(v){$$('.access-action').forEach(b=>{b.dataset.label??=b.textContent;b.disabled=v;b.textContent=v?'Verifying…':b.dataset.label})}
function progress(label,p){$('#downloadProgress').classList.remove('hidden');$('#downloadLabel').textContent=label;$('#downloadPercent').textContent=`${Math.round(p)}%`;$('#downloadBar').value=p}
async function rpc(method,params=[]){if(!window.ethereum)throw new Error('No injected Ethereum wallet was found. Open this page in a wallet-enabled browser.');return window.ethereum.request({method,params})}
async function wallet(){const a=await rpc('eth_requestAccounts'),w=normal(a?.[0]);if(!w)throw new Error('The wallet did not return a valid Ethereum address.');let c=await rpc('eth_chainId');if(c!==CFG.ethereumChainId){try{await rpc('wallet_switchEthereumChain',[{chainId:CFG.ethereumChainId}])}catch{throw new Error('Switch the wallet to Ethereum Mainnet, then try again.')}c=await rpc('eth_chainId')}if(c!==CFG.ethereumChainId)throw new Error('Ethereum Mainnet is required.');return w}
function label(v){v=String(v||'').trim().toLowerCase();if(!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(v))throw new Error('Enter one ASCII label using letters, numbers or internal hyphens. Do not enter dots.');return v}
async function request(path,{body,token}={}){if(!configured())throw new Error('The secure access broker has not been configured. Deploy the included Worker, then update config.js.');const headers={'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(`${broker()}${path}`,{method:'POST',headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Access broker returned ${r.status}.`);return d}
async function begin(route,clubLabel=null){busy(true);status(route==='AGI_CLUB_DIRECT_OWNER'?'Verifying current direct AGI Club ownership…':'Verifying current direct AGIALPHA balance…','busy');try{const address=await wallet();const ch=await request('/challenge',{body:{address,route,clubLabel,appId:CFG.appId,appVersion:CFG.version,origin:location.origin,path:location.pathname}});status('Sign the domain-bound access request in your wallet.','busy');const signature=await rpc('personal_sign',[hexUtf8(ch.message),address]);accept(await request('/verify',{body:{address,route,clubLabel,nonce:ch.nonce,message:ch.message,signature}}));unlock();status('Current on-chain eligibility verified. Protected publication unlocked.','pass')}catch(e){status(e.message||String(e),'fail')}finally{busy(false)}}
function accept(r){if(!r?.sessionToken||!r?.contentKeyB64||!normal(r.wallet))throw new Error('The access broker returned an incomplete session.');keyBytes=b64(r.contentKeyB64);session={sessionToken:r.sessionToken,wallet:normal(r.wallet),route:r.route,expiresAt:r.expiresAt,eligibility:r.eligibility||{},authorityCreated:'NONE'};sessionStorage.setItem(ACCESS_KEY,JSON.stringify(session));mark()}
function stored(){try{return JSON.parse(sessionStorage.getItem(ACCESS_KEY)||'null')}catch{return null}}
function unlock(){document.body.classList.remove('access-locked');$('#accessGate').classList.add('hidden');const s=$('#applicationShell');s.removeAttribute('inert');s.setAttribute('aria-hidden','false');$('#accessChip').textContent=`Access granted · ${short(session.wallet)}`;const route=session.route==='AGI_CLUB_DIRECT_OWNER'?`AGI Club: ${session.eligibility?.name||'direct owner'}`:`AGIALPHA: ${session.eligibility?.balanceFormatted||'qualifying direct balance'}`;$('#sessionSummary').textContent=`${route}. Session expires ${new Date(session.expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}.`;checks()}
async function lock(reason='Access requires fresh verification.',notify=true){const token=session?.sessionToken;session=null;keyBytes=null;sessionStorage.removeItem(ACCESS_KEY);clearInterval(periodic);clearInterval(inactivity);document.body.classList.add('access-locked');$('#accessGate').classList.remove('hidden');const s=$('#applicationShell');s.setAttribute('inert','');s.setAttribute('aria-hidden','true');status(reason,'fail');if(notify&&token&&configured())request('/revoke',{token}).catch(()=>{})}
async function revalidate(){const s=session||stored();if(!s?.sessionToken||new Date(s.expiresAt).getTime()<=Date.now()){await lock('The access session expired. Verify eligibility again.',false);return false}try{const a=normal((await rpc('eth_accounts'))?.[0]),c=await rpc('eth_chainId');if(a!==s.wallet||c!==CFG.ethereumChainId)throw new Error('Wallet or network changed.');accept(await request('/session',{token:s.sessionToken,body:{wallet:s.wallet}}));unlock();return true}catch(e){await lock(`${e.message||e} Access relocked.`,false);return false}}
function mark(){localStorage.setItem(ACTIVITY_KEY,String(Date.now()))}function checks(){clearInterval(periodic);clearInterval(inactivity);periodic=setInterval(revalidate,CFG.access.revalidateMinutes*60000);inactivity=setInterval(()=>{const last=Number(localStorage.getItem(ACTIVITY_KEY)||Date.now());if(Date.now()-last>CFG.access.inactivityMinutes*60000)lock('Session locked after inactivity. Verify eligibility again.')},30000)}
async function fetchBytes(url,label,onProgress=null,retries=2){let lastError;for(let attempt=0;attempt<=retries;attempt++){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`Protected file request failed (${r.status}).`);const total=Number(r.headers.get('Content-Length')||0);if(!r.body){const out=new Uint8Array(await r.arrayBuffer());onProgress?.(out.length,total||out.length);return out}const reader=r.body.getReader(),chunks=[];let loaded=0;while(true){const x=await reader.read();if(x.done)break;chunks.push(x.value);loaded+=x.value.length;if(onProgress)onProgress(loaded,total);else progress(`Downloading encrypted ${label} · ${bytes(loaded)}${total?` of ${bytes(total)}`:''}`,total?Math.min(72,loaded/total*72):35)}const out=new Uint8Array(loaded);let offset=0;for(const chunk of chunks){out.set(chunk,offset);offset+=chunk.length}return out}catch(error){lastError=error;if(attempt<retries)await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)))}}throw lastError}
async function sha(v){return hex(await crypto.subtle.digest('SHA-256',v))}
async function contentKey(){return crypto.subtle.importKey('raw',keyBytes,{name:'AES-GCM'},false,['decrypt'])}
function orderedParts(asset){const parts=[...(asset.parts||[])].sort((a,b)=>a.index-b.index),expected=asset.multipart?.partCount||parts.length;if(!parts.length||parts.length!==expected)throw new Error('Protected multipart manifest is incomplete.');for(let i=0;i<parts.length;i++){if(parts[i].index!==i+1||!parts[i].file||!parts[i].ivB64||!parts[i].aad)throw new Error('Protected multipart manifest order is invalid.')}return parts}
async function decryptSingle(asset,key){const encrypted=await fetchBytes(asset.file,asset.label);if(encrypted.length!==asset.ciphertextBytes||await sha(encrypted)!==asset.ciphertextSha256)throw new Error('Encrypted asset integrity verification failed.');progress(`Decrypting ${asset.label} locally…`,80);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(asset.ivB64),additionalData:new TextEncoder().encode(asset.aad),tagLength:128},key,encrypted);progress(`Verifying ${asset.label}…`,94);if(plain.byteLength!==asset.plaintextBytes||await sha(plain)!==asset.plaintextSha256)throw new Error('Decrypted asset integrity verification failed.');return new Blob([plain],{type:asset.mimeType})}
async function decryptMultipart(asset,key){const parts=orderedParts(asset),plainParts=[];let plainBytes=0;for(let i=0;i<parts.length;i++){const part=parts[i],step=90/parts.length,base=i*step;const encrypted=await fetchBytes(part.file,`${asset.label} · part ${i+1}/${parts.length}`,(loaded,total)=>{const denominator=total||part.ciphertextBytes;progress(`Downloading encrypted ${asset.label} · part ${i+1}/${parts.length} · ${bytes(loaded)} of ${bytes(denominator)}`,base+Math.min(step*.70,loaded/denominator*step*.70))});if(encrypted.length!==part.ciphertextBytes||await sha(encrypted)!==part.ciphertextSha256)throw new Error(`Encrypted part ${i+1} integrity verification failed.`);progress(`Decrypting and verifying ${asset.label} · part ${i+1}/${parts.length}…`,base+step*.82);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(part.ivB64),additionalData:new TextEncoder().encode(part.aad),tagLength:128},key,encrypted);if(plain.byteLength!==part.plaintextBytes||await sha(plain)!==part.plaintextSha256)throw new Error(`Decrypted part ${i+1} integrity verification failed.`);plainParts.push(plain);plainBytes+=plain.byteLength;progress(`Verified ${asset.label} · part ${i+1}/${parts.length}.`,base+step)}if(plainBytes!==asset.plaintextBytes||plainBytes!==asset.multipart?.wholePlaintextBytes)throw new Error('Reassembled protected asset size verification failed.');progress(`Assembling ${asset.label}…`,96);return new Blob(plainParts,{type:asset.mimeType})}
async function decrypt(asset){if(!keyBytes&&!(await revalidate()))throw new Error('Fresh eligibility is required.');const key=await contentKey();const blob=Array.isArray(asset.parts)&&asset.parts.length?await decryptMultipart(asset,key):await decryptSingle(asset,key);progress(`${asset.label} is ready.`,100);return blob}
async function openAsset(id){if(downloading)return;const asset=manifest?.assets?.find(x=>x.id===id);if(!asset)return toast('Protected asset not found.');downloading=true;const popup=asset.action==='open'?window.open('about:blank','_blank'):null;try{if(popup)popup.document.body.innerHTML='<p style="font:16px system-ui;padding:30px">Preparing protected publication…</p>';const blob=await decrypt(asset),url=URL.createObjectURL(blob);if(asset.action==='open'){if(popup)popup.location.href=url;else window.open(url,'_blank','noopener')}else{const a=document.createElement('a');a.href=url;a.download=asset.filename;document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),15*60*1000);toast(`${asset.label} verified and ready.`)}catch(e){if(popup)popup.close();toast(e.message||String(e));progress(e.message||String(e),0)}finally{downloading=false;setTimeout(()=>$('#downloadProgress').classList.add('hidden'),1000)}}
function details(){modal('How access verification works',`<div class="callout"><strong>Access = current direct AGI Club owner OR current direct holder of at least 1,000,000 official AGIALPHA on Ethereum Mainnet.</strong></div><h3>AGI Club route</h3><p>The broker checks the exact name <code>label.club.agi.eth</code> through the ENS Registry and, when wrapped, the NameWrapper effective owner and expiry. The signing wallet must be the current direct owner.</p><h3>AGIALPHA route</h3><p>The broker reads <code>balanceOf(signingWallet)</code> from <code>${esc(CFG.token.contract)}</code>. Only the signing wallet's current direct balance counts.</p><h3>Protected publication</h3><p>The GitHub Pages repository contains encrypted payloads, not readable PDFs. After verification, a short-lived broker session supplies the key over HTTPS. Your browser decrypts and hash-verifies the selected file locally. Large publications are stored as independently authenticated browser-safe parts and are automatically reassembled into the original file.</p><h3>Session</h3><p>Eligibility is rechecked periodically and after wallet, network or focus changes. The session creates <strong>no authority</strong>.</p><h3>Never requested</h3><p>No approval, transfer, payment, staking, locking, burning, deposit, custody or transaction authority.</p>`)}
async function init(){try{const r=await fetch('protected/manifest.json',{cache:'no-store'});if(!r.ok)throw new Error('Protected content manifest could not be loaded.');manifest=await r.json()}catch(e){status(e.message,'fail');return}if(!configured())status('Secure access broker not configured. Deploy the included Worker and update config.js.','fail');const s=stored();if(s?.sessionToken&&configured()){session=s;status('Revalidating existing access session…','busy');await revalidate()}if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>{})}
$('#clubAccessButton').addEventListener('click',()=>{try{begin('AGI_CLUB_DIRECT_OWNER',label($('#clubLabel').value))}catch(e){status(e.message,'fail')}});$('#tokenAccessButton').addEventListener('click',()=>begin('AGIALPHA_DIRECT_BALANCE'));$('#copyContract').addEventListener('click',async()=>{await navigator.clipboard.writeText(CFG.token.contract);toast('Official AGIALPHA contract copied.')});$('#accessDetailsButton').addEventListener('click',details);$('#modalClose').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')});$('#lockButton').addEventListener('click',()=>lock('Session locked. Verify current eligibility to return.'));$$('.protected-action').forEach(b=>b.addEventListener('click',()=>openAsset(b.dataset.asset)));['pointerdown','keydown','touchstart','scroll'].forEach(n=>addEventListener(n,mark,{passive:true}));addEventListener('focus',()=>{if(session)revalidate()});if(window.ethereum){window.ethereum.on?.('accountsChanged',()=>{if(session)lock('Wallet account changed. Verify again.',false)});window.ethereum.on?.('chainChanged',()=>{if(session)lock('Wallet network changed. Ethereum Mainnet is required.',false)})}addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.add('hidden')});init();
})();
