
def publication_page(lang):
 fr=lang=='fr'; depth=2 if fr else 3; path='/goalos-legal/publication-data/' if fr else '/en/goalos-legal/publication-data/'
 body=f'''<section class="page-hero"><div class="wrap page-hero-grid"><div><div class="eyebrow">{'Gouvernance des publications' if fr else 'Publication governance'}</div><h1>{'DONNÉES, VISUELS ET PROVENANCE' if fr else 'DATA, VISUALS AND PROVENANCE'}</h1><p class="lead">{'Comment le site distingue faits, hypothèses, scénarios, concepts visuels et résultats empiriques.' if fr else 'How the site separates facts, hypotheses, scenarios, conceptual visuals and empirical results.'}</p></div><div class="page-hero-art"><div class="sigil">≠</div></div></div></section>
<section><div class="wrap content-grid"><article class="prose">
<div class="legal-banner">{'Version publique v2.0.0 · En vigueur le 20 juillet 2026 · Cette page décrit le site public; les services clients exigent une gouvernance contractuelle distincte.' if fr else 'Public version v2.0.0 · Effective 20 July 2026 · This page describes the public site; client services require separate contractual governance.'}</div>
<h2>{'1. Classes de contenu' if fr else '1. Content classes'}</h2><p>{'Le site sépare les faits externes datés, l’architecture GoalOS, les hypothèses de gestion, les scénarios financiers, les résultats empiriques, les démonstrations logicielles et les visuels conceptuels. Une classe ne doit pas hériter de l’autorité d’une autre.' if fr else 'The site separates dated external facts, GoalOS architecture, management hypotheses, financial scenarios, empirical results, software demonstrations and conceptual visuals. One class must not inherit the authority of another.'}</p>
<h2>{'2. Sources externes' if fr else '2. External sources'}</h2><p>{'Les faits temporels sont accompagnés d’une date de référence et de liens vers des sources primaires lorsque possible. Une source externe ne constitue pas un endossement de MONTREAL.AI ou de GoalOS. Les faits peuvent changer après la date de référence.' if fr else 'Time-sensitive facts carry an as-of date and links to primary sources where possible. An external source does not endorse MONTREAL.AI or GoalOS. Facts may change after the as-of date.'}</p>
<h2>{'3. Hypothèses et scénarios' if fr else '3. Hypotheses and scenarios'}</h2><p>{'Les prix, marges, scores stratégiques, tailles de marché, trajectoires de revenus, valorisations et allocations de trésorerie sont des hypothèses de gestion modifiables, sauf lorsqu’un document identifie expressément une observation réelle avec sa preuve. Ils ne constituent ni prévision, ni rendement promis, ni conseil financier.' if fr else 'Prices, margins, strategic scores, market sizes, revenue paths, valuations and treasury allocations are editable management hypotheses unless a document expressly identifies a real observation and its evidence. They are not forecasts, promised returns or financial advice.'}</p>
<h2>{'4. Visuels conceptuels et génération assistée' if fr else '4. Conceptual and AI-assisted visuals'}</h2><p>{'Les images de marque, villes futures, graphes stylisés, sceaux, portails, infrastructures et tableaux de bord peuvent être conceptuels ou créés avec assistance algorithmique. Ils communiquent une architecture et une ambition; ils ne représentent pas automatiquement un système déployé, un résultat client, une métrique observée ou une capacité déjà atteinte.' if fr else 'Brand images, future cities, stylized graphs, seals, portals, infrastructure and dashboards may be conceptual or algorithmically assisted. They communicate architecture and ambition; they do not automatically represent a deployed system, customer result, observed metric or achieved capability.'}</p>
<h2>{'5. Résultats et témoignages' if fr else '5. Results and testimonials'}</h2><p>{'Aucun résultat client, témoignage, revenu, économie, amélioration ou répétition ne doit être publié sans autorisation appropriée, portée définie, preuve attribuable et limites visibles. Le registre public de preuve commence à zéro et progresse seulement lorsque les reçus existent.' if fr else 'No customer result, testimonial, revenue, saving, improvement or repeat outcome should be published without appropriate permission, defined scope, attributable evidence and visible limitations. The public proof register begins at zero and advances only when receipts exist.'}</p>
<h2>{'6. Données personnelles et confidentielles' if fr else '6. Personal and confidential data'}</h2><p>{'Le site public n’est pas un canal approuvé pour des renseignements personnels, confidentiels, privilégiés, réglementés ou contrôlés. Toute mission d’entreprise doit définir finalités, rôles, accès, rétention, sécurité, transferts, sous-traitants, incidents et suppression dans des accords distincts.' if fr else 'The public site is not an approved channel for personal, confidential, privileged, regulated or controlled information. Each enterprise mission must define purposes, roles, access, retention, security, transfers, subprocessors, incidents and deletion in separate agreements.'}</p>
<h2>{'7. Correction et retrait' if fr else '7. Correction and removal'}</h2><p>{'MONTREAL.AI peut corriger, qualifier, archiver ou retirer un contenu devenu inexact, obsolète, contesté, non autorisé ou incompatible avec la frontière des affirmations. La correction ne doit pas effacer silencieusement la provenance d’une racine ou d’un artefact lorsqu’un historique est requis.' if fr else 'MONTREAL.AI may correct, qualify, archive or remove content that becomes inaccurate, stale, disputed, unauthorized or inconsistent with the claim boundary. Correction should not silently erase the provenance of a root or artifact where history is required.'}</p>
</article><aside class="sidebar-card"><h3>{'Gouvernance publique' if fr else 'Public governance'}</h3><a href="{rel(depth,'/goalos-legal/' if fr else '/en/goalos-legal/')}">{'Centre juridique' if fr else 'Legal centre'}</a><a href="{rel(depth,'/goalos-legal/claim-boundary/' if fr else '/en/goalos-legal/claim-boundary/')}">{'Frontière des affirmations' if fr else 'Claim Boundary'}</a><a href="{rel(depth,'/goalos-legal/ai-transparency/' if fr else '/en/goalos-legal/ai-transparency/')}">{'Transparence IA' if fr else 'AI Transparency'}</a><a href="{rel(depth,'/research/' if fr else '/en/research/')}">{'Registre des sources' if fr else 'Source Register'}</a></aside></div></section>'''
 f=ROOT/path.strip('/')/'index.html';f.parent.mkdir(parents=True,exist_ok=True)
 f.write_text(page_doc(lang,path,'Données, visuels et provenance · GoalOS' if fr else 'Data, Visuals and Provenance · GoalOS','Gouvernance des sources, scénarios, résultats et visuels conceptuels.' if fr else 'Governance of sources, scenarios, results and conceptual visuals.',body,depth,'legal-page'),encoding='utf-8')

def patch_legal():
 publication_page('fr'); publication_page('en')
 for f in list((ROOT/'goalos-legal').rglob('index.html'))+list((ROOT/'en/goalos-legal').rglob('index.html')):
  txt=f.read_text(encoding='utf-8')
  txt=txt.replace('Version publique v1.0.0','Version publique v2.0.0').replace('Public version v1.0.0','Public version v2.0.0')
  soup=BeautifulSoup(txt,'html.parser')
  lang='en' if 'en' in f.parts else 'fr'; depth=len(f.relative_to(ROOT).parts)-1
  aside=soup.select_one('.sidebar-card')
  if aside and not any('publication-data' in (a.get('href') or '') for a in aside.find_all('a')):
   href=rel(depth,'/goalos-legal/publication-data/' if lang=='fr' else '/en/goalos-legal/publication-data/')
   a=soup.new_tag('a',href=href);a.string='Données et provenance' if lang=='fr' else 'Data and provenance';aside.append(a)
  # legal centre card
  if f.relative_to(ROOT).as_posix() in ('goalos-legal/index.html','en/goalos-legal/index.html'):
   container=soup.select_one('.grid') or soup.select_one('.download-list') or soup.select_one('.prose')
   if container and not any('publication-data' in (a.get('href') or '') for a in soup.find_all('a')):
    href=rel(depth,'/goalos-legal/publication-data/' if lang=='fr' else '/en/goalos-legal/publication-data/')
    frag=BeautifulSoup(f'<a class="card" href="{href}"><div class="icon">≠</div><h3>{"Données et provenance" if lang=="fr" else "Data and provenance"}</h3><p>{"Sources, hypothèses, scénarios, résultats et visuels conceptuels." if lang=="fr" else "Sources, hypotheses, scenarios, results and conceptual visuals."}</p></a>','html.parser')
    container.append(frag)
  f.write_text(str(soup),encoding='utf-8')

def update_research_pages():
 for lang in ('fr','en'):
  fr=lang=='fr'; path='/research/' if fr else '/en/research/'; depth=1 if fr else 2
  cards=''.join(f'''<article class="source-card"><div class="source-meta"><span>{s['date']}</span><span>{s['publisher']}</span></div><h3>{s['title_fr' if fr else 'title_en']}</h3><p>{s['note_fr' if fr else 'note_en']}</p><a href="{s['url']}" target="_blank" rel="noopener noreferrer">{'Source primaire' if fr else 'Primary source'} ↗</a></article>''' for s in SOURCES)
  body=f'''<section class="page-hero"><div class="wrap page-hero-grid"><div><div class="eyebrow">{'Contexte daté · frontières visibles' if fr else 'Dated context · visible boundaries'}</div><h1>{'LE CONTEXTE CHANGE. LES PREUVES RESTENT DATÉES.' if fr else 'THE CONTEXT CHANGES. EVIDENCE STAYS DATED.'}</h1><p class="lead">{'Un registre public des sources utilisées pour situer GoalOS — sans transformer les travaux externes en endossement, ni leurs résultats en preuve de GoalOS.' if fr else 'A public register of sources used to situate GoalOS—without turning external work into endorsement or its results into evidence for GoalOS.'}</p></div><div class="page-hero-art"><div class="sigil">R</div></div></div></section>
<section><div class="wrap"><div class="section-head"><div class="eyebrow">{'Au 20 juillet 2026' if fr else 'As of 20 July 2026'}</div><h2>{'Développements pertinents' if fr else 'Relevant developments'}</h2><p>{'Les résumés sont courts, paraphrasés et accompagnés d’une limite d’interprétation. Les prix et priorités GoalOS restent des hypothèses de gestion.' if fr else 'Summaries are brief, paraphrased and paired with an interpretation boundary. GoalOS pricing and priorities remain management hypotheses.'}</p></div><div class="source-grid">{cards}</div></div></section>
<section class="section-tint"><div class="wrap"><div class="section-head"><div class="eyebrow">GoalOS Research</div><h2>{'Fondations internes' if fr else 'Internal foundations'}</h2></div><div class="download-list"><div class="download-item"><div><b>Merkle Roots for the Validated Skill Graph</b><span>{'La racine engage l’état; Chronique confère l’autorité.' if fr else 'The root commits state; Chronicle grants authority.'}</span></div><a href="{rel(depth,'/goalos-documents/research/Merkle_Roots_for_the_Validated_Skill_Graph_v114.pdf')}">PDF</a></div><div class="download-item"><div><b>Private On-Chain Validated Skill Graph</b><span>{'Identité directe, capsules chiffrées, preuves de politique et mémoire bornée.' if fr else 'Direct identity, encrypted capsules, policy proofs and bounded memory.'}</span></div><a href="{rel(depth,'/goalos-documents/research/GoalOS_Private_OnChain_Validated_Skill_Graph_v97_4.pdf')}">PDF</a></div><div class="download-item"><div><b>{'Registre source machine' if fr else 'Machine-readable source register'}</b><span>JSON · v2.0.0 · {DATE}</span></div><a href="{rel(depth,'/source-register.json')}">JSON</a></div><div class="download-item"><div><b>{'État de preuve public' if fr else 'Public proof status'}</b><span>{'Architecture et reçus commerciaux séparés.' if fr else 'Architecture and commercial receipts separated.'}</span></div><a href="{rel(depth,'/proof-status.json')}">JSON</a></div></div></div></section>
<section><div class="wrap content-grid"><article class="prose"><h2>{'Frontière d’interprétation' if fr else 'Interpretation boundary'}</h2><p>{'Ces sources démontrent que les agents, l’évaluation, l’évolution de compétences, la gouvernance, la transparence et l’infrastructure progressent rapidement. Elles ne démontrent pas que GoalOS a acquis des clients, créé des résultats, atteint une valorisation, réalisé une intelligence générale ou prouvé une amélioration récursive générale.' if fr else 'These sources show rapid progress in agents, evaluation, skill evolution, governance, transparency and infrastructure. They do not show that GoalOS has acquired customers, created outcomes, reached a valuation, achieved general intelligence or proven general recursive improvement.'}</p><h2>{'Discipline de mise à jour' if fr else 'Update discipline'}</h2><p>{'Tout fait temporel important doit être revu à la date de publication. Les changements sont qualifiés par date, source et portée; une source retirée ou corrigée doit entraîner la mise à jour du registre.' if fr else 'Every important time-sensitive fact must be reviewed at publication. Changes are qualified by date, source and scope; a withdrawn or corrected source should trigger an update to the register.'}</p></article><aside class="sidebar-card"><h3>{'Frontières' if fr else 'Boundaries'}</h3><a href="{rel(depth,'/goalos-legal/claim-boundary/' if fr else '/en/goalos-legal/claim-boundary/')}">{'Affirmations' if fr else 'Claims'}</a><a href="{rel(depth,'/goalos-legal/publication-data/' if fr else '/en/goalos-legal/publication-data/')}">{'Données et visuels' if fr else 'Data and visuals'}</a><a href="{rel(depth,'/goalos-legal/ai-transparency/' if fr else '/en/goalos-legal/ai-transparency/')}">{'Transparence IA' if fr else 'AI transparency'}</a></aside></div></section>'''
  (ROOT/path.strip('/')/'index.html').write_text(page_doc(lang,path,'Recherche GoalOS — Sources, protocoles et frontières' if fr else 'GoalOS Research — Sources, Protocols and Boundaries','Sources primaires datées et limites d’interprétation.' if fr else 'Dated primary sources and interpretation boundaries.',body,depth,'research-page'),encoding='utf-8')
