from pathlib import Path
import base64, json, hashlib, os, re, shutil, zipfile, textwrap, datetime

ROOT=Path('/mnt/data/GoalOS_Singularity_Navigator_Omega_AGI_CLUB_GITHUB_PAGES_FINAL_v3_0_0_SN5_2026-07-26')
SITE=ROOT/'goalos-singularity-navigator-omega-agi-club-owner-access'
INDEX=SITE/'index.html'
SN3=Path('/mnt/data/sn5_work/base/goalos-singularity-navigator-omega-agi-club-owner-access/index.html')
DATE='2026-07-26'
VERSION='v3.0.0-SN5'
PRODUCT='GoalOS Singularity Navigator Ω'
LEGAL_VERSION='SN5-L1.0'

# Reset working site from the validated SN3 base, then restore SN5 assets.
if ROOT.exists(): shutil.rmtree(ROOT)
SITE.mkdir(parents=True)
base_dir=SN3.parent
for src in base_dir.rglob('*'):
    rel=src.relative_to(base_dir)
    dst=SITE/rel
    if src.is_dir(): dst.mkdir(parents=True,exist_ok=True)
    else:
        dst.parent.mkdir(parents=True,exist_ok=True)
        shutil.copy2(src,dst)

# Controlled visual assets
assets=SITE/'assets'; assets.mkdir(exist_ok=True)
img_candidates=[
    Path('/mnt/data/a_dramatic_ultra_luxurious_sci_fi_infographic_sty.png'),
    Path('/mnt/data/luxurious_cosmic_emblem_with_omega_symbol.png'),
    Path('/mnt/data/luxury_masterclass_cover_design.png'),
]
from PIL import Image
for i,p in enumerate(img_candidates):
    if p.exists():
        dst=assets/(['singularity_apex.webp','sovereign_seal.webp','masterclass_cover.webp'][i])
        im=Image.open(p).convert('RGB')
        maxw=1920 if i==0 else 1200
        if im.width>maxw:
            im=im.resize((maxw,round(im.height*maxw/im.width)),Image.Resampling.LANCZOS)
        im.save(dst,'WEBP',quality=84,method=6)

# Research assets
research=SITE/'research'; research.mkdir(exist_ok=True)
founding=Path('/mnt/data/GoalOS_Singularity_Navigation_Omega_Tools_to_Ride_the_Singularity_by_Vincent_Boucher_v2_0_0.pdf')
masterclass=Path('/mnt/data/GoalOS_Singularity_Navigator_Omega_MasterClass_Tools_to_Ride_the_Singularity_by_Vincent_Boucher_v3_0_0_SN5.pdf')
if founding.exists(): shutil.copy2(founding,research/founding.name)
if masterclass.exists(): shutil.copy2(masterclass,research/masterclass.name)

s=INDEX.read_text(encoding='utf-8')
# Global version and metadata updates
s=s.replace('v2.0.0-SN3',VERSION)
s=s.replace('goalosSingularityNavigatorDirectOwnerReceiptV2','goalosSingularityNavigatorDirectOwnerReceiptV3')
s=s.replace('GoalOS_Singularity_Navigator_Omega_Standalone_v2_0_0_SN2.html','GoalOS_Singularity_Navigator_Omega_AGI_CLUB_GITHUB_PAGES_v3_0_0_SN5.html')
s=s.replace("schema:'goalos-agi-club-owner-access/2.0'", "schema:'goalos-agi-club-owner-access/3.0'")
# ENS official deployment compatibility: current Name Wrapper first; preserve the earlier DAO-authorized wrapper for existing names.
s=s.replace("wrappers:[{address:'0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401',label:'Official ENS Name Wrapper · Ethereum Mainnet'}]", "wrappers:[{address:'0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401',label:'Current official ENS Name Wrapper · Ethereum Mainnet'},{address:'0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401',label:'Legacy official ENS Name Wrapper · Ethereum Mainnet (EP3.5)'}]")
s=s.replace('<html lang="en" data-theme="cosmic">','<html lang="fr-CA" data-theme="cosmic" data-default-legal-language="fr">')
s=s.replace('<title>GoalOS Singularity Navigator Ω · AGI Club</title>', '<title>GoalOS Singularity Navigator Ω · AGI Club Institution · v3.0.0-SN5</title>')
s=s.replace('content="GoalOS Singularity Navigator Ω', 'content="GoalOS Singularity Navigator Ω — AGI Club GitHub Pages Institution v3.0.0-SN5')

# Add richer metadata before </head>.
metadata='''\n<meta name="application-name" content="GoalOS Singularity Navigator Ω">
<meta name="author" content="MONTREAL.AI">
<meta name="robots" content="index,follow,max-image-preview:large">
<meta name="theme-color" content="#061226">
<meta property="og:type" content="website">
<meta property="og:title" content="GoalOS Singularity Navigator Ω — AGI Club Institution">
<meta property="og:description" content="Detect what changed. Prove what matters. Deploy only what passes. Compound only what survives reality.">
<meta property="og:image" content="assets/singularity_apex.webp">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="GoalOS Singularity Navigator Ω">
<meta name="twitter:description" content="The AGI Club institution for navigating accelerating capability change with bounded authority and proof.">
<meta name="twitter:image" content="assets/singularity_apex.webp">
'''
s=s.replace('</head>',metadata+'</head>',1)

# Add SN5 CSS before original </style>.
sn5_css=r'''
/* === GoalOS Singularity Navigator Ω · SN5 Apex Institutional Layer === */
:root{--sn5-ivory:#f6f0e4;--sn5-gold:#efc86f;--sn5-gold2:#a9741e;--sn5-purple:#8f5cff;--sn5-cyan:#66e2ff;--sn5-ink:#050b15;--sn5-navy:#06162d}
.hero{min-height:720px;isolation:isolate;overflow:hidden}
.hero-bg{background:
 radial-gradient(circle at 67% 46%,rgba(255,213,115,.15),transparent 23%),
 linear-gradient(90deg,rgba(2,7,16,.97) 0%,rgba(3,10,22,.83) 44%,rgba(2,8,18,.24) 73%,rgba(2,7,15,.8) 100%),
 url('assets/singularity_apex.webp') center/cover no-repeat!important;filter:saturate(1.12) contrast(1.06)}
.hero:before{content:"";position:absolute;inset:-35%;z-index:-1;background:conic-gradient(from 180deg at 66% 48%,transparent,rgba(241,189,73,.16),transparent 22%,rgba(116,63,219,.14),transparent 50%);animation:sn5Orbit 24s linear infinite;pointer-events:none}
.hero:after{content:"";position:absolute;inset:0;z-index:-1;background-image:radial-gradient(circle,rgba(255,226,153,.55) 0 1px,transparent 1.5px);background-size:42px 42px;mask-image:linear-gradient(90deg,transparent 25%,#000 64%,transparent);opacity:.18;animation:sn5Drift 18s linear infinite}
@keyframes sn5Orbit{to{transform:rotate(360deg)}}@keyframes sn5Drift{to{background-position:84px -42px}}
.hero-content{max-width:850px}.hero h1{font-size:clamp(3.4rem,6vw,7rem);line-height:.93;letter-spacing:-.045em}.hero h1 span{background:linear-gradient(120deg,#fff3cb,#e4ad44 35%,#fff0b2 62%,#9c6d1e);-webkit-background-clip:text;color:transparent;text-shadow:0 0 48px rgba(239,190,76,.18)}
.hero-sub{font-size:clamp(1.25rem,2.4vw,2.05rem);letter-spacing:.12em;text-transform:uppercase}.hero-doctrine span{box-shadow:inset 0 0 20px rgba(243,194,85,.08)}
.sn5-disclosure{display:flex;gap:10px;align-items:flex-start;padding:13px 16px;margin:0 0 20px;border:1px solid rgba(239,200,111,.35);border-radius:14px;background:linear-gradient(90deg,rgba(5,19,39,.9),rgba(12,13,31,.75));font-size:.82rem;color:var(--muted)}.sn5-disclosure b{color:var(--gold);white-space:nowrap}
.sn5-apex-grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.sn5-command{grid-column:span 8}.sn5-aside{grid-column:span 4}.sn5-full{grid-column:1/-1}
.sn5-kpi-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.sn5-kpi{padding:16px;border-radius:14px;border:1px solid var(--line);background:linear-gradient(145deg,rgba(13,28,50,.94),rgba(5,12,25,.96))}.sn5-kpi b{font-family:var(--serif);font-size:1.7rem;color:var(--gold);display:block}.sn5-kpi span{font-size:.72rem;letter-spacing:.09em;text-transform:uppercase;color:var(--muted)}
.sn5-decision-band{display:grid;grid-template-columns:1.3fr repeat(4,1fr);gap:1px;border:1px solid rgba(239,200,111,.42);background:rgba(239,200,111,.3);border-radius:16px;overflow:hidden}.sn5-decision-band>div{padding:16px;background:#07162a}.sn5-decision-band strong{font-family:var(--serif);font-size:1.25rem;color:var(--ivory);display:block}.sn5-decision-band small{color:var(--muted)}
.sn5-triad{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.sn5-triad article{position:relative;padding:20px;border-radius:17px;border:1px solid rgba(239,200,111,.3);background:linear-gradient(145deg,rgba(13,29,52,.96),rgba(8,13,28,.96));overflow:hidden}.sn5-triad article:after{content:"";position:absolute;width:140px;height:140px;border:1px solid rgba(239,200,111,.17);border-radius:50%;right:-60px;top:-70px}.sn5-triad em{font-style:normal;font-size:.7rem;letter-spacing:.16em;color:var(--gold);text-transform:uppercase}.sn5-triad h3{margin:7px 0}.sn5-triad p{min-height:60px}
.sn5-portfolio{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.sn5-proposal{padding:18px;border:1px solid var(--line);border-radius:16px;background:linear-gradient(150deg,rgba(15,30,54,.97),rgba(6,13,26,.97))}.sn5-proposal.champion{border-color:var(--gold);box-shadow:0 0 0 1px rgba(239,200,111,.25),0 18px 60px rgba(0,0,0,.24)}.sn5-proposal .rank{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:var(--gold);color:#0a1020;font-weight:900}.sn5-proposal h3{margin:12px 0 4px}.sn5-proposal .scores{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.sn5-proposal .scores span{font-size:.7rem;padding:5px 8px;border-radius:999px;border:1px solid var(--line);color:var(--muted)}
.sn5-vop{display:grid;gap:9px}.sn5-vop-row{display:grid;grid-template-columns:40px 1fr 70px;gap:10px;align-items:center;padding:11px;border-radius:12px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.06)}.sn5-vop-row i{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;font-style:normal;background:rgba(239,200,111,.12);color:var(--gold);font-weight:800}.sn5-vop-row em{text-align:right;font-style:normal;color:var(--gold);font-weight:800}
.sn5-lab-grid{display:grid;grid-template-columns:360px 1fr;gap:18px}.sn5-lab-controls{position:sticky;top:94px;align-self:start}.sn5-counter-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.sn5-counter{padding:18px;border:1px solid var(--line);border-radius:16px;background:rgba(7,18,35,.8)}.sn5-counter b{font-family:var(--serif);font-size:1.2rem;color:var(--gold);display:block}.sn5-counter span{font-size:.78rem;color:var(--muted)}
.sn5-stability{height:12px;border-radius:999px;background:#121d2e;overflow:hidden}.sn5-stability i{display:block;height:100%;background:linear-gradient(90deg,#c4435d,#efbd55,#68d78a);border-radius:999px}
.sn5-vault-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.sn5-codebox{font-family:var(--mono);font-size:.75rem;overflow:auto;max-height:340px;padding:16px;border-radius:13px;background:#030914;border:1px solid rgba(239,200,111,.23);color:#b9d9ff;white-space:pre-wrap;word-break:break-all}.sn5-ledger{display:grid;gap:8px}.sn5-ledger-row{display:grid;grid-template-columns:120px 1fr 92px;gap:10px;align-items:center;padding:11px;border-radius:12px;border:1px solid var(--line);background:rgba(255,255,255,.02)}
.sn5-master-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:18px}.sn5-library{display:grid;gap:12px}.sn5-resource{display:grid;grid-template-columns:74px 1fr auto;gap:15px;align-items:center;padding:16px;border:1px solid var(--line);border-radius:16px;background:rgba(6,16,31,.9)}.sn5-resource .cover{height:86px;border-radius:9px;background:linear-gradient(150deg,#f7eedf,#d4a64b);display:grid;place-items:center;color:#061329;font-family:var(--serif);font-size:1.8rem}.sn5-resource h3{margin:0 0 4px}
.sn5-legal-lang{display:flex;gap:8px;margin:0 0 14px}.sn5-legal-lang button{padding:8px 12px;border-radius:999px;border:1px solid var(--line);background:transparent;color:var(--muted);cursor:pointer}.sn5-legal-lang button.active{background:var(--gold);color:#071126;border-color:var(--gold)}.legal-pane[data-lang]{display:none}.legal-pane[data-lang].active{display:block}.legal-pane h4{margin-top:20px;color:var(--gold)}.legal-pane .legal-columns{display:grid;grid-template-columns:1fr 1fr;gap:14px}.legal-pane .legal-box{padding:15px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.02)}
.sn5-language-btn{font-weight:800;min-width:42px}.sn5-public-label{display:inline-flex;align-items:center;gap:7px;font-size:.68rem;letter-spacing:.12em;text-transform:uppercase;padding:6px 9px;border-radius:999px;border:1px solid rgba(107,220,255,.32);color:#9ae5ff;background:rgba(26,92,116,.12)}
body[data-theme="ivory"] .sn5-kpi,body[data-theme="ivory"] .sn5-proposal,body[data-theme="ivory"] .sn5-triad article,body[data-theme="ivory"] .sn5-counter,body[data-theme="ivory"] .sn5-resource{background:rgba(255,255,255,.87)}
@media(max-width:1100px){.sn5-command,.sn5-aside{grid-column:1/-1}.sn5-kpi-grid{grid-template-columns:repeat(3,1fr)}.sn5-counter-grid{grid-template-columns:repeat(2,1fr)}.sn5-lab-grid,.sn5-master-grid{grid-template-columns:1fr}.sn5-lab-controls{position:static}}
@media(max-width:720px){body.agc-locked{overflow:hidden}#agiClubAccessGate{overflow-x:hidden}.sn5-disclosure{display:block;overflow-wrap:anywhere}.sn5-disclosure b{display:block;white-space:normal;margin-bottom:6px}.agent-line{min-width:0;overflow-wrap:anywhere}.sn5-triad,.sn5-portfolio,.sn5-vault-grid,.sn5-kpi-grid,.sn5-counter-grid{grid-template-columns:1fr}.sn5-decision-band{grid-template-columns:1fr}.sn5-resource{grid-template-columns:56px 1fr}.sn5-resource .btn{grid-column:1/-1}.legal-pane .legal-columns{grid-template-columns:1fr}.hero{min-height:780px}.hero:before{display:none}}
@media(prefers-reduced-motion:reduce){.hero:before,.hero:after{animation:none!important}.hero:after{display:none}}
@media print{.sn5-no-print,.topbar,.nav,.top-actions,.agc-access{display:none!important}.sn5-apex-grid{display:block}.sn5-command,.sn5-aside{margin-bottom:12px}.view{display:none!important}.view.active{display:block!important}}
'''
s=s.replace('</style>',sn5_css+'\n</style>',1)

# Upgrade gate and hero metrics/text; preserve all existing IDs.
s=s.replace('Temporary current-owner admission','Admission temporaire du propriétaire direct actuel')
s=s.replace('AGI Club Owner Access</h2>','Accès propriétaire AGI Club</h2>')
s=s.replace('Ordinary use is reserved', 'L’usage ordinaire est réservé')
s=s.replace('Current direct AGI Club owners','Propriétaires directs actuels de l’AGI Club')
s=s.replace('<div class="agc-stats"><div class="agc-stat"><b>9</b><span>Permanent tools</span></div><div class="agc-stat"><b>8</b><span>Scenario architectures</span></div><div class="agc-stat"><b>15</b><span>Bounded AGI Jobs</span></div><div class="agc-stat"><b>12</b><span>Proof receipts</span></div></div>',
'''<div class="agc-stats"><div class="agc-stat"><b>12</b><span>Institutional agents</span></div><div class="agc-stat"><b>12</b><span>Scenario architectures</span></div><div class="agc-stat"><b>21</b><span>Bounded AGI Jobs</span></div><div class="agc-stat"><b>15</b><span>Proof receipts</span></div></div>''')
s=s.replace('<strong>9</strong><span>navigation tools</span>','<strong>12</strong><span>institutional agents</span>')
s=s.replace('<strong id="heroScenarios">8</strong>','<strong id="heroScenarios">12</strong>')
s=s.replace('One natural-language objective becomes a governed mission, competing architectures, bounded AGI Jobs, explicit Proof Debt and a concrete 30/90/365-day command plan.', 'One natural-language objective becomes a governed portfolio of competing architectures, counterfactual worlds, bounded AGI Jobs, explicit Proof Debt, Value-of-Proof priorities and an executable 72-hour / 30 / 90 / 365-day command sequence.')

# Add disclosure strip after signal strip.
needle='<div class="section-head"><div><div class="kicker">Constitute</div>'
disclosure='''<div class="sn5-disclosure"><b>ALGORITHMIC INSTITUTION · INSTITUTION ALGORITHMIQUE</b><span>Scenarios, scores, agent deliberations and recommendations are generated locally by deterministic software. They are research and mission-design outputs—not external authority, professional advice, approval, funding, or proof that an outcome occurred.</span></div>'''
s=s.replace(needle,disclosure+needle,1)

# Enhance command inputs with adaptive budget and mission consequence controls.
old='<select id="deliberationBudget"><option value="1024">1,024 stress worlds</option><option value="4096" selected>4,096 stress worlds</option><option value="16384">16,384 stress worlds</option></select>'
new='<select id="deliberationBudget"><option value="0" selected>Adaptive — GoalOS decides</option><option value="1024">1,024 stress worlds / scenario</option><option value="4096">4,096 stress worlds / scenario</option><option value="16384">16,384 stress worlds / scenario</option></select>'
s=s.replace(old,new,1)
insert_after='''<div class="field" style="margin-top:12px"><label>Primary mandate</label>'''
extra_fields='''<div class="fields-compact" style="margin-top:12px"><div class="field"><label for="decisionStakes">Decision consequence</label><select id="decisionStakes"><option value="35">Exploratory</option><option value="60" selected>Material</option><option value="82">Consequential</option><option value="96">Systemic / irreversible</option></select></div><div class="field"><label for="dataSensitivity">Data sensitivity</label><select id="dataSensitivity"><option value="20">Public / synthetic</option><option value="48" selected>Internal</option><option value="72">Confidential</option><option value="94">Regulated / highly sensitive</option></select></div><div class="field"><label for="deploymentPosture">Deployment posture</label><select id="deploymentPosture"><option value="reference">Reference institution</option><option value="advisory" selected>Private advisory workspace</option><option value="assisted">Assisted execution</option><option value="governed">Governed transaction</option><option value="infrastructure">Strategic infrastructure</option></select></div></div>'''
s=s.replace(insert_after,extra_fields+insert_after,1)

# Add routes to navigation and language button.
s=s.replace('<button data-route="brief">Apex Brief</button>', '<button data-route="brief">Apex Brief</button><button data-route="opportunity">Opportunity Engine</button><button data-route="lab">Scenario Lab</button>')
s=s.replace('<button data-route="office">Singularity Office</button><button data-route="sources">Sources</button>', '<button data-route="office">Singularity Office</button><button data-route="vault">Evidence Vault</button><button data-route="masterclass">MasterClass</button><button data-route="sources">Sources</button>')
s=s.replace('<button class="iconbtn" id="themeBtn"', '<button class="iconbtn sn5-language-btn" id="languageBtn" aria-label="Language / Langue" title="Language / Langue">FR</button><button class="iconbtn" id="themeBtn"',1)

# New views inserted before Legal Center.
new_views=r'''
<section class="view" id="view-opportunity">
 <div class="section-head"><div><div class="kicker">Apex Opportunity Engine</div><h2>The best move, the next move and the option to preserve</h2></div><p>GoalOS does not collapse every objective into one recommendation. It proposes an immediate architecture, a contingent successor and a reserve option—each with evidence, authority and switch conditions.</p></div>
 <div class="sn5-apex-grid">
  <div class="card sn5-command"><div class="card-top"><div><h3>Institutional decision surface</h3><p id="sn5DecisionThesis">Constitute a mission to generate the decision portfolio.</p></div><span class="sn5-public-label">Generated locally · Généré localement</span></div><div class="sn5-decision-band" id="sn5DecisionBand"><div><strong>Awaiting mission</strong><small>Institutional verdict</small></div><div><strong>—</strong><small>Champion</small></div><div><strong>—</strong><small>Stability</small></div><div><strong>—</strong><small>Proof posture</small></div><div><strong>—</strong><small>Exposure ratio</small></div></div></div>
  <aside class="card sn5-aside"><h3>Anti-recommendation</h3><p id="sn5AntiRecommendation">GoalOS will state what must not be done, even when it looks attractive.</p><div class="alert danger" id="sn5NoGo"><h3>No-go condition</h3><p>Awaiting a constituted objective.</p></div></aside>
  <div class="sn5-full"><div class="sn5-triad" id="sn5MandateTriad"><article><em>Preserve</em><h3>Protect what must remain true</h3><p>Institutional identity, rights, strategic control, human agency and continuity.</p></article><article><em>Build</em><h3>Create the capability frontier</h3><p>Products, markets, evidence systems, teams, capital and infrastructure.</p></article><article><em>Become</em><h3>Reconstitute for the next regime</h3><p>Roles, operating model, authority and productive capacity adapted to the new frontier.</p></article></div></div>
 </div>
 <div class="section-head"><div><div class="kicker">Three-horizon portfolio</div><h2>Immediate · successor · reserve</h2></div><p>Each proposal is admissible only inside its proof and authority envelope.</p></div><div class="sn5-portfolio" id="sn5ProposalPortfolio"></div>
 <div class="grid two" style="margin-top:18px"><div class="card"><h3>Value-of-Proof queue</h3><p>Evidence ranked by its probability of changing the decision.</p><div class="sn5-vop" id="sn5Vop"></div></div><div class="card"><h3>Switch and stop constitution</h3><div id="sn5SwitchStop"></div></div></div>
</section>
<section class="view" id="view-lab">
 <div class="section-head"><div><div class="kicker">Counterfactual Scenario Laboratory</div><h2>Change the world. Observe the architecture.</h2></div><p>Stress the recommendation against capability shocks, evidence latency, capital urgency, authority risk and irreversibility. The purpose is not prediction; it is low-regret institutional preparedness.</p></div>
 <div class="sn5-lab-grid"><aside class="card sn5-lab-controls"><h3>Counterfactual controls</h3>
  <div class="range-row"><label>Capability acceleration</label><input id="cfAcceleration" type="range" min="0" max="100" value="72"><span class="range-val">72</span></div>
  <div class="range-row"><label>Evidence latency</label><input id="cfEvidenceLatency" type="range" min="0" max="100" value="48"><span class="range-val">48</span></div>
  <div class="range-row"><label>Authority risk</label><input id="cfAuthorityRisk" type="range" min="0" max="100" value="55"><span class="range-val">55</span></div>
  <div class="range-row"><label>Capital urgency</label><input id="cfCapitalUrgency" type="range" min="0" max="100" value="62"><span class="range-val">62</span></div>
  <div class="range-row"><label>Irreversibility</label><input id="cfIrreversibility" type="range" min="0" max="100" value="44"><span class="range-val">44</span></div>
  <div class="range-row"><label>Cost collapse</label><input id="cfCostCollapse" type="range" min="0" max="100" value="76"><span class="range-val">76</span></div>
  <button class="btn primary" id="runCounterfactual" style="width:100%;margin-top:14px">Regenerate counterfactual frontier</button></aside>
  <div><div class="sn5-counter-grid" id="sn5CounterKpis"></div><div class="card" style="margin-top:16px"><div class="card-top"><div><h3>Recommendation stability</h3><p>How often the champion survives plausible counterfactual worlds.</p></div><b id="sn5StabilityLabel">—</b></div><div class="sn5-stability"><i id="sn5StabilityBar"></i></div><div id="sn5CounterNarrative" style="margin-top:16px"></div></div><div class="card" style="margin-top:16px"><h3>Counterfactual architecture order</h3><div id="sn5CounterRanking"></div></div></div>
 </div>
</section>
<section class="view" id="view-vault">
 <div class="section-head"><div><div class="kicker">Evidence Vault</div><h2>Portable evidence. Local custody. Explicit retention.</h2></div><p>Generate a deterministic proof bundle, hash it with SHA-256, optionally encrypt it with AES-GCM and keep custody in the user’s environment. No secret is transmitted to MONTREAL.AI by this static release.</p></div>
 <div class="sn5-vault-grid"><div class="card"><h3>Proof bundle</h3><p>Mission state, candidate frontier, receipts, jobs, Chronicle, source snapshot and operating boundary.</p><div class="field"><label for="vaultPassphrase">Optional export passphrase</label><input id="vaultPassphrase" type="password" autocomplete="new-password" placeholder="Used locally; never stored"></div><div class="owner-actions"><button class="btn primary" id="generateProofBundle">Generate & hash</button><button class="btn" id="exportEncryptedBundle">Encrypt & download</button><button class="btn" id="exportPlainBundle">Download JSON</button></div><div class="sn5-codebox" id="sn5BundleDigest">No proof bundle generated.</div></div>
  <div class="card"><h3>Restore or purge</h3><p>Restore a locally exported bundle or erase stored mission state. Access eligibility is always revalidated separately.</p><div class="field"><label for="vaultImportFile">Bundle file</label><input id="vaultImportFile" type="file" accept="application/json,.json,.goalos"></div><div class="field" style="margin-top:10px"><label for="vaultImportPassphrase">Passphrase, when encrypted</label><input id="vaultImportPassphrase" type="password" autocomplete="current-password"></div><div class="owner-actions"><button class="btn" id="importVaultBundle">Restore bundle</button><button class="btn danger" id="purgeMissionState">Purge mission state</button></div><div class="legal-note"><b>Retention constitution.</b> Mission state is browser-local. The user controls export, deletion and device custody. Wallet and RPC infrastructure remain third-party systems.</div></div></div>
 <div class="section-head"><div><div class="kicker">Decision ledger</div><h2>What changed, who decided and what may survive</h2></div></div><div class="sn5-ledger" id="sn5DecisionLedger"></div>
</section>
<section class="view" id="view-masterclass">
 <div class="section-head"><div><div class="kicker">Institutional Academy</div><h2>GoalOS Singularity Navigation Ω MasterClass</h2></div><p>A board-to-operator curriculum for detecting capability change, constituting missions, bounding authority, proving outcomes and compounding only verified gains.</p></div>
 <div class="sn5-master-grid"><div class="sn5-library"><article class="sn5-resource"><div class="cover">Ω</div><div><h3>Singularity-Time Navigation Constitution</h3><p>140-page founding paper: formal architecture, frontier adaptation, Proof & Authority, resilience, Chronicle, economics and empirical proof.</p></div><a class="btn" href="research/GoalOS_Singularity_Navigation_Omega_Tools_to_Ride_the_Singularity_by_Vincent_Boucher_v2_0_0.pdf" target="_blank">Open paper</a></article><article class="sn5-resource"><div class="cover">MC</div><div><h3>GoalOS Singularity Navigation Ω MasterClass</h3><p>204-page SN5 Constitutional Operating MasterClass with command surfaces, case studies, activation path, templates and the complete technical reference.</p></div><a class="btn" href="research/GoalOS_Singularity_Navigator_Omega_MasterClass_Tools_to_Ride_the_Singularity_by_Vincent_Boucher_v3_0_0_SN5.pdf" target="_blank">Open MasterClass</a></article><article class="sn5-resource"><div class="cover">SN5</div><div><h3>SN5 Operating Institution</h3><p>The live local command system: Apex Opportunity Engine, counterfactual lab, Mission Foundry, Proof & Authority, Graph, Chronicle and Singularity Office.</p></div><button class="btn" data-route="opportunity">Enter engine</button></article></div>
  <aside class="card"><h3>MasterClass progression</h3><ol class="timeline"><li><b>Orient</b><span>Preserve, build, become.</span></li><li><b>Detect</b><span>Frontier events and institutional exposure.</span></li><li><b>Constitute</b><span>Objective, authority and acceptance.</span></li><li><b>Auction</b><span>Models, agents and architectures.</span></li><li><b>Execute</b><span>Bounded AGI Jobs and typed graphs.</span></li><li><b>Prove</b><span>Evidence, independent validation and acceptance.</span></li><li><b>Admit</b><span>Rights-cleared Chronicle capability.</span></li><li><b>Compound</b><span>Successor improvement and capital-to-capacity.</span></li></ol><div class="law" style="margin-top:16px"><b>Master doctrine</b><p>Detect what changed. Test what matters. Deploy only what passes. Compound only what survives reality.</p></div></aside></div>
</section>
'''
legal_start=s.find('<section class="view" id="view-legal">')
if legal_start<0: raise RuntimeError('legal section not found')
s=s[:legal_start]+new_views+s[legal_start:]

# Replace legal section with bilingual full center.
legal_start=s.find('<section class="view" id="view-legal">')
legal_end=s.find('</section>',legal_start)+len('</section>')
legal_html=r'''
<section class="view" id="view-legal">
 <div class="section-head"><div><div class="kicker">Centre juridique · Legal Center</div><h2>Ambition bounded by truth, authority and mandatory law</h2></div><p>This release minimizes unnecessary regulatory exposure through product boundaries, local processing, explicit transparency and fail-closed controls. It does not promise immunity from law, professional obligations or jurisdiction-specific requirements.</p></div>
 <div class="sn5-legal-lang"><button class="active" data-legal-lang="fr">Français</button><button data-legal-lang="en">English</button></div>
 <div class="legal-nav" id="legalNav"><button class="active" data-legal="boundary">Cadre / Boundary</button><button data-legal="access">Accès AGI Club</button><button data-legal="terms">Conditions</button><button data-legal="privacy">Vie privée</button><button data-legal="security">Sécurité</button><button data-legal="transparency">Transparence IA</button><button data-legal="rights">Droits</button><button data-legal="regulatory">Réglementaire</button></div>
 <div class="card">
  <div class="legal-pane active" id="legal-boundary" data-lang="fr"><h3>Cadre opérationnel</h3><p>GoalOS Singularity Navigator Ω est une institution statique, locale au navigateur, destinée à la recherche, à la simulation, à la priorisation, à la conception de missions, à la gouvernance de la preuve et au suivi institutionnel. Elle ne crée pas, à elle seule, d’autorité juridique, fiscale, fiduciaire, réglementaire, professionnelle ou transactionnelle.</p><div class="legal-columns"><div class="legal-box"><h4>Ce que le système peut faire</h4><ul><li>Générer et comparer des architectures candidates.</li><li>Décomposer un objectif en AGI Jobs bornés.</li><li>Rendre visibles les hypothèses et la dette de preuve.</li><li>Préparer des dossiers, contrôles et voies d’escalade.</li><li>Conserver localement des états et preuves exportables.</li></ul></div><div class="legal-box"><h4>Ce qu’il ne fait pas</h4><ul><li>Conseil juridique, fiscal, financier, médical ou d’investissement.</li><li>Dépôt officiel, collecte de fonds, courtage ou garde de fonds.</li><li>Décision automatisée à incidence élevée.</li><li>Accès autonome à des systèmes externes ou transaction réelle.</li><li>Garantie de résultat, de financement ou de conformité.</li></ul></div></div><p>Les lois impératives, droits des personnes, obligations professionnelles et décisions des autorités publiques prévalent toujours.</p></div>
  <div class="legal-pane" id="legal-boundary-en" data-lang="en"><h3>Operating boundary</h3><p>GoalOS Singularity Navigator Ω is a static, browser-local institution for research, simulation, prioritization, mission design, evidence governance and institutional monitoring. It does not itself create legal, tax, fiduciary, regulatory, professional or transaction authority.</p><div class="legal-columns"><div class="legal-box"><h4>The system may</h4><ul><li>Generate and compare candidate architectures.</li><li>Decompose an objective into bounded AGI Jobs.</li><li>Expose assumptions and Proof Debt.</li><li>Prepare dossiers, controls and escalation routes.</li><li>Maintain locally controlled exportable evidence.</li></ul></div><div class="legal-box"><h4>The system does not</h4><ul><li>Provide legal, tax, financial, medical or investment advice.</li><li>File officially, raise capital, broker transactions or custody funds.</li><li>Make high-impact automated decisions.</li><li>Access external systems autonomously or execute real transactions.</li><li>Guarantee outcomes, funding or compliance.</li></ul></div></div><p>Mandatory law, individual rights, professional obligations and public-authority decisions always prevail.</p></div>
  <div class="legal-pane" id="legal-access" data-lang="fr"><h3>Accès AGI Club — propriété directe actuelle</h3><p>L’usage ordinaire est réservé au portefeuille connecté qui détient actuellement et directement un nom exact à une étiquette <code>label.club.agi.eth</code>.</p><ul><li>Propriété directe non enveloppée via le registre ENS.</li><li>Propriété directe enveloppée uniquement via un déploiement officiel ENS Name Wrapper reconnu sur Ethereum Mainnet (déploiement courant ou historique autorisé), avec expiration valide.</li><li>Signature EIP-712 liée au domaine lorsque prise en charge; repli <code>personal_sign</code> documenté.</li><li>Session absolue de 30 minutes et verrouillage d’inactivité de 10 minutes.</li><li>Revérification périodique et avant les exports protégés.</li><li>Rejet des noms imbriqués, du domaine racine, des approbations, gestionnaires, résolveurs, anciens détenteurs et délégations.</li></ul><p>Le code d’un site GitHub Pages demeure public. Cette barrière est un mécanisme d’admissibilité, de provenance, de licence conditionnelle et de communauté; elle n’est pas un DRM confidentiel côté serveur.</p></div>
  <div class="legal-pane" id="legal-access-en" data-lang="en"><h3>AGI Club current direct-owner access</h3><p>Ordinary use is reserved for the connected wallet that currently and directly owns one exact one-label <code>label.club.agi.eth</code> name.</p><ul><li>Direct unwrapped ownership through the ENS Registry.</li><li>Direct wrapped ownership only through a recognized official ENS Name Wrapper deployment on Ethereum Mainnet (current or authorized legacy deployment), with current expiry.</li><li>Domain-bound EIP-712 signature where supported; documented <code>personal_sign</code> fallback.</li><li>Thirty-minute absolute session and ten-minute idle lock.</li><li>Periodic revalidation and revalidation before protected exports.</li><li>Nested names, root, approvals, managers, resolvers, former ownership and delegations are rejected.</li></ul><p>GitHub Pages source remains public. The gate is an eligibility, provenance, conditional-license and community mechanism—not confidential server-side DRM.</p></div>
  <div class="legal-pane" id="legal-terms" data-lang="fr"><h3>Conditions d’utilisation</h3><ol><li><b>Acceptation.</b> L’accès ou l’utilisation vaut acceptation des présentes conditions et de la version anglaise choisie, lorsque permise.</li><li><b>Licence limitée.</b> Licence personnelle, révocable, non transférable et conditionnelle à l’admissibilité AGI Club actuelle.</li><li><b>Interdictions.</b> Pas de contournement de l’accès, extraction automatisée, entraînement de modèles, réhébergement public, fausse représentation, fraude, activité illégale ou utilisation à incidence élevée sans contrôles appropriés.</li><li><b>Responsabilité de l’utilisateur.</b> Vérifier les faits, obtenir les autorisations, professionnels et approbations requis, et respecter les lois applicables.</li><li><b>Aucune garantie.</b> Service fourni « tel quel » et « selon disponibilité », sous réserve des droits non renonçables.</li><li><b>Limitation.</b> Aucune exclusion ne vise la fraude, la faute intentionnelle ni une responsabilité non excluable. Sinon, la responsabilité maximale est limitée au montant payé pour l’accès au présent service au cours des douze mois précédents, ou 100 CAD si aucun montant n’a été payé.</li><li><b>Indemnisation.</b> Dans la mesure permise, l’utilisateur répond de son utilisation illégale, de la violation de droits et du contournement des contrôles.</li><li><b>Langue.</b> Le français est présenté en premier conformément aux exigences applicables au Québec. La version anglaise est disponible sur choix exprès.</li><li><b>Droit impératif.</b> Rien ne limite les droits non renonçables ni la compétence obligatoire.</li></ol></div>
  <div class="legal-pane" id="legal-terms-en" data-lang="en"><h3>Terms of use</h3><ol><li><b>Acceptance.</b> Access or use constitutes acceptance of these terms and the selected English version where permitted.</li><li><b>Limited license.</b> Personal, revocable, non-transferable and conditional on current AGI Club eligibility.</li><li><b>Prohibited conduct.</b> No access circumvention, automated scraping, model training, public rehosting, misrepresentation, fraud, unlawful activity or high-impact use without appropriate controls.</li><li><b>User responsibility.</b> Verify facts, obtain required authority, professionals and approvals, and comply with applicable law.</li><li><b>No warranty.</b> Provided “as is” and “as available,” subject to non-waivable rights.</li><li><b>Limitation.</b> Nothing excludes fraud, wilful misconduct or non-excludable liability. Otherwise maximum liability is limited to the amount paid for this service during the preceding twelve months, or CAD 100 when nothing was paid.</li><li><b>Indemnity.</b> To the extent permitted, the user is responsible for unlawful use, rights violations and control circumvention.</li><li><b>Language.</b> French is presented first for applicable Quebec requirements. English is available by express choice.</li><li><b>Mandatory law.</b> Nothing limits non-waivable rights or mandatory jurisdiction.</li></ol></div>
  <div class="legal-pane" id="legal-privacy" data-lang="fr"><h3>Vie privée</h3><p>La présente publication n’exploite ni compte serveur GoalOS, ni formulaire serveur, ni analytique GoalOS, ni paiement GoalOS, ni télémétrie GoalOS. Les états de mission restent dans le navigateur jusqu’à export ou suppression par l’utilisateur.</p><h4>Données susceptibles d’être traitées</h4><ul><li>Adresse publique du portefeuille, nom ENS, preuve de signature et données de session dans le navigateur.</li><li>Objectifs, scénarios, preuves et réglages saisis localement.</li><li>Données techniques traitées par GitHub, le navigateur, le portefeuille ou le fournisseur RPC selon leurs propres politiques.</li></ul><h4>Minimisation</h4><p>Ne saisissez aucune donnée personnelle sensible, secret commercial, renseignement privilégié, clé, mot de passe, vulnérabilité non autorisée, donnée réglementée ou dossier confidentiel dans cette publication publique.</p><h4>Responsable de la protection des renseignements personnels</h4><p>MONTREAL.AI · Montréal, Québec · <a href="mailto:info@quebec.ai">info@quebec.ai</a>. Les demandes doivent permettre une vérification raisonnable de l’identité et du droit invoqué.</p></div>
  <div class="legal-pane" id="legal-privacy-en" data-lang="en"><h3>Privacy</h3><p>This publication operates no GoalOS server account, server form, GoalOS analytics, GoalOS payment or GoalOS telemetry. Mission state remains in the browser until the user exports or deletes it.</p><h4>Data that may be processed</h4><ul><li>Public wallet address, ENS name, signature proof and browser session data.</li><li>Objectives, scenarios, evidence and settings entered locally.</li><li>Technical data processed by GitHub, the browser, wallet or RPC provider under their policies.</li></ul><h4>Minimization</h4><p>Do not enter sensitive personal data, trade secrets, privileged material, keys, passwords, unauthorized vulnerability information, regulated data or confidential files into this public release.</p><h4>Privacy contact</h4><p>MONTREAL.AI · Montréal, Quebec · <a href="mailto:info@quebec.ai">info@quebec.ai</a>. Requests require reasonable verification of identity and claimed rights.</p></div>
  <div class="legal-pane" id="legal-security" data-lang="fr"><h3>Sécurité et divulgation responsable</h3><ul><li>Aucun script, style, traceur ou API GoalOS externe à l’exécution.</li><li>Politique de sécurité du contenu restrictive; état local; exports chiffrables.</li><li>Les protections côté client ne remplacent pas une infrastructure serveur confidentielle.</li><li>Un portefeuille compromis, une extension malveillante, un appareil infecté ou un RPC trompeur peut compromettre l’expérience locale.</li><li>Pour une vulnérabilité réelle, contactez <a href="mailto:info@quebec.ai">info@quebec.ai</a> avec un rapport minimal et n’exploitez pas les utilisateurs.</li></ul><p>Les actions externes à conséquence élevée exigent un environnement protégé, des journaux, des contrôles d’accès, une réponse aux incidents et des tests indépendants adaptés au déploiement.</p></div>
  <div class="legal-pane" id="legal-security-en" data-lang="en"><h3>Security and responsible disclosure</h3><ul><li>No external runtime GoalOS scripts, styles, trackers or APIs.</li><li>Restrictive content security policy; local state; encryptable exports.</li><li>Client-side controls do not replace confidential server infrastructure.</li><li>A compromised wallet, malicious extension, infected device or deceptive RPC can compromise the local experience.</li><li>For a real vulnerability, contact <a href="mailto:info@quebec.ai">info@quebec.ai</a> with a minimal report and do not exploit users.</li></ul><p>Consequential external action requires a protected environment, logs, access controls, incident response and independent deployment-specific tests.</p></div>
  <div class="legal-pane" id="legal-transparency" data-lang="fr"><h3>Transparence de l’IA</h3><p>Les recommandations, scores, simulations, journaux d’agents, scénarios et documents générés sont clairement identifiés comme sorties algorithmiques. L’utilisateur doit conserver cette mention lors d’une diffusion pertinente.</p><ul><li>Le système ne prétend pas qu’une personne réelle a formulé une sortie générée.</li><li>Les simulations ne sont pas des faits observés.</li><li>Les évaluations automatiques ne sont pas des validations indépendantes lorsqu’elles utilisent les mêmes sources ou modèles.</li><li>Un déploiement doit déterminer les rôles applicables de fournisseur, déployeur, importateur, distributeur ou utilisateur professionnel.</li></ul></div>
  <div class="legal-pane" id="legal-transparency-en" data-lang="en"><h3>AI transparency</h3><p>Recommendations, scores, simulations, agent logs, scenarios and generated documents are clearly identified as algorithmic outputs. The user should preserve appropriate disclosure when distributing them.</p><ul><li>The system does not claim a real person authored generated output.</li><li>Simulations are not observed facts.</li><li>Automated evaluations are not independent validation when they share the same models or sources.</li><li>Deployments must determine applicable provider, deployer, importer, distributor or professional-user roles.</li></ul></div>
  <div class="legal-pane" id="legal-rights" data-lang="fr"><h3>Droits, propriété et réutilisation</h3><p>MONTREAL.AI conserve ses marques, noms, interfaces, textes, schémas, logiciels, méthodes, graphes et matériaux préexistants. L’utilisateur conserve ses données et résultats propres, sous réserve des droits de tiers et du contrat applicable.</p><ul><li>Aucune licence de marque, d’hébergement commercial, de formation de modèle ou de création d’un service concurrent n’est accordée implicitement.</li><li>Aucune sortie ne doit entrer dans Chronicle sans provenance, droits, portée, version, durée, conditions d’échec et révocabilité.</li><li>Les références publiques doivent créditer GoalOS Ω et MONTREAL.AI lorsqu’elles reproduisent substantiellement l’architecture.</li><li>Les marques de tiers appartiennent à leurs propriétaires.</li></ul></div>
  <div class="legal-pane" id="legal-rights-en" data-lang="en"><h3>Rights, ownership and reuse</h3><p>MONTREAL.AI retains its trademarks, names, interfaces, text, schemas, software, methods, graphs and pre-existing materials. The user retains its own data and outputs, subject to third-party rights and the applicable agreement.</p><ul><li>No trademark, commercial hosting, model-training or competing-service license is implied.</li><li>No output may enter Chronicle without provenance, rights, scope, version, duration, failure conditions and revocability.</li><li>Public references should credit GoalOS Ω and MONTREAL.AI when substantially reproducing the architecture.</li><li>Third-party marks belong to their owners.</li></ul></div>
  <div class="legal-pane" id="legal-regulatory" data-lang="fr"><h3>Positionnement réglementaire</h3><p><b>Aucune offre de titres, sollicitation, courtage ou conseil d’investissement.</b> Le produit est conçu pour réduire l’exposition non nécessaire, non pour contourner les lois. La publication publique est limitée à la recherche, la simulation et la conception de missions; elle n’exécute pas de transaction externe et n’offre pas de service professionnel réglementé.</p><div class="legal-columns"><div class="legal-box"><h4>Contrôles structurels</h4><ul><li>Traitement local et minimisation.</li><li>Autorité explicite et révocable.</li><li>Validation indépendante proportionnelle au risque.</li><li>Transparence des sorties algorithmiques.</li><li>Absence de garde, courtage, dépôt officiel ou conseil réservé.</li></ul></div><div class="legal-box"><h4>Déploiement privé requis lorsque</h4><ul><li>Données sensibles ou réglementées.</li><li>Action externe, paiement ou engagement contractuel.</li><li>Décision touchant les droits, l’emploi, le crédit, la santé ou l’accès à un service essentiel.</li><li>Infrastructure critique, cybersécurité active ou risque physique.</li></ul></div></div><p>Une analyse locale par des professionnels qualifiés demeure requise avant toute action contraignante.</p></div>
  <div class="legal-pane" id="legal-regulatory-en" data-lang="en"><h3>Regulatory positioning</h3><p><b>No securities offer, solicitation, brokerage or investment advice.</b> The product is designed to reduce unnecessary exposure, not evade law. The public release is limited to research, simulation and mission design; it performs no external transaction and offers no regulated professional service.</p><div class="legal-columns"><div class="legal-box"><h4>Structural controls</h4><ul><li>Local processing and minimization.</li><li>Explicit, revocable authority.</li><li>Risk-proportionate independent validation.</li><li>Transparency of algorithmic outputs.</li><li>No custody, brokerage, official filing or reserved advice.</li></ul></div><div class="legal-box"><h4>Protected deployment required when</h4><ul><li>Sensitive or regulated data.</li><li>External action, payment or contractual commitment.</li><li>Decisions affecting rights, employment, credit, health or essential-service access.</li><li>Critical infrastructure, active cybersecurity or physical risk.</li></ul></div></div><p>Local review by qualified professionals remains required before binding action.</p></div>
 </div>
 <div class="legal-note" style="margin-top:14px"><b>Dernière révision · Last reviewed:</b> 26 juillet 2026 · 26 July 2026. <a href="governance/LEGAL_INDEX.html" target="_blank">Index juridique bilingue / Bilingual Legal Index</a></div>
</section>
'''
s=s[:legal_start]+legal_html+s[legal_end:]

# Add owner center fields and legal language status.
s=s.replace('<div class="owner-cell"><span>Deployment</span><b id="ownerVaultDeployment">—</b></div>', '<div class="owner-cell"><span>Deployment</span><b id="ownerVaultDeployment">—</b></div><div class="owner-cell"><span>Signature mode</span><b id="ownerVaultSignatureMode">EIP-712 preferred</b></div><div class="owner-cell"><span>Idle lock</span><b id="ownerVaultIdle">10 minutes</b></div><div class="owner-cell"><span>Legal language</span><b id="ownerVaultLegalLang">Français</b></div>')

# Add extra owner confirmations without removing old controls.
if 'id="agiClubLanguageConfirm"' not in s:
    extra_confirms='<label class="agc-check"><input type="checkbox" id="agiClubLanguageConfirm"><span>Je choisis d’abord le français pour les documents juridiques; English remains available by express selection.</span></label><label class="agc-check"><input type="checkbox" id="agiClubNoSecretsConfirm"><span>Je n’entrerai aucun secret, renseignement privilégié, donnée réglementée ou identifiant dans cette publication statique.</span></label>'
    pattern=r'(<label class="agc-check"><input id="agiClubBoundaryConfirm"[^>]*><span>.*?</span></label>)'
    s,nconf=re.subn(pattern,lambda m:m.group(1)+extra_confirms,s,count=1,flags=re.S)
    if nconf!=1: raise RuntimeError(f'AGI Club confirmation insertion count {nconf}')

# Patch access CFG and add idle tracking + typed-data preference directly in runtime.
s=s.replace("sessionMinutes:30,recheckMinutes:5", "sessionMinutes:30,recheckMinutes:5,idleMinutes:10")
s=s.replace("let receipt=null,busy=false,recheckTimer=null,tickTimer=null,lastCheckDue=0;", "let receipt=null,busy=false,recheckTimer=null,tickTimer=null,lastCheckDue=0,lastActivity=Date.now();")
s=s.replace("function scheduleChecks(){if(recheckTimer)clearInterval(recheckTimer);if(tickTimer)clearInterval(tickTimer);if(!receipt)return;lastCheckDue=Date.now()+CFG.recheckMinutes*60000;recheckTimer=setInterval(()=>revalidate('scheduled ownership check'),CFG.recheckMinutes*60000);tickTimer=setInterval(updateCountdown,1000);updateCountdown()}", "function scheduleChecks(){if(recheckTimer)clearInterval(recheckTimer);if(tickTimer)clearInterval(tickTimer);if(!receipt)return;lastActivity=Date.now();lastCheckDue=Date.now()+CFG.recheckMinutes*60000;recheckTimer=setInterval(()=>revalidate('scheduled ownership check'),CFG.recheckMinutes*60000);tickTimer=setInterval(()=>{updateCountdown();if(receipt&&Date.now()-lastActivity>CFG.idleMinutes*60000)lock('Session inactive for 10 minutes — institution relocked.')},1000);updateCountdown()}")
# Require added confirmations in busy readiness and bind listeners.
s=s.replace("function ready(){return cleanLabel($('#agiClubLabelInput')?.value).ok&&$('#agiClubOwnerConfirm')?.checked&&$('#agiClubLicenseConfirm')?.checked&&$('#agiClubBoundaryConfirm')?.checked}", "function ready(){return cleanLabel($('#agiClubLabelInput')?.value).ok&&$('#agiClubOwnerConfirm')?.checked&&$('#agiClubLicenseConfirm')?.checked&&$('#agiClubBoundaryConfirm')?.checked&&$('#agiClubLanguageConfirm')?.checked&&$('#agiClubNoSecretsConfirm')?.checked}")
s=s.replace("['#agiClubLabelInput','#agiClubOwnerConfirm','#agiClubLicenseConfirm','#agiClubBoundaryConfirm']", "['#agiClubLabelInput','#agiClubOwnerConfirm','#agiClubLicenseConfirm','#agiClubBoundaryConfirm','#agiClubLanguageConfirm','#agiClubNoSecretsConfirm']")
# Upgrade access proof to EIP-712 when available, with a documented personal_sign fallback.
verify_pattern=r"async function verifyLocal\(name,address\)\{.*?\}\nfunction receiptActive"
verify_replacement="""async function verifyLocal(name,address){const p=await provider();await mainnet(p,true);const first=await localOwner(name,address);if(!first.ok)throw new Error(first.error);const issued=new Date(),expires=new Date(issued.getTime()+CFG.sessionMinutes*60000),n=nonce(),message=accessMessage(name,address,n,issued.toISOString(),expires.toISOString()),firstBlock=await blockNumber();const typed={domain:{name:'GoalOS Singularity Navigator Ω',version:'3',chainId:1,verifyingContract:CFG.registry},primaryType:'AGIClubAccess',types:{EIP712Domain:[{name:'name',type:'string'},{name:'version',type:'string'},{name:'chainId',type:'uint256'},{name:'verifyingContract',type:'address'}],AGIClubAccess:[{name:'name',type:'string'},{name:'owner',type:'address'},{name:'nonce',type:'string'},{name:'issuedAt',type:'string'},{name:'expiresAt',type:'string'},{name:'canonicalDeployment',type:'string'}]},message:{name,owner:address,nonce:n,issuedAt:issued.toISOString(),expiresAt:expires.toISOString(),canonicalDeployment:canonicalUrl()}};let signature,signatureMode,signedPayload;try{signedPayload=JSON.stringify(typed);signature=await p.request({method:'eth_signTypedData_v4',params:[address,signedPayload]});signatureMode='eip712-v4'}catch(e){signedPayload=message;signature=await p.request({method:'personal_sign',params:[message,address]});signatureMode='personal_sign-domain-bound'}await mainnet(p,false);const active=await accounts(false);if(!same(active,address))throw new Error('Wallet account changed while the access proof was being constituted.');const second=await localOwner(name,address);if(!second.ok)throw new Error('Ownership changed during verification.');const verifiedBlock=await blockNumber();return{schema:'goalos-agi-club-owner-access/3.0',version:CFG.version,product:'GoalOS Singularity Navigator Ω',name,address,node:second.node,mode:second.mode,registryOwner:second.registryOwner,wrapperAddress:second.wrapperAddress,wrapperLabel:second.wrapperLabel,wrappedExpiry:second.expiry,fuses:second.fuses,issuedAt:issued.toISOString(),expiresAt:expires.toISOString(),lastVerifiedAt:new Date().toISOString(),verificationBlock:verifiedBlock,initialVerificationBlock:firstBlock,nonce:n,message,signedPayload,signature,signatureMode,signatureDigest:'0x'+hx(k256(signature)),authority:'github-pages-static-direct-owner-check',serverAuthoritative:false,distributionMode:'public-static-github-pages',canonicalDeployment:canonicalUrl(),canonicalDeploymentMatch:isCanonical(),protectionBoundary:'Conditional-use and evidence gate; public source is not confidential and client-side access control is not unbypassable DRM.'}}\nfunction receiptActive"""
s,nverify=re.subn(verify_pattern,verify_replacement,s,flags=re.S)
if nverify!=1: raise RuntimeError(f'verifyLocal replacement count {nverify}')
s=s.replace("set('#ownerVaultDeployment',isCanonical()?'Canonical GitHub Pages path':'Standalone / alternate origin');updateCountdown()", "set('#ownerVaultDeployment',isCanonical()?'Canonical GitHub Pages path':'Standalone / alternate origin');set('#ownerVaultSignatureMode',r?.signatureMode||'—');updateCountdown()")

# Add activity listeners after bind declaration opening.
s=s.replace("function bind(){['#agiClubLabelInput'", "function bind(){['pointerdown','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,()=>{lastActivity=Date.now()},{passive:true}));['#agiClubLabelInput'")
# Add signature mode to receipts without risky EIP-712 wallet dependencies; preserve compatibility and label fallback accurately.
# signature mode is set by the replacement verifyLocal implementation below

# App enhancement script before closing body.
SN5_JS=r'''
<script id="goalos-sn5-apex-runtime">
(()=>{'use strict';
const SN5_VERSION='v3.0.0-SN5';
const sn5$=(s,r=document)=>r.querySelector(s),sn5$$=(s,r=document)=>[...r.querySelectorAll(s)];
const originalMissionInputs=missionInputs, originalGenerateJobs=generateJobs, originalRenderAll=renderAll, originalRoute=route, originalSetCouncil=setCouncil;
setCouncil=function(p,label){originalSetCouncil(Math.min(100,p),label)};
// Enlarge the institution without deleting predecessor primitives.
AGENTS.push(['Counterfactual Governor','Changes capability, evidence, authority and capital assumptions to test recommendation stability.'],['Rights & Privacy Steward','Enforces data minimization, rights, retention, language and deployment boundaries.'],['Opportunity Portfolio Architect','Builds immediate, successor and reserve proposals around preserve, build and become.']);
STRATEGIES.push(
 {id:'federated',name:'Federated Mission Network',tag:'Distributed proof',desc:'Coordinates specialized sovereign nodes under shared standards while keeping data, authority and evidence locally scoped.',base:{upside:86,speed:72,resilience:92,evidence:93,agency:89,reversibility:90,autonomy:66,complexity:78,compounding:95}},
 {id:'science',name:'Autonomous Discovery Institution',tag:'Research frontier',desc:'Converts hypotheses into controlled research missions, independent replication, validated discovery and protected scientific capability.',base:{upside:96,speed:80,resilience:76,evidence:96,agency:77,reversibility:73,autonomy:86,complexity:82,compounding:98}},
 {id:'market',name:'Verified Market Capture',tag:'Distribution first',desc:'Uses high-frequency customer and operational missions to capture demand, prove value quickly and finance deeper capability ownership.',base:{upside:91,speed:91,resilience:73,evidence:86,agency:79,reversibility:84,autonomy:82,complexity:63,compounding:92}},
 {id:'civil',name:'Public-Interest Capacity Compact',tag:'Institutional legitimacy',desc:'Combines productive capacity with public-purpose, transparent evidence, distributed benefits and durable institutional legitimacy.',base:{upside:84,speed:58,resilience:95,evidence:97,agency:96,reversibility:87,autonomy:49,complexity:85,compounding:94}}
);
RECEIPTS.push(['privacy','Privacy and data constitution','Data classes, legal basis, minimization, retention, deletion and protected-environment triggers.','execute'],['conflict','Conflict and independence register','Provider compensation, evaluator independence and interested-party roles are disclosed.','accept'],['impact','Impact and externalities docket','Material labour, environmental, market, security and public-impact effects are assessed.','admit']);
SOURCES.push(
 {publisher:'Commission d’accès à l’information du Québec',title:'Loi 25 — obligations des entreprises',class:'Privacy · Quebec',verified:'2026-07-26',url:'https://www.cai.gouv.qc.ca/entreprises/protection-renseignements-personnels-loi-25',note:'Privacy governance, incident and transparency obligations applicable in Quebec contexts.'},
 {publisher:'ENS Documentation',title:'ENS Deployments and Name Wrapper',class:'Identity · Ethereum',verified:'2026-07-26',url:'https://docs.ens.domains/learn/deployments/',note:'Official Ethereum Mainnet Registry and Name Wrapper deployment references.'}
);
DEFAULT_EVENTS.push({date:'2026-07-26',class:'Institution',title:'SN5 Apex Opportunity Engine constituted',summary:'GoalOS adds three-horizon recommendations, counterfactual stability, encrypted evidence portability and bilingual legal controls.',url:'',impact:94,active:true});
for(const r of RECEIPTS)if(!(r[0] in state.receipts))state.receipts[r[0]]=false;
state.ledger=Array.isArray(state.ledger)?state.ledger:[];
state.counterfactual=state.counterfactual||{acceleration:72,evidenceLatency:48,authorityRisk:55,capitalUrgency:62,irreversibility:44,costCollapse:76};

function adaptiveBudget(){const explicit=+(sn5$('#deliberationBudget')?.value||0);if(explicit)return explicit;const stakes=+(sn5$('#decisionStakes')?.value||60),sensitive=+(sn5$('#dataSensitivity')?.value||48),posture=sn5$('#deploymentPosture')?.value||'advisory';const mult={reference:0,advisory:8,assisted:16,governed:28,infrastructure:38}[posture]||0;const v=stakes+sensitive*.55+mult+(state.events?.filter(e=>e.active!==false).length||0)*1.5;return v>145?16384:v>90?4096:1024}
missionInputs=function(){const m=originalMissionInputs();m.stakes=+(sn5$('#decisionStakes')?.value||60);m.dataSensitivity=+(sn5$('#dataSensitivity')?.value||48);m.deploymentPosture=sn5$('#deploymentPosture')?.value||'advisory';m.deliberationBudget=adaptiveBudget();return m};
const extraJobs=[
 ['Run counterfactual architecture auction','Counterfactual Governor','Stability and switch report','Counterfactual docket'],
 ['Compile Value-of-Proof queue','Evidence Verifier','Evidence acquisition order','Value-of-Proof receipt'],
 ['Constitute privacy and retention boundary','Rights & Privacy Steward','Data constitution','Privacy receipt'],
 ['Build three-horizon opportunity portfolio','Opportunity Portfolio Architect','Immediate, successor and reserve proposals','Portfolio receipt'],
 ['Map externalities and public-impact effects','Adversarial Auditor','Impact ledger','Impact receipt'],
 ['Create encrypted portable proof bundle','Evidence Verifier','Custody-ready evidence package','Integrity digest']
];
generateJobs=function(m,c){const base=originalGenerateJobs(m,c);return base.concat(extraJobs.map((j,i)=>({id:'J'+String(base.length+i+1).padStart(2,'0'),title:j[0],agent:j[1],output:j[2],proof:j[3],status:'planned',budget:Math.round(7+i*2+m.capital*1.7),deps:['J'+String(Math.max(1,base.length-2+i%3)).padStart(2,'0')],authority:i===2?'Privacy owner':i===4?'Accountable sponsor':'Mission owner'})))};
function decisionState(){if(!state.winner)return['Awaiting mission','pending'];const p=proofPct(),w=state.winner;if(w.gate==='blocked'||p<35)return['CONTAIN / DO NOT DEPLOY','danger'];if(p<70||w.proofDebt>35)return['TEST UNDER CONTAINMENT','warn'];if(p<90)return['ADOPT CONDITIONALLY','warn'];return['ADOPT WITH MONITORING','good']}
function proposalPortfolio(){if(!state.candidates?.length)return[];const c=state.candidates;const champion=c[0],successor=c.find(x=>x.id!==champion.id&&x.metrics.compounding>=champion.metrics.compounding-3)||c[1],reserve=[...c].sort((a,b)=>(b.metrics.reversibility+b.metrics.resilience)-(a.metrics.reversibility+a.metrics.resilience)).find(x=>x.id!==champion.id&&x.id!==successor?.id)||c[2];return[{role:'Immediate architecture',x:champion,why:'Best current verified-risk-adjusted route.'},{role:'Successor architecture',x:successor,why:'Most credible next architecture after current Proof Debt is retired.'},{role:'Reserve option',x:reserve,why:'Preserves reversibility, continuity and provider optionality.'}]}
function nonDominated(cands){return cands.filter(a=>!cands.some(b=>b!==a&&b.score>=a.score&&b.p10>=a.p10&&b.proofDebt<=a.proofDebt&&((b.score>a.score)||(b.p10>a.p10)||(b.proofDebt<a.proofDebt))))}
function renderOpportunity(){const band=sn5$('#sn5DecisionBand');if(!band)return;const w=state.winner,[label,cls]=decisionState(),ser=singularityExposure(),p=proofPct(),nd=nonDominated(state.candidates||[]);sn5$('#sn5DecisionThesis').textContent=state.mission?`${state.mission.objective} GoalOS currently recommends ${w?.name||'no architecture'} within an explicit evidence and authority envelope.`:'Constitute a mission to generate the decision portfolio.';band.innerHTML=`<div><strong class="${cls}">${label}</strong><small>Institutional verdict</small></div><div><strong>${esc(w?.name||'—')}</strong><small>Champion</small></div><div><strong>${w?Math.round((w.stability??0)*100)+'%':'—'}</strong><small>Stability</small></div><div><strong>${p}%</strong><small>Proof posture</small></div><div><strong>${state.mission?ser.ser.toFixed(2):'—'}</strong><small>Exposure ratio</small></div>`;
 const anti=state.candidates?.slice().sort((a,b)=>b.metrics.upside-a.metrics.upside).find(x=>x.gate==='blocked')||state.candidates?.slice(-1)[0];sn5$('#sn5AntiRecommendation').textContent=anti?`Do not select ${anti.name} merely for its upside. It carries ${anti.proofDebt.toFixed(0)} Proof Debt points, ${anti.regret.toFixed(1)} modeled regret and a ${anti.gate} gate.`:'GoalOS will state what must not be done, even when it looks attractive.';sn5$('#sn5NoGo').innerHTML=w?`<h3>No-go condition</h3><p>Do not cross an irreversible boundary while any applicable authority, privacy, evidence, independent-validation or rollback receipt remains absent.</p>`:'<h3>No-go condition</h3><p>Awaiting a constituted objective.</p>';
 const pp=proposalPortfolio();sn5$('#sn5ProposalPortfolio').innerHTML=pp.length?pp.map((p,i)=>`<article class="sn5-proposal ${i===0?'champion':''}"><span class="rank">${i+1}</span><em>${esc(p.role)}</em><h3>${esc(p.x.name)}</h3><p>${esc(p.why)} ${esc(p.x.desc)}</p><div class="scores"><span>Score ${p.x.score.toFixed(1)}</span><span>P10 ${p.x.p10.toFixed(1)}</span><span>Debt ${p.x.proofDebt.toFixed(0)}</span><span>${p.x.gate}</span></div></article>`).join(''):'<p>Run the mission.</p>';
 const vp=proofPriorities();sn5$('#sn5Vop').innerHTML=vp.length?vp.slice(0,7).map((x,i)=>`<div class="sn5-vop-row"><i>${i+1}</i><div><b>${esc(x.name)}</b><span>${esc(x.detail)}</span></div><em>${x.score}</em></div>`).join(''):'<div class="alert good"><h3>Canonical receipts present</h3><p>Maintain currentness, scope and revocation.</p></div>';
 const sw=briefSwitchConditions();sn5$('#sn5SwitchStop').innerHTML=(sw.length?sw:['Constitute a mission.']).map((x,i)=>`<div class="brief-item"><b>${i<3?'Switch':'Stop'} condition</b><p>${esc(x)}</p></div>`).join('');
 const tri=sn5$('#sn5MandateTriad');if(state.mission&&tri){const txt=state.mission.objective;const mode=state.constitution?.mode||'institution';tri.innerHTML=`<article><em>Preserve</em><h3>Institutional invariants</h3><p>Protect accountable authority, rights, strategic data, reversibility and the mission’s non-negotiable purpose.</p></article><article><em>Build</em><h3>${esc(mode)} capability frontier</h3><p>Execute the immediate ${esc(w?.name||'candidate')} mission, retire the highest Value-of-Proof items and produce an accepted Evidence Docket.</p></article><article><em>Become</em><h3>Successor institution</h3><p>Admit only proven capability, rerun on a fresh mission and move to the successor only when improvement is demonstrated.</p></article>`}
}
function cfValues(){return{acceleration:+sn5$('#cfAcceleration').value,evidenceLatency:+sn5$('#cfEvidenceLatency').value,authorityRisk:+sn5$('#cfAuthorityRisk').value,capitalUrgency:+sn5$('#cfCapitalUrgency').value,irreversibility:+sn5$('#cfIrreversibility').value,costCollapse:+sn5$('#cfCostCollapse').value}}
function counterScore(x,v){return x.score+(v.costCollapse-50)*x.metrics.autonomy*.0016+(v.capitalUrgency-50)*x.metrics.speed*.0014-(v.authorityRisk-50)*(100-x.metrics.agency)*.0018-(v.evidenceLatency-50)*(100-x.metrics.evidence)*.0016-(v.irreversibility-50)*(100-x.metrics.reversibility)*.0017+(v.acceleration-50)*x.metrics.compounding*.0015}
function renderCounterfactual(){const v=cfValues();state.counterfactual=v;const ranked=(state.candidates||[]).map(x=>({...x,cfScore:counterScore(x,v)})).sort((a,b)=>b.cfScore-a.cfScore);const stability=state.winner&&ranked.length?Math.max(12,Math.round(100-Math.abs(ranked[0].cfScore-state.winner.score)*3-(ranked[0].id!==state.winner.id?28:0))):0;sn5$('#sn5CounterKpis').innerHTML=[['Champion',ranked[0]?.name||'—'],['Stability',stability+'%'],['Shock severity',Math.round((v.acceleration+v.authorityRisk+v.irreversibility)/3)],['Evidence pressure',Math.round((v.evidenceLatency+v.authorityRisk)/2)]].map(x=>`<div class="sn5-counter"><b>${esc(String(x[1]))}</b><span>${esc(x[0])}</span></div>`).join('');sn5$('#sn5StabilityLabel').textContent=stability?stability+'%':'—';sn5$('#sn5StabilityBar').style.width=stability+'%';sn5$('#sn5CounterNarrative').innerHTML=ranked.length?`<div class="alert ${ranked[0].id===state.winner?.id?'good':'warn'}"><h3>${ranked[0].id===state.winner?.id?'Champion survives':'Architecture switch detected'}</h3><p>${ranked[0].id===state.winner?.id?`${ranked[0].name} remains preferred under this counterfactual regime.`:`The modeled world changes the champion from ${state.winner?.name} to ${ranked[0].name}. Treat this as a switch condition, not a prediction.`}</p></div>`:'<p>Run a mission first.</p>';sn5$('#sn5CounterRanking').innerHTML=ranked.slice(0,8).map((x,i)=>`<div class="proof-priority"><i>${i+1}</i><div><b>${esc(x.name)}</b><span>Counterfactual ${x.cfScore.toFixed(1)} · Base ${x.score.toFixed(1)} · Debt ${x.proofDebt.toFixed(0)}</span></div><em>${x.gate}</em></div>`).join('')||'<p>Awaiting mission.</p>';save()}
function decisionLedger(){const items=[];if(state.mission)items.push(['Mission constituted',state.mission.objective,new Date(state.created||Date.now()).toLocaleDateString()]);if(state.winner)items.push(['Architecture recommended',state.winner.name,decisionState()[0]]);for(const e of (state.chronicle||[]).slice(-5))items.push(['Chronicle',e.title||e.name||'Capability record',e.status||e.verdict||'recorded']);for(const g of (state.generations||[]).slice(-3))items.push(['Successor',g.name,`Quality ${Math.round(g.quality)} · Risk ${Math.round(g.risk)}`]);return items}
function renderLedger(){const el=sn5$('#sn5DecisionLedger');if(!el)return;el.innerHTML=decisionLedger().map(x=>`<div class="sn5-ledger-row"><b>${esc(x[0])}</b><span>${esc(x[1])}</span><em>${esc(x[2])}</em></div>`).join('')||'<div class="legal-note">No mission decisions have been recorded yet.</div>'}
function sha256Fallback(ascii){function rr(v,a){return(v>>>a)|(v<<(32-a))}const mp=Math.pow,mx=mp(2,32),l='length',words=[],len=ascii[l]*8;let h=sha256Fallback.h=sha256Fallback.h||[],k=sha256Fallback.k=sha256Fallback.k||[],pc=k[l],c={};for(let n=2;pc<64;n++){if(!c[n]){for(let i=0;i<313;i+=n)c[i]=n;h[pc]=(mp(n,.5)*mx)|0;k[pc++]=(mp(n,1/3)*mx)|0}}ascii+='\x80';while(ascii[l]%64-56)ascii+='\x00';for(let i=0;i<ascii[l];i++){const j=ascii.charCodeAt(i);if(j>>8)return'';words[i>>2]|=j<<((3-i)%4)*8}words[words[l]]=(len/mx)|0;words[words[l]]=len;for(let j=0;j<words[l];){const w=words.slice(j,j+=16),oldh=h.slice(0);h=h.slice(0,8);for(let i=0;i<64;i++){const w15=w[i-15],w2=w[i-2],a=h[0],e=h[4];const temp1=h[7]+(rr(e,6)^rr(e,11)^rr(e,25))+((e&h[5])^((~e)&h[6]))+k[i]+(w[i]=i<16?w[i]:(w[i-16]+(rr(w15,7)^rr(w15,18)^(w15>>>3))+w[i-7]+(rr(w2,17)^rr(w2,19)^(w2>>>10)))|0);const temp2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&h[1])^(a&h[2])^(h[1]&h[2]));h=[(temp1+temp2)|0,a,h[1],h[2],(h[3]+temp1)|0,e,h[5],h[6]]}for(let i=0;i<8;i++)h[i]=(h[i]+oldh[i])|0}let out='';for(let i=0;i<8;i++)for(let j=3;j+1;j--){const b=(h[i]>>(j*8))&255;out+=(b<16?'0':'')+b.toString(16)}return out}async function sha256Text(t){if(globalThis.crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}return sha256Fallback(unescape(encodeURIComponent(t)))}
function proofBundle(){return{schema:'goalos-singularity-navigator-proof-bundle/3.0',product:'GoalOS Singularity Navigator Ω',version:SN5_VERSION,generatedAt:new Date().toISOString(),algorithmicOutput:true,operatingBoundary:'Research, simulation, mission design and evidence governance; no external authority or transaction.',state,sourceSnapshot:SOURCES,receiptDefinitions:RECEIPTS,integrity:{hashAlgorithm:'SHA-256',digest:null}}}
async function buildBundle(){const b=proofBundle(),canon=JSON.stringify(b);b.integrity.digest=await sha256Text(canon);return b}
async function deriveKey(pass,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function b64(bytes){return btoa(String.fromCharCode(...bytes))}function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function encryptedBundle(bundle,pass){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pass,salt),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(bundle)));return{schema:'goalos-encrypted-proof-bundle/1.0',kdf:'PBKDF2-SHA-256',iterations:250000,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),ciphertext:b64(new Uint8Array(ct))}}
async function decryptBundle(obj,pass){const key=await deriveKey(pass,unb64(obj.salt)),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(obj.iv)},key,unb64(obj.ciphertext));return JSON.parse(new TextDecoder().decode(pt))}
let lastBundle=null;
async function renderBundle(){lastBundle=await buildBundle();sn5$('#sn5BundleDigest').textContent=`SHA-256  ${lastBundle.integrity.digest}\nGenerated ${lastBundle.generatedAt}\nMission ${state.mission?.objective||'not constituted'}\nCandidate architectures ${(state.candidates||[]).length}\nProof receipts ${proofPct()}%\nChronicle records ${(state.chronicle||[]).length}`;return lastBundle}
function updateGenerations(){if(!state.winner)return;if((state.generations||[]).length<3){const g1=state.generations[1]||state.generations[0];state.generations.push({name:'Generation 2',quality:clamp(g1.quality+7),value:clamp(g1.value+9),time:clamp(g1.time-12,12,100),cost:clamp(g1.cost-10,12,100),risk:clamp(g1.risk-7,8,100),human:clamp(g1.human-9,8,100)})}}
renderAll=function(){updateGenerations();originalRenderAll();renderOpportunity();renderCounterfactual();renderLedger()};
route=function(name){originalRoute(name);if(name==='opportunity')setTimeout(renderOpportunity,20);if(name==='lab')setTimeout(renderCounterfactual,20);if(name==='vault')setTimeout(renderLedger,20);if(name==='masterclass'){} };
const runBtn=sn5$('#runMission');runBtn?.addEventListener('click',()=>{setTimeout(()=>{state.receipts={...state.receipts,privacy:true,conflict:true,impact:false};state.ledger.push({at:new Date().toISOString(),event:'mission-run',objective:state.mission?.objective});renderAll()},AGENTS.length*240+700)});
sn5$('#runCounterfactual')?.addEventListener('click',()=>{renderCounterfactual();toast('Counterfactual frontier regenerated','The result is a modeled decision aid, not a prediction.')});sn5$$('#view-lab input[type=range]').forEach(r=>r.addEventListener('input',()=>{const v=r.parentElement.querySelector('.range-val');if(v)v.textContent=r.value}));
sn5$('#generateProofBundle')?.addEventListener('click',async()=>{await renderBundle();toast('Proof bundle generated','SHA-256 digest computed locally.')});sn5$('#exportPlainBundle')?.addEventListener('click',async()=>{const b=lastBundle||await renderBundle();download(`GoalOS_SN5_Proof_Bundle_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(b,null,2))});sn5$('#exportEncryptedBundle')?.addEventListener('click',async()=>{const pass=sn5$('#vaultPassphrase').value;if(pass.length<10)return toast('Passphrase required','Use at least 10 characters for local encryption.');const b=lastBundle||await renderBundle(),enc=await encryptedBundle(b,pass);download(`GoalOS_SN5_Encrypted_Proof_Bundle_${new Date().toISOString().slice(0,10)}.goalos`,JSON.stringify(enc,null,2),'application/json');toast('Encrypted bundle downloaded','AES-GCM encryption completed locally.')});sn5$('#importVaultBundle')?.addEventListener('click',async()=>{const f=sn5$('#vaultImportFile').files?.[0];if(!f)return toast('Choose a bundle file');try{let obj=JSON.parse(await f.text());if(obj.schema==='goalos-encrypted-proof-bundle/1.0')obj=await decryptBundle(obj,sn5$('#vaultImportPassphrase').value);if(!obj.state)throw new Error('No GoalOS state in bundle.');state={...state,...obj.state};save();renderAll();toast('Bundle restored','Mission state restored locally.')}catch(e){toast('Restore failed',String(e.message||e))}});sn5$('#purgeMissionState')?.addEventListener('click',()=>{if(!confirm('Purge all browser-local GoalOS mission state? AGI Club access is not affected.'))return;localStorage.removeItem(STORE);location.reload()});
// Legal language behavior: one pane per selected legal topic and language.
let legalLang='fr';function showLegal(){const key=sn5$('#legalNav button.active')?.dataset.legal||'boundary';sn5$$('.legal-pane').forEach(p=>p.classList.remove('active'));const id=legalLang==='fr'?`#legal-${key}`:`#legal-${key}-en`;sn5$(id)?.classList.add('active');sn5$$('[data-legal-lang]').forEach(b=>b.classList.toggle('active',b.dataset.legalLang===legalLang));const ol=sn5$('#ownerVaultLegalLang');if(ol)ol.textContent=legalLang==='fr'?'Français':'English'}
sn5$$('[data-legal-lang]').forEach(b=>b.addEventListener('click',()=>{legalLang=b.dataset.legalLang;showLegal()}));sn5$('#legalNav')?.addEventListener('click',()=>setTimeout(showLegal,0));sn5$('#languageBtn')?.addEventListener('click',()=>{legalLang=legalLang==='fr'?'en':'fr';sn5$('#languageBtn').textContent=legalLang.toUpperCase();showLegal();toast(legalLang==='fr'?'Français juridique sélectionné':'English legal text selected')});
// Extend command palette and update top-level markers.
PALETTE.splice(2,0,['Opportunity Engine','opportunity'],['Scenario Laboratory','lab']);PALETTE.splice(PALETTE.length-3,0,['Evidence Vault','vault'],['MasterClass','masterclass']);
const rs=sn5$('#releaseStatus');if(rs&&rs.textContent.includes('Locked'))rs.textContent=`AGI Club · Locked · ${SN5_VERSION}`;sn5$('#heroScenarios').textContent=STRATEGIES.length;sn5$('#heroEvents').textContent=DEFAULT_EVENTS.length;const status=sn5$('#ownerVaultSignatureMode');if(status)status.textContent='Domain-bound signature';
// Protected actions for new evidence exports use the existing access API when available.
for(const id of ['#exportEncryptedBundle','#exportPlainBundle','#downloadBoardBrief']){sn5$(id)?.addEventListener('click',async e=>{if(window.GOALOS_AGI_CLUB_ACCESS&&!window.GOALOS_AGI_CLUB_ACCESS.verified){e.preventDefault();e.stopImmediatePropagation();window.GOALOS_AGI_CLUB_ACCESS.lock('Direct AGI Club ownership is required.')}},true)}
renderAll();showLegal();
})();
</script>
'''
s=s.rsplit('</body>',1)[0]+SN5_JS+'\n</body>'+s.rsplit('</body>',1)[1]

# Update footer/version in any remaining content.
s=s.replace('Nine browser-local agents','Twelve browser-local institutional agents')
s=s.replace('nine browser-local agents','twelve browser-local institutional agents')
s=s.replace('six execution stacks','six execution stacks')

INDEX.write_text(s,encoding='utf-8')
# 404 mirrors index for SPA/static resilience.
(SITE/'404.html').write_text(s,encoding='utf-8')

# Bilingual static legal center and documents.
gov=SITE/'governance'; gov.mkdir(exist_ok=True)
legal_index='''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GoalOS Singularity Navigator Ω — Centre juridique</title><style>body{margin:0;font:16px/1.65 system-ui;background:#f5efe2;color:#07162d}.wrap{max-width:1100px;margin:auto;padding:48px 24px}h1,h2{font-family:Georgia,serif}h1{font-size:clamp(2.5rem,6vw,5rem);margin:.2em 0;color:#07162d}.gold{color:#a67220}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.card{padding:22px;border:1px solid #caa45e;background:#fffaf0;border-radius:16px}a{color:#6c4710}.law{background:#07162d;color:#fff;padding:24px;border-radius:18px;margin:24px 0}.meta{letter-spacing:.16em;text-transform:uppercase;font-size:.75rem}.lang{display:flex;gap:10px}</style></head><body><main class="wrap"><div class="meta">MONTREAL.AI · GoalOS Ω · v3.0.0-SN5</div><h1>Centre juridique <span class="gold">bilingue</span></h1><p>Documents publics de gouvernance, d’accès, de vie privée, de sécurité, de transparence de l’IA, de droits et de positionnement réglementaire.</p><div class="law"><b>Cadre exact.</b> Ces documents peuvent réduire les risques et clarifier les responsabilités. Ils ne garantissent aucune immunité et ne remplacent pas les lois impératives ni les professionnels qualifiés.</div><div class="grid"><article class="card"><h2>Français</h2><p><a href="TERMS_FR.html">Conditions d’utilisation</a></p><p><a href="PRIVACY_FR.html">Vie privée</a></p><p><a href="REGULATORY_FR.html">Réglementaire et absence d’offre</a></p><p><a href="RIGHTS_FR.html">Droits et réutilisation</a></p><p><a href="SECURITY_FR.html">Sécurité</a></p></article><article class="card"><h2>English</h2><p><a href="TERMS_EN.html">Terms of use</a></p><p><a href="PRIVACY_EN.html">Privacy</a></p><p><a href="REGULATORY_EN.html">Regulatory and no-offer</a></p><p><a href="RIGHTS_EN.html">Rights and reuse</a></p><p><a href="SECURITY_EN.html">Security</a></p></article><article class="card"><h2>Institution</h2><p><a href="../index.html#legal">Open Legal Center</a></p><p><a href="../AI_USAGE_POLICY.txt">AI Usage Policy</a></p><p><a href="../STATIC_ACCESS_SECURITY_MODEL.md">Static Access Security Model</a></p><p><a href="mailto:info@quebec.ai">info@quebec.ai</a></p></article></div></main></body></html>'''
(gov/'LEGAL_INDEX.html').write_text(legal_index,encoding='utf-8')

docs={
'TERMS_FR.html':('Conditions d’utilisation','Licence personnelle et conditionnelle aux propriétaires directs actuels de l’AGI Club. Usage de recherche, simulation et conception de missions seulement. Interdiction de contournement, extraction, entraînement de modèles, réhébergement public, activité illégale, fausse représentation et utilisation à incidence élevée sans contrôles appropriés. Service fourni tel quel, sous réserve des droits non renonçables. Les lois impératives et obligations professionnelles prévalent.'),
'TERMS_EN.html':('Terms of Use','Personal license conditional on current direct AGI Club ownership. Research, simulation and mission-design use only. No circumvention, scraping, model training, public rehosting, unlawful activity, misrepresentation or high-impact use without appropriate controls. Service provided as is, subject to non-waivable rights. Mandatory law and professional obligations prevail.'),
'PRIVACY_FR.html':('Vie privée','Traitement local au navigateur; aucune analytique, compte, paiement ou télémétrie GoalOS. Le portefeuille, GitHub et le fournisseur RPC peuvent traiter des données techniques selon leurs politiques. Ne saisissez aucun secret ni renseignement réglementé. Contact responsable: info@quebec.ai.'),
'PRIVACY_EN.html':('Privacy','Browser-local processing; no GoalOS analytics, account, payment or telemetry. Wallet, GitHub and RPC providers may process technical data under their policies. Do not enter secrets or regulated information. Privacy contact: info@quebec.ai.'),
'REGULATORY_FR.html':('Réglementaire et absence d’offre','Aucune offre de titres, sollicitation, courtage, conseil d’investissement, service juridique, fiscal, médical ou autre service professionnel réservé. Aucun financement, avantage fiscal ou approbation n’est garanti. Les actions contraignantes exigent des faits exacts, sources actuelles, professionnels qualifiés et autorité responsable.'),
'REGULATORY_EN.html':('Regulatory and No-Offer','No securities offer, solicitation, brokerage, investment advice, legal, tax, medical or other reserved professional service. No funding, fiscal benefit or approval is guaranteed. Binding action requires exact facts, current sources, qualified professionals and responsible authority.'),
'RIGHTS_FR.html':('Droits et réutilisation','MONTREAL.AI conserve les marques, logiciels, méthodes, schémas et matériaux préexistants. Aucune licence implicite de marque, réhébergement commercial, entraînement de modèle ou service concurrent. Chronicle exige provenance, droits, portée, version et révocabilité.'),
'RIGHTS_EN.html':('Rights and Reuse','MONTREAL.AI retains trademarks, software, methods, schemas and pre-existing materials. No implied trademark, commercial rehosting, model-training or competing-service license. Chronicle requires provenance, rights, scope, version and revocability.'),
'SECURITY_FR.html':('Sécurité','Publication statique et locale. Aucun script externe. Les contrôles côté client ne sont pas un DRM serveur confidentiel. Signalez de manière responsable à info@quebec.ai. N’exploitez pas les utilisateurs.'),
'SECURITY_EN.html':('Security','Static local publication. No external scripts. Client-side controls are not confidential server-side DRM. Disclose responsibly to info@quebec.ai. Do not exploit users.')}
for fn,(title,body) in docs.items():
    lang='fr' if fn.endswith('FR.html') else 'en'
    html=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · GoalOS Ω</title><style>body{{max-width:850px;margin:50px auto;padding:0 22px;font:17px/1.7 Georgia,serif;color:#07162d;background:#f7f1e6}}h1{{font-size:3rem}}a{{color:#7b5112}}.box{{border:1px solid #c6a15f;padding:25px;background:#fffaf0;border-radius:16px}}</style></head><body><a href="LEGAL_INDEX.html">← Index</a><h1>{title}</h1><div class="box"><p>{body}</p><p><b>Version:</b> {VERSION} · <b>Reviewed:</b> {DATE}</p></div></body></html>'''
    (gov/fn).write_text(html,encoding='utf-8')

# Additional public policies / discovery files.
(SITE/'AI_USAGE_POLICY.txt').write_text('''GoalOS Singularity Navigator Ω — AI Usage Policy — v3.0.0-SN5\n\nPermitted: human-supervised research, simulation, mission design, education, evidence planning and controlled internal evaluation.\nProhibited without separately reviewed protected deployment: high-impact automated decisions; external transactions; regulated professional practice; biometric/emotion inference; critical-infrastructure control; weapons; unlawful surveillance; unauthorized cybersecurity; processing of sensitive or regulated data.\nAll generated recommendations, scores, scenarios and agent logs are algorithmic outputs and must remain labelled. Binding action requires exact facts, current sources, responsible authority and deployment-specific controls.\n''',encoding='utf-8')
(SITE/'robots.txt').write_text('''User-agent: *\nAllow: /\n\nUser-agent: GPTBot\nDisallow: /goalos-singularity-navigator-omega-agi-club-owner-access/\nUser-agent: Google-Extended\nDisallow: /goalos-singularity-navigator-omega-agi-club-owner-access/\nUser-agent: CCBot\nDisallow: /goalos-singularity-navigator-omega-agi-club-owner-access/\n\n# These directives state publisher preference; technical enforcement depends on crawler compliance.\n''',encoding='utf-8')
well=SITE/'.well-known';well.mkdir(exist_ok=True)
(well/'security.txt').write_text(f'''Contact: mailto:info@quebec.ai\nPreferred-Languages: fr, en\nCanonical: https://montrealai.github.io/goalos-singularity-navigator-omega-agi-club-owner-access/.well-known/security.txt\nExpires: 2027-07-26T23:59:59Z\nPolicy: https://montrealai.github.io/goalos-singularity-navigator-omega-agi-club-owner-access/governance/SECURITY_EN.html\n''',encoding='utf-8')
(SITE/'CITATION.cff').write_text(f'''cff-version: 1.2.0\ntitle: "GoalOS Singularity Navigator Ω — AGI Club GitHub Pages Institution"\nmessage: "Cite GoalOS Ω and MONTREAL.AI when substantially referencing the institutional architecture."\ntype: software\nversion: "{VERSION}"\ndate-released: "{DATE}"\nauthors:\n  - name: "MONTREAL.AI"\nurl: "https://montrealai.github.io/goalos-singularity-navigator-omega-agi-club-owner-access/"\n''',encoding='utf-8')

# PWA manifest/service worker updated.
manifest={"name":"GoalOS Singularity Navigator Ω — AGI Club Institution","short_name":"GoalOS Navigator Ω","description":"Tools to Ride the Singularity — proof-governed institutional navigation for current direct AGI Club owners.","start_url":"./index.html","scope":"./","display":"standalone","background_color":"#040914","theme_color":"#06162d","lang":"fr-CA","categories":["business","productivity","education"]}
(SITE/'manifest.webmanifest').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
cache_files=['./','./index.html','./START_HERE.html','./assets/singularity_apex.webp','./research/'+founding.name,'./research/'+masterclass.name,'./governance/LEGAL_INDEX.html']
(SITE/'sw.js').write_text("const C='goalos-sn5-v1';const A="+json.dumps(cache_files)+";self.addEventListener('install',e=>e.waitUntil(caches.open(C).then(c=>c.addAll(A)).then(()=>self.skipWaiting())));self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==C).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request).then(x=>{const y=x.clone();caches.open(C).then(c=>c.put(e.request,y));return x}).catch(()=>caches.match('./index.html'))))});",encoding='utf-8')

# Updated source schemas / tooling docs.
schemas=SITE/'schemas';schemas.mkdir(exist_ok=True)
(schemas/'proof-bundle.schema.json').write_text(json.dumps({"$schema":"https://json-schema.org/draft/2020-12/schema","title":"GoalOS SN5 Proof Bundle","type":"object","required":["schema","product","version","generatedAt","state","integrity"],"properties":{"schema":{"const":"goalos-singularity-navigator-proof-bundle/3.0"},"version":{"const":VERSION},"generatedAt":{"type":"string","format":"date-time"},"state":{"type":"object"},"integrity":{"type":"object","required":["hashAlgorithm","digest"]}}},indent=2),encoding='utf-8')
receipt_schema={
 '$schema':'https://json-schema.org/draft/2020-12/schema',
 '$id':'https://montrealai.github.io/goalos-singularity-navigator-omega-agi-club-owner-access/schemas/agi_club_owner_access_receipt_v3.schema.json',
 'title':'GoalOS AGI Club Direct Owner Access Receipt v3','type':'object','additionalProperties':True,
 'required':['schema','version','product','name','address','node','mode','issuedAt','expiresAt','verificationBlock','signature','signatureMode','protectionBoundary'],
 'properties':{
  'schema':{'const':'goalos-agi-club-owner-access/3.0'},'version':{'const':VERSION},'product':{'const':PRODUCT},
  'name':{'type':'string','pattern':r'^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.club\.agi\.eth$'},
  'address':{'type':'string','pattern':r'^0x[0-9a-fA-F]{40}$'},'node':{'type':'string','pattern':r'^0x[0-9a-fA-F]{64}$'},
  'mode':{'enum':['ENS Registry direct owner','ENS Name Wrapper ERC-1155 direct owner']},
  'issuedAt':{'type':'string','format':'date-time'},'expiresAt':{'type':'string','format':'date-time'},
  'verificationBlock':{'type':'integer','minimum':1},'signature':{'type':'string','pattern':r'^0x[0-9a-fA-F]+$'},
  'signatureMode':{'enum':['eip712-v4','personal_sign-domain-bound']},'protectionBoundary':{'type':'string','minLength':20}
 }
}
(schemas/'agi_club_owner_access_receipt_v3.schema.json').write_text(json.dumps(receipt_schema,ensure_ascii=False,indent=2),encoding='utf-8')


# README / VERSION / deployment guide.
(SITE/'VERSION.json').write_text(json.dumps({"product":PRODUCT,"edition":"AGI Club GitHub Pages Institution","version":VERSION,"releaseDate":DATE,"canonicalPath":"/goalos-singularity-navigator-omega-agi-club-owner-access/","candidateArchitectures":12,"institutionalAgents":12,"boundedAGIJobs":21,"proofReceipts":15,"views":16,"legalLanguages":["fr","en"],"legalVersion":LEGAL_VERSION,"snapshot":DATE},ensure_ascii=False,indent=2),encoding='utf-8')
(SITE/'README.md').write_text(f'''# {PRODUCT}\n\n## AGI Club GitHub Pages Institution — {VERSION}\n\nA complete browser-local proof-governed navigation institution for the current direct owner of an exact one-label `label.club.agi.eth` name.\n\nCanonical URL: `https://montrealai.github.io/goalos-singularity-navigator-omega-agi-club-owner-access/`\n\nSee `START_HERE.html`, `GITHUB_PAGES_DEPLOYMENT_GUIDE.md`, `governance/LEGAL_INDEX.html`, `documentation/QA_REPORT.md` and `MANIFEST.json`.\n''',encoding='utf-8')
(SITE/'LICENSE_AGI_CLUB_OWNER_ONLY.txt').write_text('''GoalOS Singularity Navigator Ω — Conditional AGI Club Owner License\n\nOrdinary use is licensed only to the connected wallet that currently and directly owns an eligible exact one-label label.club.agi.eth name, subject to the bilingual Terms of Use. Source visibility through GitHub Pages does not grant a license to circumvent the gate, scrape, train models, rehost, commercialize, impersonate, or create a confusingly similar branded institution. Mandatory law and non-waivable rights prevail.\n''',encoding='utf-8')
(SITE/'STATIC_ACCESS_SECURITY_MODEL.md').write_text('''# Static Access Security Model\n\nThe AGI Club gate verifies current direct ENS ownership in the browser, obtains a domain-bound signature, creates a temporary local receipt, revalidates ownership and fails closed. GitHub Pages publishes source to the public. The gate is therefore an eligibility, provenance, conditional-license and community-access mechanism; it is not confidential server-side DRM or regulated identity certification. Sensitive work requires a separately reviewed private deployment.\n''',encoding='utf-8')
(SITE/'GITHUB_PAGES_DEPLOYMENT_GUIDE.md').write_text(f'''# GitHub Pages Deployment Guide — {VERSION}\n\n1. Unzip the deployment ZIP locally.\n2. Copy `.nojekyll` and `goalos-singularity-navigator-omega-agi-club-owner-access/` directly into the root of `MontrealAI/MontrealAI.github.io`.\n3. Do not upload the ZIP as the site. Do not add another enclosing directory. Do not delete unrelated repository content.\n4. Commit and publish.\n5. Open `https://montrealai.github.io/goalos-singularity-navigator-omega-agi-club-owner-access/`.\n6. Test one real direct unwrapped owner and one real direct wrapped owner if available; verify wrong-owner, nested-name and network-change denial.\n7. Confirm the bilingual Legal Center, founding paper and MasterClass open.\n''',encoding='utf-8')

# Start Here page.
start=f'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Start Here · GoalOS Singularity Navigator Ω · {VERSION}</title><style>body{{margin:0;background:#040914;color:#f8efd9;font:16px/1.55 system-ui}}main{{max-width:1050px;margin:auto;padding:60px 24px}}h1{{font:clamp(3rem,7vw,6.7rem)/.94 Georgia,serif;margin:.15em 0;background:linear-gradient(120deg,#fff0bd,#d7a43d);-webkit-background-clip:text;color:transparent}}h2{{font-family:Georgia,serif}}.hero{{padding:40px;border:1px solid #aa7d29;border-radius:24px;background:linear-gradient(135deg,#081a35,#0b0b1d)}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px;margin-top:22px}}a{{display:block;padding:18px;border:1px solid #8f6a28;border-radius:14px;color:#f5d681;text-decoration:none;background:#071326}}a b{{display:block;color:white;font-size:1.1rem}}.law{{border-left:4px solid #e6ba5f;padding:15px 18px;background:#0c1830;margin-top:22px}}</style></head><body><main><section class="hero"><div>MONTREAL.AI · AGI Club GitHub Pages Institution · {VERSION}</div><h1>GoalOS Singularity Navigator Ω</h1><h2>Tools to Ride the Singularity</h2><p>Détecter ce qui a changé. Prouver ce qui compte. Déployer seulement ce qui passe. Composer seulement ce qui survit à la réalité.</p><div class="law"><b>Current direct AGI Club owner access.</b> Ordinary use requires current direct ownership of an exact one-label <code>label.club.agi.eth</code> name.</div></section><div class="grid"><a href="index.html"><b>Enter the Institution</b>Open the AGI Club owner gate and complete GoalOS command system.</a><a href="research/{founding.name}"><b>Founding Paper</b>Singularity-Time Navigation Constitution · 140 pages.</a><a href="research/{masterclass.name}"><b>MasterClass</b>Complete operational curriculum · 170 pages.</a><a href="governance/LEGAL_INDEX.html"><b>Centre juridique bilingue</b>French-first legal center with English versions.</a><a href="documentation/QA_REPORT.md"><b>QA Report</b>Automated, visual, static and clean-room assurance.</a><a href="MANIFEST.json"><b>Manifest</b>Machine-readable release inventory and integrity record.</a></div></main></body></html>'''
(SITE/'START_HERE.html').write_text(start,encoding='utf-8')

print('Built SN5 site:',SITE)
print('index bytes',INDEX.stat().st_size)
