'use strict';
(()=>{
const CFG={product:'GoalOS Singularity Office Ω',release:'v2.0.0-SO2',suffix:'club.agi.eth',chainId:'0x1',registry:'0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',wrappers:[{address:'0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401',label:'Official ENS Name Wrapper'}],sessionKey:'goalos-singularity-office-access-v1',sessionMinutes:30,recheckMinutes:5,idleMinutes:10};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let access=null,lastActivity=Date.now(),recheckTimer=null,idleTimer=null,loadedLicense=null,publicKey=null;const enc=new TextEncoder();
function t(k){return window.GoalOSApp?.t?.(k)||window.GOALOS_I18N?.en?.[k]||k}
function toast(title,msg){window.GoalOSApp?.toast?.(title,msg)}
function setStatus(msg,state='warn'){const n=$('#gateStatus');if(n){n.textContent=msg;n.dataset.state=state}}
function b64uToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function bytesToB64u(b){let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function canonical(obj){if(obj===null||typeof obj!=='object')return JSON.stringify(obj);if(Array.isArray(obj))return'['+obj.map(canonical).join(',')+']';return'{'+Object.keys(obj).sort().map(k=>JSON.stringify(k)+':'+canonical(obj[k])).join(',')+'}'}
async function loadPublicKey(){if(publicKey)return publicKey;const embedded=window.__GOALOS_EMBEDDED_PACKS__?.publicKey;const j=embedded||await fetch('data/publisher-public-key.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Publisher key unavailable');return r.json()});publicKey=await crypto.subtle.importKey('jwk',j,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return publicKey}
async function verifySignedObject(obj){const sig=obj?.signature;if(!sig)return false;const payload={...obj};delete payload.signature;delete payload.signatureAlgorithm;delete payload.publicKeyId;const key=await loadPublicKey();return crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,b64uToBytes(sig),enc.encode(canonical(payload)))}
function originAllowed(patterns=[]){if(location.protocol==='file:')return patterns.some(x=>x==='file://'||x==='*');const origin=location.origin;return patterns.some(p=>{if(p==='*'||p===origin)return true;if(p.endsWith(':*'))return origin.startsWith(p.slice(0,-1));return false})}
async function validateLicense(obj){if(!obj||obj.schema!=='goalos.license.v1')throw new Error('Unrecognized GoalOS licence schema.');if(obj.product!==CFG.product)throw new Error('Licence is for another GoalOS product.');if(Number(obj.releaseMajor)!==1)throw new Error('Licence is not compatible with this release generation.');if(!await verifySignedObject(obj))throw new Error('Publisher signature is invalid.');const now=Date.now();if(Date.parse(obj.notBefore)>now)throw new Error('Licence is not active yet.');if(Date.parse(obj.expiresAt)<=now)throw new Error('Licence has expired.');if(!originAllowed(obj.origins||[]))throw new Error('Licence does not authorize this deployment origin.');return obj}
function cleanLabel(v){const x=String(v||'').trim().toLowerCase();if(!x)return{ok:false,error:'Enter the first label of the direct club subdomain.'};if(x.includes('.'))return{ok:false,error:'Enter one label only.'};if(x.length>63||!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(x))return{ok:false,error:'Use lowercase ASCII letters, digits and internal hyphens.'};return{ok:true,label:x,name:`${x}.${CFG.suffix}`}}
const MASK64=(1n<<64n)-1n,ROT=[0,1,62,28,27,36,44,6,55,20,3,10,43,25,39,41,45,15,21,8,18,2,61,56,14],RC=[0x1n,0x8082n,0x800000000000808an,0x8000000080008000n,0x808bn,0x80000001n,0x8000000080008081n,0x8000000000008009n,0x8an,0x88n,0x80008009n,0x8000000an,0x8000808bn,0x800000000000008bn,0x8000000000008089n,0x8000000000008003n,0x8000000000008002n,0x8000000000000080n,0x800an,0x800000008000000an,0x8000000080008081n,0x8000000000008080n,0x80000001n,0x8000000080008008n];
function rotl(x,n){n=BigInt(n);return n===0n?x&MASK64:((x<<n)|(x>>(64n-n)))&MASK64}function kF(s){for(let r=0;r<24;r++){const C=Array(5),D=Array(5),B=Array(25);for(let x=0;x<5;x++)C[x]=s[x]^s[x+5]^s[x+10]^s[x+15]^s[x+20];for(let x=0;x<5;x++)D[x]=C[(x+4)%5]^rotl(C[(x+1)%5],1);for(let x=0;x<5;x++)for(let y=0;y<5;y++)s[x+5*y]=(s[x+5*y]^D[x])&MASK64;for(let x=0;x<5;x++)for(let y=0;y<5;y++)B[y+5*((2*x+3*y)%5)]=rotl(s[x+5*y],ROT[x+5*y]);for(let x=0;x<5;x++)for(let y=0;y<5;y++)s[x+5*y]=(B[x+5*y]^((~B[(x+1)%5+5*y])&B[(x+2)%5+5*y]))&MASK64;s[0]=(s[0]^RC[r])&MASK64}}
function k256(input){const bytes=typeof input==='string'?enc.encode(input):input,rate=136,n=Math.ceil((bytes.length+1)/rate)*rate,p=new Uint8Array(n);p.set(bytes);p[bytes.length]^=1;p[n-1]^=128;const s=Array(25).fill(0n);for(let o=0;o<p.length;o+=rate){for(let i=0;i<rate;i++)s[Math.floor(i/8)]^=BigInt(p[o+i])<<BigInt(8*(i%8));kF(s)}const out=new Uint8Array(32);for(let i=0;i<32;i++)out[i]=Number((s[Math.floor(i/8)]>>BigInt(8*(i%8)))&255n);return out}
function hx(b){return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}function cat(a,b){const o=new Uint8Array(a.length+b.length);o.set(a);o.set(b,a.length);return o}function namehash(name){let node=new Uint8Array(32);for(const label of name.toLowerCase().split('.').reverse())node=k256(cat(node,k256(label)));return'0x'+hx(node)}
function parseAddr(data,word=0){const h=String(data||'').replace(/^0x/,'');if(h.length<(word+1)*64)throw new Error('Malformed address response.');return'0x'+h.slice(word*64+24,word*64+64)}function parseUint(data,word=0){const h=String(data||'').replace(/^0x/,'');return BigInt('0x'+(h.slice(word*64,(word+1)*64)||'0'))}function same(a,b){return String(a||'').toLowerCase()===String(b||'').toLowerCase()}function short(a){return a?`${a.slice(0,6)}…${a.slice(-4)}`:'—'}function randomHex(n=16){const b=new Uint8Array(n);crypto.getRandomValues(b);return hx(b)}
async function provider(){if(!window.ethereum)throw new Error('No injected Ethereum wallet detected.');return window.ethereum}async function accounts(request=true){const p=await provider(),a=await p.request({method:request?'eth_requestAccounts':'eth_accounts'});if(!a?.[0])throw new Error('Wallet account unavailable.');return a[0]}async function mainnet(p,switchAllowed=true){let c=String(await p.request({method:'eth_chainId'})).toLowerCase();if(c!=='0x1'){if(!switchAllowed)throw new Error('Ethereum Mainnet is required.');await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1'}]});c=String(await p.request({method:'eth_chainId'})).toLowerCase();if(c!=='0x1')throw new Error('Ethereum Mainnet is required.')}return c}async function call(to,data){return(await provider()).request({method:'eth_call',params:[{to,data},'latest']})}async function blockNumber(){return Number(BigInt(await(await provider()).request({method:'eth_blockNumber'})))}
async function localOwner(name,address){const node=namehash(name),ownerRaw=await call(CFG.registry,'0x02571be3'+node.slice(2)),registryOwner=parseAddr(ownerRaw);if(same(registryOwner,address))return{name,address,node,mode:'ENS Registry direct owner',registryOwner,expiry:null};const wrapper=CFG.wrappers.find(w=>same(registryOwner,w.address));if(!wrapper)throw new Error('Connected wallet is not the direct Registry owner and the name is not held by the recognized Name Wrapper.');const wrappedOwner=parseAddr(await call(wrapper.address,'0x6352211e'+node.slice(2)));if(!same(wrappedOwner,address))throw new Error('Connected wallet is not the direct wrapped-name owner.');const data=await call(wrapper.address,'0x0178fe3f'+node.slice(2)),dataOwner=parseAddr(data,0),expiry=Number(parseUint(data,2));if(!same(dataOwner,address))throw new Error('Wrapped-name ownership data does not match the connected wallet.');if(expiry&&expiry<=Math.floor(Date.now()/1000))throw new Error('Wrapped AGI Club name has expired.');return{name,address,node,mode:'ENS Name Wrapper direct owner',registryOwner,wrapperAddress:wrapper.address,expiry}}
function typedData(name,address,issued,expires,nonce){return{domain:{name:CFG.product,version:'1',chainId:1},message:{wallet:address,qualifyingName:name,product:CFG.product,release:CFG.release,issuedAt:issued,expiresAt:expires,nonce,origin:location.origin||'file://'},primaryType:'OfficeAccess',types:{EIP712Domain:[{name:'name',type:'string'},{name:'version',type:'string'},{name:'chainId',type:'uint256'}],OfficeAccess:[{name:'wallet',type:'address'},{name:'qualifyingName',type:'string'},{name:'product',type:'string'},{name:'release',type:'string'},{name:'issuedAt',type:'string'},{name:'expiresAt',type:'string'},{name:'nonce',type:'string'},{name:'origin',type:'string'}]}}}
async function signAccess(name,address){const p=await provider(),issued=new Date().toISOString(),expires=new Date(Date.now()+CFG.sessionMinutes*60000).toISOString(),nonce=randomHex();const td=typedData(name,address,issued,expires,nonce);try{return{issued,expires,nonce,signatureMode:'EIP-712',signature:await p.request({method:'eth_signTypedData_v4',params:[address,JSON.stringify(td)]})}}catch{const msg=`${CFG.product}\nCurrent direct owner access\nName: ${name}\nWallet: ${address}\nRelease: ${CFG.release}\nIssued: ${issued}\nExpires: ${expires}\nNonce: ${nonce}\nOrigin: ${location.origin||'file://'}`;return{issued,expires,nonce,signatureMode:'personal_sign',signature:await p.request({method:'personal_sign',params:['0x'+hx(enc.encode(msg)),address]})}}
}
function active(){return access&&Date.parse(access.expiresAt)>Date.now()}
function save(){try{access?sessionStorage.setItem(CFG.sessionKey,JSON.stringify(access)):sessionStorage.removeItem(CFG.sessionKey)}catch{}}
function updateChip(){const chip=$('#accessChip');if(!chip)return;if(!active()){chip.textContent='Locked';chip.dataset.state='locked'}else{chip.textContent=access.mode==='preview'?'Preview':access.mode==='license'?`${access.license.tier} · ${access.license.licensee}`:access.name;chip.dataset.state='active'}}
function schedule(){clearInterval(recheckTimer);clearInterval(idleTimer);if(!active())return;lastActivity=Date.now();idleTimer=setInterval(()=>{if(Date.now()-lastActivity>CFG.idleMinutes*60000)lock('Session locked after inactivity.');if(!active())lock('Access session expired.')},1000);if(access.mode==='agi')recheckTimer=setInterval(()=>revalidate('scheduled'),CFG.recheckMinutes*60000)}
function unlock(obj){access=obj;save();document.body.classList.remove('access-locked');$('#accessGate').hidden=true;updateChip();schedule();document.dispatchEvent(new CustomEvent('goalos:access',{detail:access}));window.GoalOSApp?.renderAccess?.();}
function lock(reason='Access required.'){access=null;save();clearInterval(recheckTimer);clearInterval(idleTimer);document.body.classList.add('access-locked');$('#accessGate').hidden=false;updateChip();setStatus(reason,'warn');document.dispatchEvent(new CustomEvent('goalos:access',{detail:null}));}
async function verifyAgi(){const n=cleanLabel($('#agiLabel').value);if(!n.ok)return setStatus(n.error,'bad');if(!$('#agiOwner').checked||!$('#agiTerms').checked||!$('#agiBoundary').checked)return setStatus('Accept all access conditions first.','bad');try{setStatus('Connecting wallet and verifying direct ownership…','warn');const p=await provider(),address=await accounts(true);await mainnet(p,true);const own=await localOwner(n.name,address),sig=await signAccess(n.name,address);const block=await blockNumber();unlock({mode:'agi',name:n.name,address,ownershipMode:own.mode,verificationBlock:block,lastVerifiedAt:new Date().toISOString(),issuedAt:sig.issued,expiresAt:sig.expires,signature:sig.signature,signatureMode:sig.signatureMode,release:CFG.release});setStatus('Direct AGI Club ownership verified.','ok')}catch(e){setStatus(String(e?.message||e),'bad')}}
async function revalidate(reason='manual'){if(!active())return lock('Access session expired.'),false;if(access.mode==='preview')return true;if(access.mode==='license'){try{await validateLicense(access.license);return true}catch(e){lock(String(e.message||e));return false}}try{const p=await provider();await mainnet(p,false);const address=await accounts(false);if(!same(address,access.address))throw new Error('Wallet account changed.');await localOwner(access.name,address);access.lastVerifiedAt=new Date().toISOString();access.verificationBlock=await blockNumber();save();updateChip();return true}catch(e){lock(`Ownership verification failed: ${String(e?.message||e)}`);return false}}
async function restore(){try{const x=JSON.parse(sessionStorage.getItem(CFG.sessionKey)||'null');if(!x)return false;access=x;if(!active())throw new Error('Prior session expired.');if(access.mode==='license')await validateLicense(access.license);if(access.mode==='agi')await revalidate('restore');unlock(access);return true}catch(e){access=null;save();setStatus(String(e.message||e),'warn');return false}}
function exportReceipt(){if(!access)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(access,null,2)],{type:'application/json'}));a.download=`GoalOS_Singularity_Office_Access_Receipt_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function assert(action='protected action'){if(!active()){lock('Access required.');return false}if(access.mode==='preview'){toast('Preview mode',`${action} is disabled in public preview.`);return false}if(!await revalidate(action))return false;return true}
function accessDetails(){if(!access)return{mode:'locked'};return access}
function bindTabs(){$$('.access-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.access-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.access-pane').forEach(p=>p.classList.toggle('active',p.dataset.accessPane===b.dataset.accessTab))}))}
function bind(){['pointerdown','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,()=>lastActivity=Date.now(),{passive:true}));bindTabs();['#agiLabel','#agiOwner','#agiTerms','#agiBoundary'].forEach(s=>$(s)?.addEventListener(s==='#agiLabel'?'input':'change',()=>{$('#agiVerify').disabled=!(cleanLabel($('#agiLabel').value).ok&&$('#agiOwner').checked&&$('#agiTerms').checked&&$('#agiBoundary').checked)}));$('#agiVerify').addEventListener('click',verifyAgi);$('#agiRestore').addEventListener('click',restore);$('#previewUnlock').addEventListener('click',()=>unlock({mode:'preview',issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+60*60000).toISOString(),release:CFG.release}));
 const file=$('#licenseFile');file.addEventListener('change',async()=>{try{const obj=JSON.parse(await file.files[0].text());loadedLicense=await validateLicense(obj);$('#licenseeProof').textContent=loadedLicense.licensee;$('#tierProof').textContent=loadedLicense.tier;$('#expiryProof').textContent=new Date(loadedLicense.expiresAt).toLocaleString();$('#licenseStatusProof').textContent='Valid';$('#licenseUnlock').disabled=!$('#licenseTerms').checked;setStatus('Signed institutional licence verified.','ok')}catch(e){loadedLicense=null;$('#licenseStatusProof').textContent='Invalid';setStatus(String(e.message||e),'bad')}});$('#licenseTerms').addEventListener('change',()=>$('#licenseUnlock').disabled=!(loadedLicense&&$('#licenseTerms').checked));$('#licenseUnlock').addEventListener('click',()=>{if(!loadedLicense)return;unlock({mode:'license',license:loadedLicense,issuedAt:new Date().toISOString(),expiresAt:loadedLicense.expiresAt,release:CFG.release});setStatus('Institution licence active.','ok')});
 $('#accessChip').addEventListener('click',()=>{window.GoalOSApp?.renderAccess?.();$('#accessDialog').showModal()});$('#revalidateAccess').addEventListener('click',()=>revalidate('manual'));$('#exportAccessReceipt').addEventListener('click',exportReceipt);$('#lockOffice').addEventListener('click',()=>{$('#accessDialog').close();lock('Office locked by user.')});
 $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog')?.close()));
 if(window.ethereum?.on){window.ethereum.on('accountsChanged',()=>{if(access?.mode==='agi')lock('Wallet account changed.')});window.ethereum.on('chainChanged',()=>{if(access?.mode==='agi')lock('Wallet network changed.')});window.ethereum.on('disconnect',()=>{if(access?.mode==='agi')lock('Wallet disconnected.')})}
 window.addEventListener('focus',()=>{if(access?.mode==='agi')revalidate('focus')});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&access?.mode==='agi')revalidate('visibility')});restore()}
window.GoalOSAccess={get current(){return access},active,assert,revalidate,lock,unlock,accessDetails,validateLicense,verifySignedObject};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
