'use strict';
(()=>{
const RELEASE='v2.0.0-SO2';
const WEIGHTS=[
 {id:'upside',en:'Verified upside',fr:'Potentiel vérifié',default:86},
 {id:'speed',en:'Speed',fr:'Vitesse',default:72},
 {id:'proof',en:'Evidence',fr:'Preuve',default:90},
 {id:'authority',en:'Authority fit',fr:'Compatibilité d’autorité',default:92},
 {id:'resilience',en:'Resilience',fr:'Résilience',default:86},
 {id:'human',en:'Human agency',fr:'Agentivité humaine',default:82},
 {id:'reversibility',en:'Reversibility',fr:'Réversibilité',default:84},
 {id:'capital',en:'Capital efficiency',fr:'Efficience du capital',default:75},
 {id:'compounding',en:'Compounding',fr:'Composition',default:92}
];
const CAPABILITIES=[
 ['intelligence','Intelligence','Intelligence'],['data','Data','Données'],['tools','Tools & connectors','Outils et connecteurs'],['authority','Identity & authority','Identité et autorité'],['evidence','Evidence & evaluation','Preuve et évaluation'],['human','Human agency','Agentivité humaine'],['security','Security & resilience','Sécurité et résilience'],['distribution','Distribution & markets','Distribution et marchés'],['capital','Capital','Capital'],['infrastructure','Compute & infrastructure','Calcul et infrastructure']
];
const ARCHITECTURES=[
 {id:'balanced',en:'Proof-First Adaptive Office',fr:'Bureau adaptatif — preuve d’abord',summaryEn:'Balanced frontier adoption under explicit authority, evidence and rollback.',summaryFr:'Adoption équilibrée de la frontière sous autorité, preuve et retour arrière explicites.',base:{upside:84,speed:78,proof:94,authority:94,resilience:91,human:88,reversibility:91,capital:76,compounding:93},complexity:62,proofDebt:24},
 {id:'capture',en:'Frontier Capture Office',fr:'Bureau de capture de la frontière',summaryEn:'Aggressively tests new capability and moves the best verified missions into production.',summaryFr:'Teste agressivement les nouvelles capacités et met en production les meilleures missions vérifiées.',base:{upside:98,speed:95,proof:72,authority:66,resilience:61,human:62,reversibility:55,capital:72,compounding:91},complexity:82,proofDebt:58},
 {id:'sovereign',en:'Sovereign Capability Core',fr:'Noyau de capacité souveraine',summaryEn:'Owns strategic models, data, evaluation and institutional memory while renting non-core layers.',summaryFr:'Possède les modèles, données, évaluations et mémoire stratégiques, et loue les couches non essentielles.',base:{upside:88,speed:62,proof:91,authority:97,resilience:96,human:89,reversibility:84,capital:57,compounding:97},complexity:78,proofDebt:34},
 {id:'resilience',en:'Resilience-First Office',fr:'Bureau — résilience d’abord',summaryEn:'Protects continuity, provider optionality and recovery before expanding autonomy.',summaryFr:'Protège la continuité, l’optionnalité des fournisseurs et la reprise avant d’étendre l’autonomie.',base:{upside:70,speed:52,proof:95,authority:96,resilience:100,human:91,reversibility:98,capital:67,compounding:76},complexity:52,proofDebt:14},
 {id:'human',en:'Human Agency Transition Office',fr:'Bureau de transition de l’agentivité humaine',summaryEn:'Redesigns roles, consent, incentives and capability ownership around human authority.',summaryFr:'Redessine les rôles, le consentement, les incitatifs et la propriété des capacités autour de l’autorité humaine.',base:{upside:80,speed:64,proof:86,authority:93,resilience:84,human:100,reversibility:90,capital:66,compounding:87},complexity:64,proofDebt:28},
 {id:'capacity',en:'Productive Capacity Office',fr:'Bureau de capacité productive',summaryEn:'Converts verified value into compute, energy, data, laboratories and infrastructure.',summaryFr:'Convertit la valeur vérifiée en calcul, énergie, données, laboratoires et infrastructure.',base:{upside:96,speed:58,proof:82,authority:80,resilience:79,human:70,reversibility:47,capital:62,compounding:100},complexity:91,proofDebt:56},
 {id:'global',en:'Global Launch & Expansion Office',fr:'Bureau de lancement et d’expansion mondiale',summaryEn:'Continuously optimizes jurisdictions, capital, talent, public support and market entry.',summaryFr:'Optimise continuellement les juridictions, le capital, les talents, le soutien public et l’accès aux marchés.',base:{upside:91,speed:72,proof:88,authority:89,resilience:82,human:78,reversibility:73,capital:91,compounding:92},complexity:84,proofDebt:42},
 {id:'operations',en:'High-Frequency Operations Office',fr:'Bureau d’opérations à haute fréquence',summaryEn:'Turns recurring enterprise requests into governed missions with fast evidence loops.',summaryFr:'Transforme les demandes récurrentes en missions gouvernées avec des boucles de preuve rapides.',base:{upside:86,speed:94,proof:86,authority:87,resilience:82,human:77,reversibility:86,capital:90,compounding:94},complexity:72,proofDebt:31},
 {id:'research',en:'Research Acceleration Office',fr:'Bureau d’accélération de la recherche',summaryEn:'Runs hypothesis, experiment, replication and evidence loops across scientific programmes.',summaryFr:'Exécute des boucles d’hypothèses, d’expériences, de réplication et de preuve pour les programmes scientifiques.',base:{upside:95,speed:86,proof:93,authority:76,resilience:72,human:86,reversibility:90,capital:69,compounding:98},complexity:77,proofDebt:38},
 {id:'portfolio',en:'Portfolio Capital Office',fr:'Bureau de capital de portefeuille',summaryEn:'Allocates capital across missions, options and successor architectures using verified contribution.',summaryFr:'Alloue le capital entre missions, options et architectures successeures selon la contribution vérifiée.',base:{upside:90,speed:76,proof:89,authority:90,resilience:87,human:72,reversibility:80,capital:100,compounding:96},complexity:75,proofDebt:35},
 {id:'public',en:'Public-Interest Mission Office',fr:'Bureau de missions d’intérêt public',summaryEn:'Combines transparency, public authority, participation and measurable institutional value.',summaryFr:'Combine transparence, autorité publique, participation et valeur institutionnelle mesurable.',base:{upside:84,speed:52,proof:98,authority:100,resilience:92,human:98,reversibility:86,capital:66,compounding:86},complexity:86,proofDebt:30},
 {id:'reserve',en:'Minimal-Regret Reserve Office',fr:'Bureau de réserve à regret minimal',summaryEn:'Preserves optionality and waits for the smallest decisive proof before irreversible commitment.',summaryFr:'Préserve l’optionnalité et attend la plus petite preuve décisive avant tout engagement irréversible.',base:{upside:66,speed:44,proof:96,authority:97,resilience:99,human:92,reversibility:100,capital:83,compounding:70},complexity:38,proofDebt:10}
];
const COUNCIL=[
 ['frontier','Frontier Sentinel','Sentinelle de la frontière'],['capability','Capability Cartographer','Cartographe des capacités'],['auction','Model Auctioneer','Commissaire aux modèles'],['mission','Mission Compiler','Compilateur de missions'],['authority','Authority Governor','Gouverneur de l’autorité'],['adversarial','Adversarial Auditor','Auditeur contradictoire'],['evidence','Evidence Verifier','Vérificateur de preuves'],['successor','Successor Architect','Architecte des successeurs'],['capacity','Capacity Strategist','Stratège de la capacité'],['portfolio','Opportunity Portfolio Architect','Architecte du portefeuille d’opportunités'],['privacy','Rights & Privacy Steward','Gardien des droits et de la vie privée'],['externalities','Institutional Externalities Auditor','Auditeur des externalités institutionnelles']
];
const RECEIPTS=[
 ['objective','Consequential objective','Objectif conséquent'],['principal','Accountable principal','Principal responsable'],['sources','Current official sources','Sources officielles actuelles'],['authority','Authority Envelope','Enveloppe d’autorité'],['docket','Evidence Docket','Dossier de preuve'],['validation','Independent validation','Validation indépendante'],['acceptance','Accountable acceptance','Acceptation responsable'],['rights','Rights and scope','Droits et portée'],['transparency','AI transparency','Transparence de l’IA'],['rollback','Rollback and continuity','Retour arrière et continuité'],['currentness','Currentness and expiry','Actualité et expiration'],['externalities','Externalities and impact','Externalités et impact'],['successor','Fresh-successor test','Test de successeur neuf'],['chronicle','Chronicle admission','Admission Chronicle'],['reinvestment','Productive reinvestment authority','Autorité de réinvestissement productif']
];
const MISSION_TEMPLATES=[
 ['frontier-scan','Frontier capability and regulatory delta','Delta de capacité et de réglementation','RADAR'],
 ['source-refresh','Official-source refresh and impact map','Actualisation des sources officielles et carte d’impact','RADAR'],
 ['twin-baseline','Institutional Capability Twin baseline','État de référence du Jumeau de capacité','TWIN'],
 ['architecture-auction','Architecture auction and stress test','Enchère d’architectures et test de stress','AUCTION'],
 ['model-auction','Model and agent execution-stack auction','Enchère des modèles et de la pile d’exécution','AUCTION'],
 ['authority-map','Agent identity and authority map','Carte d’identité et d’autorité des agents','AUTHORITY'],
 ['proof-debt','Retire top Value-of-Proof item','Retirer la principale dette Valeur-de-la-preuve','PROOF'],
 ['security-review','Trajectory security and injection review','Revue de sécurité de trajectoire et d’injection','RESILIENCE'],
 ['resilience-drill','Provider failover and rollback drill','Exercice de relève et de retour arrière','RESILIENCE'],
 ['mission-pack','Compile highest-value Mission Pack','Compiler le Mission Pack de plus grande valeur','MISSION'],
 ['bounded-pilot','Run bounded production pilot','Exécuter un pilote de production borné','MISSION'],
 ['independent-verification','Independent result verification','Vérification indépendante du résultat','PROOF'],
 ['acceptance','Stakeholder acceptance and exception decision','Acceptation des parties et décision d’exception','AUTHORITY'],
 ['chronicle-admission','Chronicle admission or rejection','Admission ou rejet Chronicle','CHRONICLE'],
 ['successor-test','Fresh successor mission comparison','Comparaison sur une mission successeure neuve','CHRONICLE'],
 ['value-ledger','Update Verified Value Ledger','Mettre à jour le registre de valeur vérifiée','VALUE'],
 ['capital-allocation','Capital-to-Capacity allocation','Allocation Capital-vers-Capacité','VALUE'],
 ['board-brief','Board command brief','Sommaire de commandement au conseil','BOARD'],
 ['weekly-office','Weekly Office command','Commandement hebdomadaire du Bureau','CADENCE'],
 ['quarterly-reconstitution','Quarterly institutional reconstitution','Reconstitution institutionnelle trimestrielle','CADENCE'],
 ['annual-review','Annual authority, resilience and rights review','Revue annuelle de l’autorité, de la résilience et des droits','CADENCE']
];
const MONITOR_DOMAINS=[
 ['functionality','Functionality','Fonctionnalité'],['operations','Operations','Opérations'],['human','Human factors','Facteurs humains'],['security','Security','Sécurité'],['compliance','Compliance','Conformité'],['impact','Large-scale impacts','Impacts à grande échelle']
];
const CADENCE={
 continuous:['Monitor official source changes','Watch authority expiry and access changes','Detect material frontier events','Track incidents and blocked actions'],
 daily:['Review urgent alerts','Revalidate high-risk missions','Inspect critical provider health'],
 weekly:['Issue Frontier & Opportunity Brief','Run mission portfolio command','Retire highest Value-of-Proof item','Update Verified Value Ledger'],
 monthly:['Run capability and model auction','Review capital allocation','Review access, privacy and security evidence','Update institution risk register'],
 quarterly:['Reconstitute competing architectures','Run fresh-successor comparison','Review provider concentration and reversibility','Issue board architecture report'],
 annual:['Full authority and rights review','Resilience and incident-response exercise','Privacy governance and retention review','Complete Office constitution renewal'],
 material:['Activate 72-hour Capability Shock Protocol','Freeze affected transactions','Create impact graph and successor scenarios','Escalate to accountable authority']
};
function hashString(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function clamp(x,a=0,b=100){return Math.max(a,Math.min(b,x))}
function quantile(arr,q){const x=[...arr].sort((a,b)=>a-b),p=(x.length-1)*q,b=Math.floor(p),r=p-b;return x[b+1]!==undefined?x[b]+r*(x[b+1]-x[b]):x[b]}
function defaultProfile(){return{
 institutionName:'Apex Institution',institutionType:'Company',objective:'Preserve strategic control, deploy the strongest verified capabilities and compound accepted gains into durable productive capacity.',preserve:'Founder control, institutional purpose, lawful authority, customer trust, privacy, reversibility and the right to stop.',horizon:365,capitalBand:3,stakes:82,sensitivity:48,
 weights:Object.fromEntries(WEIGHTS.map(w=>[w.id,w.default])),capability:Object.fromEntries(CAPABILITIES.map((c,i)=>[c[0],{current:45+(i%4)*7,target:82+(i%3)*5,disposition:i<2?'OWN':i<5?'UPGRADE':i<8?'TEST':'RENT'}]))
}}
function defaultState(){const p=defaultProfile();return{
 schema:'goalos.singularity-office.state.v1',release:RELEASE,workspaceId:'workspace-'+Date.now().toString(36),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),language:'en',profile:p,
 access:{mode:'locked'},sourcePack:null,modelCatalog:null,auction:null,council:[],missions:[],proofDebt:[],receipts:Object.fromEntries(RECEIPTS.map(r=>[r[0],false])),authorities:[{id:'auth-1',role:'Accountable sponsor',holder:'Institution lead',scope:'Mission constitution and acceptance',expires:null,status:'active'}],bundles:[],ledger:[],chronicle:[],valueEntries:[],capitalAllocation:{intelligence:20,evidence:20,data:12,distribution:14,talent:12,infrastructure:14,reserve:8},incidents:[],cadence:{},runtime:{endpoint:'',connected:false},lastRun:null
 }}
function profileFactor(profile,arch){let adj=0;const stakes=Number(profile.stakes||60),sens=Number(profile.sensitivity||48),capital=Number(profile.capitalBand||3);if(stakes>80){adj+=(arch.base.proof+arch.base.authority+arch.base.resilience-250)*.05}if(sens>70){adj+=(arch.base.authority+arch.base.resilience-170)*.07}if(capital>=4&&['capacity','global','portfolio'].includes(arch.id))adj+=6;if(capital<=2&&['reserve','operations','balanced'].includes(arch.id))adj+=5;const obj=(profile.objective||'').toLowerCase();if(/research|science|r&d|laboratory|recherche|science/.test(obj)&&arch.id==='research')adj+=10;if(/infrastructure|compute|energy|data center|centre de données|énergie/.test(obj)&&arch.id==='capacity')adj+=12;if(/market|global|jurisdiction|international|marché|mondial/.test(obj)&&arch.id==='global')adj+=9;if(/customer|service|operations|client|opérations/.test(obj)&&arch.id==='operations')adj+=9;if(/human|workforce|career|people|humain|talent/.test(obj)&&arch.id==='human')adj+=8;if(/public|government|citizen|public|gouvernement/.test(obj)&&arch.id==='public')adj+=9;return adj}
function scoreArchitecture(profile,arch,worlds=1024){const weights=profile.weights||Object.fromEntries(WEIGHTS.map(w=>[w.id,w.default]));const totalW=Object.values(weights).reduce((a,b)=>a+Number(b||0),0)||1;const baseScore=Object.entries(weights).reduce((s,[k,w])=>s+(arch.base[k]||50)*Number(w),0)/totalW;const seed=hashString(JSON.stringify(profile)+arch.id+worlds);const r=rng(seed);const vals=[];const shocks={capability:0,evidence:0,authority:0,capital:0,irreversibility:0,cost:0};for(let i=0;i<worlds;i++){
 const cap=(r()-.5)*22,evid=(r()-.5)*18,auth=(r()-.5)*20,market=(r()-.5)*18,cost=(r()-.5)*16,incident=r()<.035?-(12+r()*24):0;
 const robustness=(arch.base.resilience+arch.base.reversibility+arch.base.authority)/3;
 let v=baseScore+profileFactor(profile,arch)+(cap*(arch.base.upside/100))+(evid*(arch.base.proof/100))+(auth*(arch.base.authority/100))+(market*(arch.base.speed/100))+(cost*(arch.base.capital/100))+incident*(1-robustness/140)-arch.complexity*.035-arch.proofDebt*.05;
 vals.push(clamp(v,0,100));shocks.capability+=Math.abs(cap);shocks.evidence+=Math.abs(evid);shocks.authority+=Math.abs(auth);shocks.capital+=Math.abs(cost);shocks.irreversibility+=(100-arch.base.reversibility)/100;shocks.cost+=(100-arch.base.capital)/100
 }
 const mean=vals.reduce((a,b)=>a+b,0)/vals.length,p10=quantile(vals,.1),tail=quantile(vals,.02),p90=quantile(vals,.9),variance=vals.reduce((s,v)=>s+(v-mean)**2,0)/vals.length;const regret=clamp(100-p10+(arch.complexity*.12)+(arch.proofDebt*.14),0,100);const confidence=clamp(100-Math.sqrt(variance)*2-arch.proofDebt*.35,0,100);return{...arch,score:+mean.toFixed(1),p10:+p10.toFixed(1),tail:+tail.toFixed(1),p90:+p90.toFixed(1),regret:+regret.toFixed(1),confidence:+confidence.toFixed(1),worlds}}
function runAuction(profile,worlds=0){const effective=worlds||((Number(profile.stakes)>80||Number(profile.sensitivity)>70)?4096:1024);const scenarios=ARCHITECTURES.map(a=>scoreArchitecture(profile,a,effective)).sort((a,b)=>b.score-a.score||a.regret-b.regret);const champion=scenarios[0],runner=scenarios[1];const reserve=[...scenarios].sort((a,b)=>a.regret-b.regret||b.p10-a.p10)[0];const successor=[...scenarios].filter(s=>s.id!==champion.id).sort((a,b)=>(b.base.compounding+b.base.proof+b.base.resilience)-(a.base.compounding+a.base.proof+a.base.resilience))[0];const stability=clamp((champion.score-runner.score)*9+champion.confidence*.55,0,100);return{runId:'auction-'+Date.now().toString(36),createdAt:new Date().toISOString(),worlds:effective,scenarios,champion,runner,reserve,successor,stability,verdict:champion.p10>=70&&champion.confidence>=65?'ADOPT':champion.p10>=55?'CONDITIONAL':'MONITOR'} }
function generateProofDebt(profile,auction,sources=[]){const ch=auction.champion;const items=[
 ['source-currentness','Verify current official sources for every material claim', 'Vérifier les sources officielles actuelles pour chaque affirmation importante',Math.round(90-ch.base.proof*.45)],
 ['authority-scope','Confirm accountable authority for every consequential action','Confirmer l’autorité responsable de chaque action conséquente',Math.round(95-ch.base.authority*.45)],
 ['rollback','Prove rollback, continuity and provider-switching paths','Prouver les voies de retour arrière, de continuité et de changement de fournisseur',Math.round(92-ch.base.reversibility*.42)],
 ['customer-value','Establish the value baseline and complete cost denominator','Établir la valeur de référence et le dénominateur complet des coûts',72],
 ['rights','Confirm rights, confidentiality, reuse and Chronicle scope','Confirmer les droits, la confidentialité, la réutilisation et la portée Chronicle',78],
 ['independence','Pre-commit independent validators and acceptance tests','Préengager les validateurs indépendants et les tests d’acceptation',82],
 ['externalities','Measure human, regulatory, market and infrastructure externalities','Mesurer les externalités humaines, réglementaires, de marché et d’infrastructure',68],
 ['live-signal','Refresh mission-critical frontier and regulatory signals','Actualiser les signaux critiques de frontière et de réglementation',sources.length?55:88]
 ];return items.map((x,i)=>({id:x[0],en:x[1],fr:x[2],vop:clamp(x[3]+(Number(profile.stakes||60)-60)*.25,20,99),status:'open',owner:i%2?'Evidence Verifier':'Authority Governor',impact:i<3?'transaction-blocking':'decision-changing'})).sort((a,b)=>b.vop-a.vop)}
function generateMissions(profile,auction){const ch=auction.champion;return MISSION_TEMPLATES.map((m,i)=>({id:m[0],nameEn:m[1],nameFr:m[2],category:m[3],status:i<3?'READY':'PLANNED',progress:0,owner:COUNCIL[i%COUNCIL.length][1],authority:i%3===0?'Accountable sponsor':i%3===1?'Proof & Authority Office':'Mission lead',proof:['Source snapshot','Acceptance test','Evidence Docket','Signed decision'][i%4],budget:Math.max(1,Math.round((i+1)*(Number(profile.capitalBand||3))*.7)),valuePotential:Math.round((ch.score/100)*(i+2)*12500),dependencies:i===0?[]:[MISSION_TEMPLATES[Math.max(0,i-1)][0]],risk:i%5===0?'high':i%3===0?'medium':'low',chronicle:'pending'}))}
function generateCouncil(profile,auction,lang='en'){const ch=auction.champion,rn=auction.runner;return COUNCIL.map((r,i)=>{const role=lang==='fr'?r[2]:r[1];const messagesEn=[
 `The frontier delta supports ${ch.en}, but official-source currentness should be revalidated before any consequential commitment.`,
 `The Capability Twin shows that authority, evidence and infrastructure are the highest-leverage gaps for this objective.`,
 `${ch.en} wins the normalized auction; ${rn.en} becomes the first switch candidate if evidence latency rises.`,
 `The mission should be decomposed into 21 bounded jobs with explicit dependencies and transaction gates.`,
 `No external action should proceed until the accountable principal, scope, tools, budget and rollback are recorded.`,
 `The strongest adverse world combines provider failure, stale evidence and premature irreversible deployment.`,
 `The top Value-of-Proof item should be retired before expanding autonomy or capital exposure.`,
 `Chronicle admission should be narrow; the successor must outperform on a fresh, separately accepted mission.`,
 `Verified contribution should first fund evidence, resilience and high-frequency mission capacity.`,
 `Adopt a three-horizon portfolio: immediate champion, successor after Proof Debt retirement and minimal-regret reserve.`,
 `Collect only necessary data, keep secrets out of public-static surfaces and bind reuse to explicit rights.`,
 `Monitor human agency, market concentration, infrastructure load and public-interest effects alongside financial value.`
 ];const messagesFr=[
 `Le delta de frontière appuie ${ch.fr}, mais l’actualité des sources officielles doit être revérifiée avant tout engagement conséquent.`,
 `Le Jumeau de capacité montre que l’autorité, la preuve et l’infrastructure sont les écarts au plus fort effet de levier.`,
 `${ch.fr} remporte l’enchère normalisée; ${rn.fr} devient le premier candidat de bascule si la latence de preuve augmente.`,
 `La mission devrait être décomposée en 21 tâches bornées avec dépendances explicites et portes transactionnelles.`,
 `Aucune action externe ne devrait commencer avant l’enregistrement du principal, de la portée, des outils, du budget et du retour arrière.`,
 `Le monde adverse le plus fort combine défaillance de fournisseur, preuve périmée et déploiement irréversible prématuré.`,
 `Le premier élément Valeur-de-la-preuve devrait être retiré avant d’étendre l’autonomie ou l’exposition en capital.`,
 `L’admission Chronicle doit être étroite; le successeur doit surperformer sur une mission neuve et acceptée séparément.`,
 `La contribution vérifiée devrait d’abord financer la preuve, la résilience et les missions à haute fréquence.`,
 `Adopter un portefeuille à trois horizons : champion immédiat, successeur après retrait de la dette de preuve et réserve à regret minimal.`,
 `Ne recueillir que les données nécessaires, exclure les secrets des surfaces publiques et lier la réutilisation à des droits explicites.`,
 `Surveiller l’agentivité humaine, la concentration du marché, la charge d’infrastructure et les effets d’intérêt public avec la valeur financière.`
 ];return{id:r[0],role,message:(lang==='fr'?messagesFr:messagesEn)[i],timestamp:new Date(Date.now()+i*700).toISOString()}})}
function singularityExposure(profile,sources=[]){const capabilityHalfLife=Math.max(7,65-(sources.length*2)-Number(profile.weights?.speed||70)*.25);const adaptationLag=Math.max(5,110-Number(profile.weights?.proof||85)*.3-Number(profile.weights?.authority||85)*.25-Number(profile.weights?.speed||70)*.15);return{capabilityHalfLife:+capabilityHalfLife.toFixed(1),adaptationLag:+adaptationLag.toFixed(1),ratio:+(adaptationLag/capabilityHalfLife).toFixed(2)}}
function pulse(state){const a=state.auction||runAuction(state.profile,1024),m=state.missions||[],r=Object.values(state.receipts||{}),proofPct=Math.round((r.filter(Boolean).length/Math.max(1,r.length))*100),missionHealth=m.length?Math.round(m.reduce((s,x)=>s+(x.status==='COMPLETE'?100:x.status==='RUNNING'?72:x.status==='READY'?55:x.status==='BLOCKED'?15:30),0)/m.length):0,verifiedValue=(state.valueEntries||[]).filter(v=>v.stage==='verified').reduce((s,v)=>s+Number(v.amount||0),0),ser=singularityExposure(state.profile,state.sourcePack?.sources||[]);return{ser:ser.ratio,proof:proofPct,authority:Math.round(((state.authorities||[]).filter(a=>a.status==='active').length/Math.max(1,(state.authorities||[]).length)*70)+(proofPct*.3)),missions:missionHealth,value:verifiedValue,resilience:Math.round((a.champion.base.resilience+a.champion.base.reversibility)/2),frontier:Math.min(100,30+(state.sourcePack?.sources?.length||0)*6),compounding:Math.round((a.champion.base.compounding+proofPct)/2)}}
function switchConditions(auction,lang='en'){const ch=auction.champion,r=auction.runner;return lang==='fr'?[`Basculer vers « ${r.fr} » si la preuve requise dépasse le délai décisionnel.`,`Suspendre si la couverture d’autorité descend sous 80 % pour une action conséquente.`,`Déclencher la réserve « ${auction.reserve.fr} » si le P10 descend sous 55.`,`Réouvrir l’enchère après tout changement matériel de modèle, de loi, de capital ou d’infrastructure.`]:[`Switch to ${r.en} if required evidence exceeds the decision window.`,`Pause if authority coverage falls below 80% for a consequential action.`,`Activate reserve option ${auction.reserve.en} if P10 falls below 55.`,`Re-run the auction after any material model, law, capital or infrastructure change.`]}
function commandSequence(state,lang='en'){const ch=state.auction?.champion||runAuction(state.profile).champion;return lang==='fr'?[['0–72 h',`Revérifier les signaux déterminants, figer l’enveloppe d’autorité et lancer le premier test borné de « ${ch.fr} ».`],['30 jours','Retirer les trois principales dettes de preuve, mettre à jour le Jumeau de capacité et obtenir un résultat accepté.'],['90 jours','Constituer le portefeuille récurrent, admettre une capacité étroite dans Chronicle et exécuter une comparaison successeure.'],['365 jours','Maintenir la cadence du Bureau, composer la valeur vérifiée et réallouer le capital vers la capacité productive.']]:[['0–72h',`Revalidate decision-changing signals, freeze the authority envelope and launch the first bounded ${ch.en} pilot.`],['30 days','Retire the top three Proof Debt items, update the Capability Twin and obtain one accepted outcome.'],['90 days','Constitute the recurring portfolio, admit one narrow Chronicle capability and run a successor comparison.'],['365 days','Operate the Office cadence, compound verified value and reallocate capital into productive capacity.']]}
function sampleValueEntries(){return[{id:'value-1',name:'Decision time avoided',amount:125000,stage:'validated',evidence:'Baseline and elapsed-time comparison'},{id:'value-2',name:'Risk exposure retired',amount:250000,stage:'modeled',evidence:'Scenario risk model'},{id:'value-3',name:'Capital unlocked',amount:500000,stage:'identified',evidence:'Candidate funding route'}]}
function sampleIncidents(){return[{id:'inc-1',title:'Source expiry on critical assumption',severity:'medium',status:'open',owner:'Evidence Verifier',createdAt:new Date().toISOString()},{id:'inc-2',title:'Single-provider concentration above policy',severity:'high',status:'mitigating',owner:'Resilience Engine',createdAt:new Date().toISOString()}]}
function verifyState(x){return x&&x.schema==='goalos.singularity-office.state.v1'&&x.profile&&typeof x.profile.objective==='string'}
window.GoalOSEngine={RELEASE,WEIGHTS,CAPABILITIES,ARCHITECTURES,COUNCIL,RECEIPTS,MISSION_TEMPLATES,MONITOR_DOMAINS,CADENCE,defaultProfile,defaultState,runAuction,generateProofDebt,generateMissions,generateCouncil,singularityExposure,pulse,switchConditions,commandSequence,sampleValueEntries,sampleIncidents,verifyState,hashString,clamp};
})();
